### ISSUE TITLE
(#203) Build Our topic landing page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#105]
### Done criteria 
- [x]  Create as standard page and use box links for topics
- [x] Create research topic teaser if required
---
### Designs
- [Landing page](https://invis.io/K5CGE4K9M)
- [Our topic](https://invis.io/WTCJKJ4PA) and [another topic](https://invis.io/42CJKJH5B) 
---
### ALNAP to check 
Don't need to sign off the build, just the theming.

**Comment by dilwarhussain** [comment]
http://alnap-dev.mrmdev.co.uk/our-topics

**Comment by Maria-alnap** [comment]
@dilwarhussain would you please send me the login details again? Thanks!

**Comment by angievanhegan** [comment]
@Maria-alnap You're on it! I probably shouldn't have assigned this to you now. I'm getting this column ready for you to start work on after your training next week. That said, I've just realised that this is just build so there's nothing for you to review - we're going to send you the pages once the design has been applied, then you'll be able to test everything. I'm going to move this straight into the done column! Angie
