### ISSUE TITLE
Build Blog author user profile

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#107]
- [ ] Add views to user profile page to achieve this (await wireframe)

- Currently those who make comments have a click through profile page.
- Blog authors do need a profile page, but don't need to list comments

This will probably be a mix of Drupal and Civi fields.
Depends on #156  Wireframe blog author profile
Linked to #40

**Comment by cat-manta** [comment]
@Maria-alnap Have designed this page now, link is below:
https://invis.io/3TCA5T6U7#/240257402_Blog_Author_Profile_V0-1
