### ISSUE TITLE
About / What we do page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#110]

**Comment by angievanhegan** [comment]
@russ-manta Another one dragged out of the backlog. I'm just putting it here in case we've missed something. What should we do with this? Thanks

**Comment by russ-manta** [comment]
@ican-icant do you know anything about Networks and Lesson papers?

**Comment by ican-icant** [comment]
@russ-manta  This section will be full of standard text pages describing what they do, rather than have views of docs etc. A lesson paper is a resource, but in this section they will explain their role is to create them rather than list them all here.

**Comment by russ-manta** [comment]
@angievanhegan I think we have this all covered with the other About card - I'll move this to Done
