### ISSUE TITLE
(#201) Build + Theme resource series nugget

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#112]
### Dependancies
-  [x] Scope resource series #141 
---
### Done criteria

- [x] Use nugget already created in Resource series content type and the existing entity reference to Resource series from a resource
- [x] Rabbit hole Resource series nodes
- [x] Change view on the resource node so it it only shows 1 resource series and instead of showing a link to the resource series node it shows all the resources within that resource series (except the one you are currently on) with the same presentation as the related resources view (beneath) - http://alnap-dev.mrmdev.co.uk/test-innovation-resource
- [x] Remove any excess/unneeded content added to the demo resource series nodes

----
### ALNAP to check

[Resource series example ](http://alnap-dev.mrmdev.co.uk/test-innovation-resource)

- [x] Test creating a resource series and it functions / looks as expected

**Comment by angievanhegan** [comment]
@cutlern Would you be able to let me have  link to what you've built? Thanks

**Comment by cutlern** [comment]
@angievanhegan http://alnap-dev.mrmdev.co.uk/about/what-we-do/innovation-in-humanitarian-action

**Comment by angievanhegan** [comment]
@cutlern I'm in!! I had no idea there was so much to see! I love the flowers :hibiscus: :cherry_blossom: I think this looks really good and is just a clearer version of what what they already have. I think I just need to double check with Maria that it's what they were expecting. Then when Russ has reviewed it, we'll send it to Maria for review. @russ-manta is that ok with you?

**Comment by russ-manta** [comment]
@cutlern I've updated  the subtasks for this task (above) to show what we now need to do tomorrow morning. Shouldn't be too much more work I think. Mainly a view change and rabbit holing. I'll slack you about this too

**Comment by angievanhegan** [comment]
@russ-manta Please can you add criteria for Maria (under the heading 'ALNAP to check') so she knows how to review/test this? Thanks

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan the resource page sample link assigned for me to check above is dead. I did check the link under "done criteria" and it looks good to me, if that helps!

**Comment by angievanhegan** [comment]
@Maria-alnap Sorry, by bad. You check the right thing though. I'll move this to done :smiley:
