### ISSUE TITLE
(#209) Build and theme Member update CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#113]
### Done criteria
- [x] Same fields as news for now then we see based on #82
- [x] Build and theme according to design
- [x] Card content fieldset description
- [x] Language selection field - do we need this? 
- [x] Add field for Organisation (entity ref)
- [x] Add associated organisation to the RHS of member updates in the same way as  news [example](http://alnap-dev.mrmdev.co.uk/omnis-enim-est-natura-diligens-sui)
- [x] BLOCKER - Currently hidden from everyone but admin and editors.
- [x]  Create account for @ican-icant to test
- [x] Privacy settings (only members can see this)
---
### ALNAP to check
[Test page](http://alnap-dev.mrmdev.co.uk/member-update-test-01)
- [x] Can view Member updates
- [x] Can edit existing Member updates
- [x] Can add new Member updates
- [x] Content type has all the necessary fields
- [x] Nodes can't be viewed when logged out (get access denied)

**Comment by dilwarhussain** [comment]
http://alnap-dev.mrmdev.co.uk/admin/structure/types/manage/member-update/fields

**Comment by nadia847** [comment]
@dilwarhussain 

Missing:
- [ ] Card content fieldset description
- [ ] Language selection field - do we need this? 
- [ ] Privacy settings (only members can see this)

**Comment by angievanhegan** [comment]
@nadia847 can these missing things be moved into the Done criteria at the top?

**Comment by angievanhegan** [comment]
There's no explanation as to why @dave-manta and @ican-icant are assigned to this task so I'm removing them.

**Comment by nadia847** [comment]
@angievanhegan I've moved them up. I think they were probably assigned for scoping

**Comment by russ-manta** [comment]
@ican-icant should member updates have the logo of the organisation it's related to diplsayed on the right: http://alnap-dev.mrmdev.co.uk/member-update-test-01  like on news ? http://alnap-dev.mrmdev.co.uk/news/english-accumsan-amet-cogo-fere-qui

**Comment by ican-icant** [comment]
@russ-manta  yes I think that works

**Comment by russ-manta** [comment]
@cutlern can you add the associated organisation to the RHS of member updates in the same way you did for news please? eg on this page: http://alnap-dev.mrmdev.co.uk/omnis-enim-est-natura-diligens-sui

**Comment by russ-manta** [comment]
@nadia847 can you check the permissions on this please?  I can't see member update nodes logged in as a full member and I can't see the feed on my profile either. I can only see if I have the role of editor.

**Comment by angievanhegan** [comment]
@nadia847 please can you add a 'blocker' done criteria so we can see why it's in here. Ta!

**Comment by russ-manta** [comment]
@meldera can you look at the permissions issue on this one please?

**Comment by ican-icant** [comment]
@angievanhegan @meldera the more button is still not right.

**Comment by nadia847** [comment]
@ican-icant you have an account. use your email address and the usual password.

**Comment by ican-icant** [comment]
@nadia847 I've logged - with my steve@m account in and I can't see any member updates?

**Comment by nadia847** [comment]
@ican-icant your role was removed. now re-added. Please try again.

**Comment by ican-icant** [comment]
@nadia847 it works!, but there was nothing for to tick off so added one and ticked it

**Comment by nadia847** [comment]
@ican-icant yeah all the tick boxes should have been unchecked for you. I've now done this. Could you please go through and check any off that can be and add any issues as necessary? thanks!

**Comment by angievanhegan** [comment]
@Maria-alnap I think this is ready for you to review.

**Comment by Maria-alnap** [comment]
@nadia847 @ican-icant @russ-manta All this looks good! I'll move to done

**Comment by Maria-alnap** [comment]
@nadia847 apols, I think I closed this by mistake and don't know how to reopen it!)

**Comment by nadia847** [comment]
@Maria-alnap ha no worries! I've moved it to "Done this sprint". Is that where it should be?
