### ISSUE TITLE
Build promo nugget

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#114]
The promo content type should be referenced via a nugget so it can appear anywhere

See content model for fields

- [ ] Add paragraph type
- [ ] Add to sections views

**Comment by nadia847** [comment]
@ican-icant this method might not work when we have a page (such as the news landing page) which is a View page not a content page with views (see comments on card #32 to address how we build search pages)

**Comment by angievanhegan** [comment]
NELLE: @arseni can promo descriptions have full text formats so they can use different style colour fonts for their descriptions? or is there a better way to let them have that functionality?


ARSENI: I think access to "full text" would be expected. No point in creating a specific text format just for promos either.. Will have to trust editors not to mess it up
