### ISSUE TITLE
(#201) Building resources feed importers

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#116]
### Done criteria
- [x] Complete import feed
- [x] Run test import
- [x] Ensure regions are imported for resources
---
### ALNAP to check
- [ ] Check resource content is imported as expected?

**Comment by russ-manta** [comment]
@meldera Alnap have confirmed that they use the region on resources for searching so we'll need to add/use this: http://www.alnap.org/resources/results.aspx?q=|ta

**Comment by angievanhegan** [comment]
@russ-manta This was in the backlog but it looks like it should be in sprint 5. Not sure which column.

**Comment by russ-manta** [comment]
@angievanhegan it's done I'll move it over

**Comment by angievanhegan** [comment]
@russ-manta Is there anything here for ALNAP to check? Or could it actually move into Done?
