### ISSUE TITLE
(#201) Build resource node views

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#122]
### Done criteria
- [x] Related resources view
- [x] View of fields in the design and file download
- [x] Research series (#112)
----
### Designs
- <a href="https://invis.io/ANC0GIX8Q">Resources wide</a>
- <a href="https://invis.io/ZTCBNO4N6">Resources mobile</a>
---
### ALNAP to check
ALNAP only need to review this once it's been themed (see #172)
- [ ] Check lists/displays of related resources on a resource page look correct and have the correct fields of text etc

**Comment by dilwarhussain** [comment]
@angievanhegan @russ-manta @ican-icant @nadia847 @meldera  Related resources on the resource node. Are these being related using the 'Related resources' field? This is currently a text field. This relates to @cutlern work on #112 as well

**Comment by russ-manta** [comment]
@dilwarhussain Is the text field on the content type is related to the import but the entity ref beneath is the field being used going forward

**Comment by dilwarhussain** [comment]
@russ-manta So just to clarify we will use 'field_related' to do the related resources? What will happen with existing relations if they are in a text field atm?

**Comment by russ-manta** [comment]
@dilwarhussain Arseni is dealing with existing related resources from the text field during the import

**Comment by angievanhegan** [comment]
@dilwarhussain do you have a second to add a link to an example of a resource page on the dev site please? This is the most complete example I could find http://alnap-dev.mrmdev.co.uk/test-innovation-resource Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan That's the test resource I've been using to create and theme the resources.

**Comment by russ-manta** [comment]
This is related to #112 which @cutlern will finish tomorrow to complete this task

**Comment by ican-icant** [comment]
@dilwarhussain - a few things I've spotted:
> DOWNLOAD needs a rollover
> SHARE icons are missing
> Check position of title to the design
> Download button needs to be in line with the top of the white box
>  Remove the black dot at the end of the word organisation
> Size of text under Author and Organisation looks smaller than other titles

**Comment by russ-manta** [comment]
@dilwarhussain @ican-icant we are not doing share icons as part of this sprint

**Comment by dilwarhussain** [comment]
Thanks @russ-manta . @ican-icant Those changes have been made bar the share icons.

**Comment by angievanhegan** [comment]
@russ-manta Can I move Steve's comments over to #123 (build share widget) then move this to done? I think ALNAP only need to look at the page once it's been themed (#172)

**Comment by angievanhegan** [comment]
@dilwarhussain Should these comments from Steve be added to #172? Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan I've made those changes to the resource node, the share icons still need to be added. I'll talk to @nadia847 about those now.

**Comment by angievanhegan** [comment]
Thanks @dilwarhussain Are they part of this issue or @172 (the theming issue)?

**Comment by Maria-alnap** [comment]
@angievanhegan just checked this here:
http://alnap-dev.mrmdev.co.uk/test-innovation-resource 
... and some of the resource cards show title, organisation and author while others in that same page only  show title and organisation.

**Comment by Maria-alnap** [comment]
@angievanhegan just checked this here:
http://alnap-dev.mrmdev.co.uk/test-innovation-resource 
... and some of the resource cards show title, organisation and author while others in that same page only  show title and organisation.

**Comment by russ-manta** [comment]
@Maria-alnap these are just resources where no author has been added. If one is added it shows.  Should we make the authors field a required field to make sure there is always a value for Author?

**Comment by Maria-alnap** [comment]
@russ-manta I thought that would be the case! No worries, let's leave as is. Some resources will have an organisation as the author, not a particular person, so the current set up is fine.
