### ISSUE TITLE
(#217) Build Share widget

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#123]
and ensure it works on each shareable content type (news, blocks, etc)

### Done criteria
- [x] Share widgets on: News, events, blogs, jobs, resources
- [x] Can share content on each social network
---
### Designs
- [ ] https://projects.invisionapp.com/share/ANC0GIX8Q#/screens
---
### ALNAP to check
e.g. http://alnap-dev.mrmdev.co.uk/blogs/blog-4

![Screen Shot 2017-08-22 at 17.54.13.png](https://images.zenhubusercontent.com/5970b09e61b4ca3b0a751dc3/91af692c-9b2f-4131-9c18-865be4ae615a)

- [x] Share widgets on: News, events, blogs, jobs, resources
- [x] Can share content on each social network
- [x] Look like the design

**Comment by angievanhegan** [comment]
this has been done (as part of the blog page build)

**Comment by Maria-alnap** [comment]
@nadia847 again, unsure what I'm meant to be looking at here

**Comment by nadia847** [comment]
@Maria-alnap added a link and screenshot. In this case you need to flag any content type that should have share icons that does not.

And ensure that the share icons work (only need to test that on one page though e.g. blog 4 linked to above)

**Comment by Maria-alnap** [comment]
@nadia847 Thanks! All of this looks good. I'll move to done :)
