### ISSUE TITLE
(#200) Header

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#124]
### Done criteria
- [x] Add logo
- [x] Add facebook, twitter and youtube icon and link
- [x] Add Login/Register links
- [x] Add google translate (showing outline)
- [x] Nav/ menu
- [x] Including search
- [x] Mobile version 
- [x] Theme
----
### Designs
- [Homepage wide](https://invis.io/NSCBN3KQ5)
- [Homepage wide nav](https://invis.io/6KCBN4KYE)
- [Mobile version](https://invis.io/9XCBN2XZ4)
- [Mobile nav](https://invis.io/5MCBMRUDQ)
---
### ALNAP to check
- [x] Logo
- [x] Social icons
- [x] Login/Register links
- [x] Google translate
- [x] Nav/ menu including search
- [x] Mobile version

**Comment by ican-icant** [comment]
@pipemanta - please make NAV text CAPS and space them out more in line with the design.

Please add ALNAP youtube icon (per the design) and link to https://www.youtube.com/channel/UCFFvUaLbZpNk1_X3UXWryTQ

**Comment by angievanhegan** [comment]
@ican-icant Can you review please? Thanks

**Comment by ican-icant** [comment]
- missing youtube icon and link
- cant see the outline around the google translate button

**Comment by angievanhegan** [comment]
@russ-manta I've updated the done criteria. Please can you reassign this? Thanks

**Comment by russ-manta** [comment]
@pipemanta can you complete the missing items in the done section please?

**Comment by pipemanta** [comment]
@russ-manta @ican-icant ready done criteria, I leaved empty the checkbox for QA

**Comment by ican-icant** [comment]
@angievanhegan - all signed off by me :)

**Comment by angievanhegan** [comment]
Ready for you to sign off @Maria-alnap

**Comment by Maria-alnap** [comment]
@angievanhegan thanks! Only think that's not showing up for me in header is the register button (hence that's the only one I haven't checked. All the rest if OK!

**Comment by angievanhegan** [comment]
@Maria-alnap what browser are you using?
@russ-manta this needs reassigning. Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan I'm using Chrome but I've also checked in IE but the register button is defo not there.

**Comment by russ-manta** [comment]
@Maria-alnap are you logged into the site?  The register button only shows if you are logged out.

**Comment by Maria-alnap** [comment]
@russ-manta Dah! Of course... I completely hadn't thought about that! It is fine. I'll tick it now :)

**Comment by angievanhegan** [comment]
@maria-alnap please can you drag this into the Done this spring column? Thanks
