### ISSUE TITLE
(#200) Footer

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#125]
### Done criteria
- [x] Add contact details
- [x] Youtube icon and link
- [x] Add mailchimp signup linked to the ALNAP list
- [x] Add footer links (disclaimer | privacy policy)
- [x] It should be 'Website by Manta Ray Media'
- [x] Theme
- [x] Mobile version
----
### Designs
- [Homepage wide](https://invis.io/NSCBN3KQ5)
- [Homepage wide nav](https://invis.io/6KCBN4KYE)
- [Mobile version](https://invis.io/9XCBN2XZ4)
- [Mobile nav](https://invis.io/5MCBMRUDQ)
---
### ALNAP to check
[Home page](http://alnap-dev.mrmdev.co.uk/)
- [x] Contact details
- [x] Social icons
- [x] Mailchimp sign up
- [x] Links

**Comment by angievanhegan** [comment]
@russ-manta There's a note on the RT board to say that the mailchimp signup should integrate with Civi. Is that something we've factored in here? Thanks.

**Comment by russ-manta** [comment]
@angievanhegan it's irrelevant here.  We'll be adding Civi mailchimp integration but that is independent of this form

**Comment by angievanhegan** [comment]
@ican-icant Please can you review this? Thanks

**Comment by ican-icant** [comment]
All good, but:
- Missing youtube icon and link
- it's connected to manta ray newsletter
- It should be 'Website by Manta Ray Media' - it's not a remora site

**Comment by angievanhegan** [comment]
I've added 1 and 3 to the done criteria and created a new issue for 2 (#207) so that it can be linked when the newsletter has been setup. @russ-manta please can you assign this to someone to complete the last few done criteria? Thanks

**Comment by russ-manta** [comment]
@pipemanta can you complete all the checkbox done items above please?

**Comment by angievanhegan** [comment]
@ican-icant  Please can you review this?

**Comment by ican-icant** [comment]
All good @angievanhegan :)

**Comment by angievanhegan** [comment]
Ready for you to sign off @Maria-alnap .

**Comment by Maria-alnap** [comment]
@angievanhegan thanks! Only one I haven't ticked is the Mailchimp one, as we haven't set that up yet. I did test test it and it works but the setup would need to be updated when we have that ready.

**Comment by angievanhegan** [comment]
@Maria-alnap I think this might be covered in #207 - but I've added mention of it to the notifcations sprint goal so we don't forget about it.
