### ISSUE TITLE
(#214) Build and theme site search

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#127]
### Done criteria
- [x] Set up apache solr
- [x] Set up search API
- [x] Build general search based on help search but for all content types (except excluded) see requirements below
  - [x] searches all site content INCLUDING  resources
  - [x] Search within PDF text (very important)
  - [x] Search with keywords
  - [x] Results filtered by content type
- [x] Theme search page
- [x] Link search in nav to this search page

Client meeting 7 July Maria confirmed we don't need synonym searching here.

---
### Designs
- [ ] Need a design for expanded search box (from main menu)
- [ ] Need a design for results if different from help search type display
---
### ALNAP to check
- [x] Build general search based on help search but for all content types (except excluded) see requirements below
  - [x] searches all site content INCLUDING  resources
  - [x] Search within PDF text (very important)
  - [x] Search with keywords
  - [x] Results filtered by content type
- [x] Theme search page
- [x] Link search in nav to this search page

**Comment by nadia847** [comment]
@russ-manta We're not using core drupal search for this, are we?

**Comment by russ-manta** [comment]
@nadia847 no we're using search api & solr

**Comment by nadia847** [comment]
@russ-manta cool thanks requirements updated. I also think this task is probably more a 40 than a 20, especially considering we have lots of entity ref relationships

**Comment by angievanhegan** [comment]
@Maria-alnap Please add any specific requirements at the top of this issue.

**Comment by angievanhegan** [comment]
Copied from issue #147

RUSS:  For the main site search can we confirm what functionality you need?

search with keyword box and filter by content type
Search within pdfs/documents
showing recommended resources etc based on other searches

Are there more requirements than this?

MARIA: these 3 would suffice for the main site search. Would the results here be listed by relevance?

**Comment by angievanhegan** [comment]
@ican-icant I have an action to confirm we've got all Maria's requirements for site search (and that none of them will need costing). Is there another site search Manta Ray have already built that I can use as a basis of my discussions with Maria on? I'm hoping to do this this week. Thanks

**Comment by russ-manta** [comment]
Linked with #59. Main resources search is the key search. The site search can probably use the same search api config but not filter out non-resource content types.

**Comment by russ-manta** [comment]
@meldera can you theme other content type labels such as organisation & team (and all others) in the same way as organisation: http://alnap-dev.mrmdev.co.uk/search?keywords=alnap

Also should we have a brief text summary beneath the title?

**Comment by Maria-alnap** [comment]
This looks and works OK.
