### ISSUE TITLE
(#247) Migrate resources (final)

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#129]
### Done criteria
- [ ] Final resource migration - copy all from live alnap site
- [ ] Consider how to deal with any stragglers (after cutoff date)
---
### ALNAP to check
- [ ] All resources present and correct

**Comment by nadia847** [comment]
Remora countries vs something new
Internal and public tags still required?

@russ-manta

**Comment by angievanhegan** [comment]
@russ-manta We haven't captured this in the roadmap for this week? Should we be doing it later?
