### ISSUE TITLE
(#137) Redirects for resources

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#131]
### Done criteria
- [ ] Programatic redirects for resources (and only resources!)
---
### ALNAP review criteria
- [ ] Redirection from old urls is correctly going to new ones

**Comment by angievanhegan** [comment]
@Maria-alnap We discussed this before, but I'm not sure if we came to a satisfactory conclusion. Do we need redirects for all three of the content types listed above, or just resources? Thanks.

**Comment by Maria-alnap** [comment]
@angievanhegan I think we'll need not only redirects for this but also for the topics and about pages. Happy to be explained further about this, as I may be misunderstanding, but I guess what we're after here is for users to be able to access the new About and topic pages via redirects when going to the URL of the old ones, right?

**Comment by angievanhegan** [comment]
@Maria-alnap yes, that's exactly what this is. Can you confirm how many topics pages you have? 

@dave-manta Please can you let us know if this is all within scope of the budget? Thanks

**Comment by dave-manta** [comment]
@angievanhegan yes, it's within scope. I recollect agreeing that we wouldn't be doing redirects for resources, however we can for any other content we're automatically migrating. In addition, ALNAP can make manual redirects for things like research topics as there are only a few today.  OK?

**Comment by angievanhegan** [comment]
@dave-manta On issue #9 we sort of confirmed that we'd be migrating resources. The only other thing we're migrating is blog comments, which obviously won't need redirects. Let's clarify this on Friday. It's for a future sprint so we don't need to do it now.

**Comment by dave-manta** [comment]
@angievanhegan do you mean we confirmed that we'd be migrating resources **redirects**?  If that's the case, Ok.

**Comment by Maria-alnap** [comment]
@angievanhegan you can find the number of topic pages in the IA in your whiteboard, I think it's like 12 or 15 of them?

**Comment by angievanhegan** [comment]
FYI @russ-manta @nadia847 - @Maria-alnap and I just spoke. We agreed that there will be a programatic redirection of the resources content and then we'll provide the ability for them to redirect any other pages they like (from within Drupal).

**Comment by angievanhegan** [comment]
@russ-manta Please can you write the done criteria and size this. Thanks very much :o)
