### ISSUE TITLE
(#234) Scoping member organisation registration

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#135]
we'll leave their current process as is - which is for prospective member to send an email and if ALNAP think they could be a member, they send them a form to complete.  May consider making this form a Civi form, but that's not relevant for the website build.

### Done criteria
- [ ] Confirm process
- [ ] Do we need to build a webform?
- [ ] Create new tasks to build any new functionality as required
- [ ] How are payments taken?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by dave-manta** [comment]
@Maria-alnap would you mind uploading the various member registration forms you put in Slack here please.

**Comment by Maria-alnap** [comment]
[Uploading New Members Application Form NGO.docx...]
[Uploading New Members Application Form Red Cross_Red Crescent.docx...]
[Uploading New Members Application Form.docx...]
[Uploading Guidance notes for applicants.docx...]

**Comment by Maria-alnap** [comment]
There you go :)

**Comment by dave-manta** [comment]
@Maria-alnap thanks, although I can't seem to get access to the files.  For some reason doc files are not supported. Could you save them and upload as docx.  Also, there seems to be a lot of tracked comments in them. Could you send 'clean' versions?

@russ-manta @angievanhegan

**Comment by Maria-alnap** [comment]
They were docx...

**Comment by Maria-alnap** [comment]
I'll try again

**Comment by Maria-alnap** [comment]
[Uploading Guidance notes for applicants.docx...]

**Comment by Maria-alnap** [comment]
[Uploading New Members Application Form Red Cross_Red Crescent.docx...]
[Uploading New Members Application Form.docx...]
[Uploading New Members Application Form NGO.docx...]

**Comment by Maria-alnap** [comment]
Should I try with PDFs?

**Comment by nadia847** [comment]
[test.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317329d2699000201a6665/125516c66e82c728ace21e0d46fc918937c0cfeb9ffbb049a15ee4d67304722a7a55f07c26d0b12dee167d025f5f4cff170e0d17faaa9b37b4f46d2ede0356b49b381d66cc2f12aeb2831bb606be258e498cb2bb8a48d2a5.pdf)

**Comment by nadia847** [comment]
[test.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317329d2699000201a6665/125516c66e82c728ace21e0d46fc918937c0cfeb9ffbb049a15ee4d67304722a7a55f07c26d0b12dee167d025f5f4cff170e0d17faaa9b37b4f46d2ede0356b49b381d66cc2f13aab2831bb606be258e488cbebc8349d2a5.docx)

**Comment by nadia847** [comment]
[test.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317329d2699000201a6665/125516c66e82c728ace21e0d46fc918937c0cfeb9ffbb049a15ee4d67304722a7a55f07c26d0b12dee167d025f5f4cff170e0d17faaa9b37b4f46d2ede0356b49b381d66cc2f13aab2831bb606be258e4780bebf8248d2a5.docx)
[test.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317329d2699000201a6665/125516c66e82c728ace21e0d46fc918937c0cfeb9ffbb049a15ee4d67304722a7a55f07c26d0b12dee167d025f5f4cff170e0d17faaa9b37b4f46d2ede0356b49b381d66cc2f12aeb2831bb606be258e4782b2ba8e44d2a5.pdf)

**Comment by nadia847** [comment]
Hi @Maria-alnap (sorry for the spamming!) The uploads seem to work ok for me. Are you keeping all the text that appears after the name of the file when you save your comment? 

Are you seeing the files as links when you save?
![Screen Shot 2017-06-14 at 16.58.02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317329d2699000201a6665/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f76b7191a379e90c2e59415f4cbe5d4a1f06a3a3dc78e2a436628f5508ecd26a5971c46810a8eed11fbf03e976dd1dd6b0ef9850d2aa6c7bb3d4d216744b470a83ed5e37aa984fc15ff24ee44452a0153362f43b.png)

**Comment by angievanhegan** [comment]
@Maria-alnap Sorry, we just decided that we're going to use Active Collab for storing docs. Are you ok to upload it there, then add links from here? Thanks Angie

**Comment by Maria-alnap** [comment]
ok

**Comment by Maria-alnap** [comment]
http://projects.mantaraymedia.co.uk/proxy.php?proxy=forward_preview&module=system&v=5.13.13&b=DEV&context=files&id=1491&size=261631&md5=fda4f27c9f74eac1be43dad0b36f9f9d&timestamp=2017-06-14+16%3A02%3A22

**Comment by Maria-alnap** [comment]
Does that work? (Would you pls check before I do the rest?)

**Comment by Maria-alnap** [comment]
I've just uploaded them here: http://projects.mantaraymedia.co.uk/projects/189/files

**Comment by Maria-alnap** [comment]
(first link was for just the first of the files)

**Comment by angievanhegan** [comment]
@Maria-alnap The first link doesn't work. But the second link does.

**Comment by Maria-alnap** [comment]
Great!

**Comment by Maria-alnap** [comment]
The files you need are the last 4 uploaded there :)
