### ISSUE TITLE
Scope Resource series PAGE

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#141]
For launch, we'll build a nugget that allows a resource to show a list of other resources in that series  (see #112)

In the future, ALNAP may require a resource series page which they can reference from other places in the site. 

The notes below are from the discussions, clarifying a short term (nugget) approach and a possible longer term (page) approach.

**Comment by dave-manta** [comment]
@Maria-alnap could you give post a few links to resource series on your current site, which will help guide our implementation.  Thanks.

**Comment by Maria-alnap** [comment]
@dave-manta sure, the case studies in the link below would be a good example: http://www.alnap.org/what-we-do/innovation#case_studies

**Comment by Maria-alnap** [comment]
(the report above them in that page would also be part of the series)

**Comment by dave-manta** [comment]
Thanks @Maria-alnap 

@nadia847 I believe the example Maria has sent matches my ideas from earlier. A separate content with entity references, displaying a view of all related content in the main content area and then on individual nodes, saying they are part of a series and linking to that.  Do you agree>

**Comment by angievanhegan** [comment]
@dave-manta Would we need a wireframe for this so that Maria can confirm what's going to go on it?

**Comment by angievanhegan** [comment]
@russ-manta I don't think this is in our sprint for this week. Would it be helpful to scope it now, or could we leave it until it's in the sprint? Thanks

**Comment by nadia847** [comment]
@dave-manta I agree. I also think this might need to be a content type with nuggets in order to do all the expanding/collapsing bits and the "Resources on similar topics" which is in addition to the resources in the series. What say you?

@angievanhegan Dave and I had a little chat yesterday and I'm not sure there's much scoping to be done here, just need confirmation on ^ from Dave and we're good to go.

**Comment by russ-manta** [comment]
@angievanhegan @nadia847 sounds like not too much scoping needed. It doesn't affect resources themselves apart from a link saying they are part of a series. So doesn't affect what we have done/are doing so far on resources

**Comment by nadia847** [comment]
@angievanhegan  @russ-manta Well we need to display a view on any resources that are part of a series that they are part of a series but there's not much in that.

**Comment by angievanhegan** [comment]
@dave-manta Are you happy to approve the above plan? No wireframe needed? If you're ok with this, please add a note here and move to the backlog. And let Nadia know she can go ahead with issue #112 Thanks.

**Comment by dave-manta** [comment]
I'm not sure I follow Nadia's question above or understand the need for nuggets. I believe this should be discussed in a scoping meeting, rather than in this thread.  Also, may have relevance for Resources import.

**Comment by russ-manta** [comment]
@Maria-alnap another quick question on resource series if I may.  We're planning on building this ias a separate content type although it shares most of the fields with a resource.  Can you confirm that a resource series page would not appear in the results when searching the HELP resource library?

**Comment by Maria-alnap** [comment]
@russ-manta, yep, that's right. We're not expecting resource series to appear in search results. We could maybe add them as recommendations?

**Comment by angievanhegan** [comment]
@ican-icant Just so that we know exactly what we're doing, I think it'd actually be helpful to have a wireframe for this. Do you have time to oblige? :o)

**Comment by angievanhegan** [comment]
@ican-icant How are you getting on with this? Nelle needs it to be able to work on her issue and to get it done for the end of the sprint. Thanks!

**Comment by angievanhegan** [comment]
Hi @Maria-alnap. I'm trying to clarify the requirements today for the resource series so that we can have it built in this sprint. Looking at the [example](http://www.alnap.org/what-we-do/innovation#case_studies/) you gave us - there are two types of lists of resources. One with the + sign and then the others at the bottom with the covers. Do you still need both? And if so, can you help me understand the difference between them? thanks

**Comment by Maria-alnap** [comment]
@angievanhegan we just need one of those lists, tbh. It's just that the old site  adds lists of resources at the end of the page and we thought it would be good to use the toggles to position the case studies higher up. These 2 listings are replications, really.

**Comment by angievanhegan** [comment]
@Maria-alnap so you just need to be able to add one list, which would be a combination of hand picked case studies and resources? Thanks

@cutlern fyi

**Comment by Maria-alnap** [comment]
@angievanhegan we need one list for resource series and another list for related resources, as per the wireframe. The 2 lists in the sample I sent both are to show one of our resource series, as requested.

**Comment by cutlern** [comment]
Hi @Maria-alnap ! Would you mind having a look at what’s been built so far and let me know if this is what you had in mind? (password is mrm /mrm)

http://alnap-dev.mrmdev.co.uk/about/what-we-do/innovation-in-humanitarian-action

At the moment resources are being displayed in two places on the page, in a ‘resource series nugget’ where you can select specific resources and is displayed in expanding boxes, and at the bottom of the page where resources are automatically displayed in a list of cards based on the resource series tag (like ‘Innovation’ for example).

**Comment by Maria-alnap** [comment]
@cutlern thanks for the link. What's the username?

**Comment by nadia847** [comment]
@Maria-alnap 

user: mrm
password: mrmdev

**Comment by Maria-alnap** [comment]
thanks @nadia847 @angievanhegan 
I'm a bit confused by this. The page you sent has nothing to do with the IA we signed off. Innovation is one of our topic pages. We won't have one under the about menu, we will only have a general research page there. 

Our request for a resource series was just to have a list of resources under a specific resource page, for when that resource is part of a series. The example I sent was about a resources series in our innovation work (the case studies in the page, which I clearly signposted). You were not meant to replicate this whole page on the new website.

Happy to discuss.
