### ISSUE TITLE
(#210) Build and theme events content type

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#144]
Links to #30 (build content type)
### Done criteria
- [ ] need to modify the 'register' text on the button (consult with client) (it may be to more info or to a registration link)
- [ ] Add checkbox to hide sidebar for event (for all events)
- [ ] Add checkbox to hide event details white box (for all events)
- [ ] Add subtopics nugget to event content type in the relevant region (style if needed), relabel nugget if needed on content type
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by nadia847** [comment]
Dupe

**Comment by russ-manta** [comment]
@cutlern is this one done now?

**Comment by cutlern** [comment]
@russ-manta yes
