### ISSUE TITLE
Decide how we are using user profiles

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#145]
- [ ] Decide how we're using user profiles
- [ ] Create issues in waffle as a result of this decision
- [ ] Make sure we have the appropriate work packages on the Roadmap
- [ ] Make sure we have an issue for using this design: https://invis.io/6GC6FJ72N

**Comment by nadia847** [comment]
@angievanhegan @russ-manta Is this kinda a duplicate of #45?
