### ISSUE TITLE
(#250) Build and theme person node (for ALNAP staff member?)

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#146]
### Done criteria
- [x]  use person content type
- [x] DISCUSSION: Copied from Invision comment. Maria asked:  Would it be possible to add a row(s) of cards with publications and blogs the Member of staff has authored under his bio?
- [x]  DISCUSSION: display their reports and resources, like blogs are on the author profile page
---
### Designs
[Person page](https://invis.io/6GC6FJ72N)

---
### ALNAP to check
[Team member](http://alnap-dev.mrmdev.co.uk/people/mr-arseni-melder)
- [x] Looks like design
- [x] Create new person page

**Comment by angievanhegan** [comment]
I'm moving this back to the backlog as it's not within the current sprint goals. It's ready for client review.

**Comment by angievanhegan** [comment]
@Maria-alnap I've added a done criteria to this one from the meeting on Friday. Please can you let me know if its' not right? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan  your criteria is right!

**Comment by nadia847** [comment]
Hi @Maria-alnap 

Just picking up a comment you left in Invision about staff profile pages just noticed a request in card #146 Build and theme person node (for ALNAP staff members) to display their blogs, publications and resources to appear on the Person's profile page.

This doesn't seem to be in the original scope of requirements and as such will be kind of tricky to automate at this stage.

You can however manually add box link references to staff publications and resources.

However adding blogs to this page (via box links) may make it look more like the blog author profiles which is something you didn't want so I would reconsider doing that.

**Comment by Maria-alnap** [comment]
@nadia847 Yes, this is something that we've discussed before and using box links will do. No need to set up anything further!

We've also started setting it up already and even have nice new fancy portraits! Check here: http://alnap-dev.mrmdev.co.uk/about/meet-our-team (I know, I hate my photo too but some will be retaken so I'll be the first in line!)
