### ISSUE TITLE
(#208) Build and theme user account page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#147]
### Done criteria
- [x] BLOCKED BY: Forms in #118 
- [x] Build views
- [x] Theme views, buttons and links etc
- [x] ISSUE: button position correct
- [x] ISSUE: create some Civi enabled webforms for editing
- [x] Theme profile edit forms
- [x] Make sure that there's no '+ Member news' button as members can't submit news  (yet)
- [x] ISSUE: Editing "email and password" page changes the name on your profile page to your email address
- [x] ISSUE: Editing "email and password" page changes the name on your blog author  
- [x] ISSUE: On saving Email password page am getting directed to user registration form
- [x] DISCUSSION: Blog author about text - who adds this and where? User or alnap? In Civi or drupal?
- [x] ISSUE: Adding an organisation in the webform doesn't chuck it into the civi field?
- [x] ISSUE: Need profile details eg ddress

---
### Designs
- [My account page](https://invis.io/D9CLJYJRW)
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@nadia847 have I correctly marked this as an extra? Thanks

**Comment by angievanhegan** [comment]
@cat-manta Do you think the design needs to change as we're losing the 'Member news' button? There's a chance it will come back later. Thanks

**Comment by cat-manta** [comment]
@angievanhegan Steve and I don't think it should change if there's a chance it could come back

**Comment by cutlern** [comment]
@russ-manta content upload buttons need positioning and and the moment they've just been styled and link back to the homepage until its been decided how the users can upload content that gets alnap's approval

**Comment by russ-manta** [comment]
@nadia847 can you take this over from Nelle or reassign if you need while I'm away. Buttons need positioning as per Nell's comment and then we need to create some Civi enabled webforms for editing the various sections of the profile which Dave can help you with.

**Comment by dave-manta** [comment]
@nadia847 couple of changes.
- [ ] If not social fields are provided, "find me on" should be hidden
- [ ] If an incorrect URL is put in, it looks to take the linkedin profile by default?
