### ISSUE TITLE
Confirm site search requirements

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#149]
- [ ] confirm search requirements/functionality
- [ ] Need a design for expanded search box (from main menu)
- [ ] Need a design for results

**Comment by russ-manta** [comment]
@dave-manta can you confirm what the search requirements are for the site and why we might need Apache SOLR. I can't remember/find if there are any notes on how search should work

**Comment by dave-manta** [comment]
@russ-manta is this for the main site search or the resources search, or are they one of the same.  There's been quite a lot of discussion on resources search and I believe you were part of those conversations. I don't have any specific notes on the search requirements, but if necessary we can meet and we can also re-confirm with ALNAP.

**Comment by russ-manta** [comment]
@Maria-alnap For the main site search can we confirm what functionality you need?
1. search with keyword box and filter by content type 
2. Search within pdfs/documents
3. Search recommendations

Are there more requirements than this?
Thanks
Russ

**Comment by angievanhegan** [comment]
@Maria-alnap Could you have a look at Russ's questions please? Thanks

**Comment by Maria-alnap** [comment]
Hi @russ-manta , what do you mean with Q3?

**Comment by russ-manta** [comment]
@Maria-alnap Q3 is showing recommended resources etc based on other searches

**Comment by Maria-alnap** [comment]
@russ-manta yep, these 3 would suffice for the main site search. Would the results here be listed by relevance?

**Comment by angievanhegan** [comment]
These notes have been copied to #127. This is pretty much a dupe.
