### ISSUE TITLE
(#213) Setup the taxonomy for tagging resources / events / news

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#15]
### Done criteria
- [x]  Resource type, category, tags and internal tags created
- [x] Events type taxonomy created
- [x] News taxonomy 
- [x]  Blogs taxonomy
- [x]  Jobs taxonomy

---
### Designs
- [x] N/a
### ALNAP to check
- [x] Resources have all relevant tags and internal tags available
- [x] Resource type and category are correct on resource content type
- [x] Event types are available when adding an event
- [x] News/Blogs/Jobs have relevant tags available
- [x] Evaluation reports added to tags/subtags
- [x] Ability to add/edit tags
- [x] Unable to add more tags if the prior tag has a slash in it eg. Refugees/IDPs solutions for this are either to rename the tag (remove the slash) or to add to any that have this tag with this tag as the last one
---

-----
#### Events labels (suggested by Maria in #75)
- Conference
- Panel discussion
- Lecture/ seminar
- Workshop
- Training course
- Other event (please specify)
- Online event (please specify)

#### Amends to taxonomy
- [x] move evaluation reports from a resource type to a tag
- [x] add the evaluation types as subtags.
- [x] The Crisis types in the resources backend should be subtags for Syria, which should be moved from an internal tag to an external one.
- [x] There's still a legacy field which we won't need: resource category (past, current, operational, analysis)
- [x] Unable to add more tags if the prior tag has a slash in it eg. Refugees/IDPs , see https://www.drupal.org/node/93854 for possible fixes

Then do #70 - Build related content view/s

**Comment by angievanhegan** [comment]
@ican-icant Who's the best person/people to do this? Ta

**Comment by dave-manta** [comment]
1. Text
2. Type (conference, launch, lecture, meeting, seminar, workshop, training course, webinar, other)
3. Tags (the resource keywords)
4. Organisation (agency)
5. Member vs non-meb

**Comment by angievanhegan** [comment]
@dave-manta I think the requirement for tagging events is just to use the resources taxonomy?

**Comment by dave-manta** [comment]
@angievanhegan I think Steve and I just need to go through and confirm exactly what we need. Probably solvable with 10 min conversation.

**Comment by angievanhegan** [comment]
@dave-manta Please can you make sure you clarify the requirements in the description field

**Comment by dave-manta** [comment]
@angievanhegan the title is confusing me. Is this for Resources?

**Comment by angievanhegan** [comment]
@dave-manta I'm not sure. I think it should cover the full extent of the taxonomy.  That'd seem most useful?

**Comment by dave-manta** [comment]
@angievanhegan OK. In which case my numbered list higher up is confusing as that's for Events I believe.

**Comment by angievanhegan** [comment]
@russ-manta Please can you help us out with this one? I've just copied the title over from the work package. Please can you clarify the requirements and the estimate so that this work can be allocated to someone? Thanks very much.

**Comment by russ-manta** [comment]
@angievanhegan I've added a checkbox for resources/events/news. Resources and events are now done and ready for review. I'm not sure about news though @dave-manta  do we have any info on what tags are needed for news?

**Comment by dave-manta** [comment]
@russ-manta please check with @ican-icant

**Comment by dilwarhussain** [comment]
Use the 'tags' taxonomy on: Resource, Events, News, Blogs, Jobs.

**Comment by russ-manta** [comment]
@Maria-alnap please can you confirm with Phil what the 'Evaluation - sub type' is for resources and where it is used?

**Comment by Maria-alnap** [comment]
@russ-Manta, I assume it is because evaluations are not tagged under the main tag list, but as a resource type (evaluation reports), hence they didn't want to meddle these subcategories with the rest of the tags. 

I don't think this makes sense at all and I'd tag all "evaluation reports" under a new "evaluations" tag with the subtypes as second tier tags to "evaluations".

I'm double checking with Phil. I'll keep you posted

**Comment by angievanhegan** [comment]
Maria responded to this while it was in the Done column. I'm putting it into the backlog with the 'review' tag in case there's something we need to pick up later.

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta So what I said earlier should be the way forward: move  evaluation reports from a resource type to a tag and add the evaluation types as subtags. 

The Crisis types in the resources backend should be subtags for Syria, which should be moved from an internal tag to an external one.

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan Not sure we reached agreement on the extent to which we could tweak Apache Solr that is within scope.  As mentioned, we would like to connect certain keywords in our taxonomy as synonyms to begin with. It would be good to know when you're planning to take this on, as I need to sort it out with our researchers... Thanks!

**Comment by russ-manta** [comment]
@Maria-alnap we'll be testing this next week. Solr has a synonyms file which we'll need to populate. Once we're happy it's working ok then we'll be ready for the list of synonyms so we should be able to give you the green light next week

**Comment by Maria-alnap** [comment]
@russ-manta thanks for that! Our head of research will be on leave until mid August so there's no rush with this. Happy to have the green light for then instead...

**Comment by angievanhegan** [comment]
@russ-manta I brought this into the sprint as an extra. Is that ok? Thanks

**Comment by russ-manta** [comment]
@Maria-alnap we've copied the Evaluation reports from resource type to tags - can we remove from resource type now?  What happens to items that previously had a resource type of Evaluation report (or one of the subtypes?) will you manually tag all items that previously has a resource type of evaluation report?  
Also can you give me an example of one of the Crisis subtypes in the resource back end?

**Comment by Maria-alnap** [comment]
@russ-manta Thanks! It might be worth keeping the resource type for those particular evals in the database, as we have no other way of ID what they are otherwise. How would you suggest that we re tag these? Could we do it once the site and bulk tagging are ready or should we tweak this in the database before import?

**Comment by russ-manta** [comment]
@Maria-alnap for the evals let's keep the tags in both places for now and then retag using bulk tagging before finally removing the old resource types once all the retagging has been done.

for Crisis to confirm we'll create a 'Syria crisis' parent tag within the tags taxonomy and then create the subtypes of 'Research, policy and analysis' , 'Learning and evaluation of similar crises' & 'Current learning and evaluation'  - is this correct? 
The internal tag for 'Syria crisis' and Crisis category can be removed once all these items have been retagged.

**Comment by Maria-alnap** [comment]
@russ-manta Great! Sounds like a plan!

**Comment by russ-manta** [comment]
@Maria-alnap great, the new tags have now been added

**Comment by angievanhegan** [comment]
@Maria-alnap It looks like this can be reviewed now and hopefully you can tick your checklist! Thanks

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan I've ticked all but the "edit tag" box as we haven't been explained how to do this yet.

Also, on the resources backend there's still a legacy field which we won't need: resource category (past, current, operational, analysis)

**Comment by angievanhegan** [comment]
@matty-manta Please can you explain to Maria how to edit these? Thank you.
@russ-manta There are two taxonomy amends (noted at the top). Thanks too.

**Comment by Maria-alnap** [comment]
@matty-manta @russ-manta where are we at with this? Not sure we've been explained what @angievanhegan says above

**Comment by russ-manta** [comment]
@Maria-alnap I went through this on one of the conf calls a while back. It's done using this url https://www.alnap.org/admin/content/resources  you search for the resources using this form, check the ones which are relevant and then from the operations drop down choose 'Modify entity values' . You then select the tags checkbox, add tags you want and then check 'Add new value(s) to Tags, instead of overwriting the existing values.' if you want to just add to exisiting tags.  I can run throught this again if you need but it's pretty straightforward

**Comment by Maria-alnap** [comment]
@russ-manta great! I'll close this one then
