### ISSUE TITLE
(#209) Wireframes/scoping  member updates views

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#153]
See notes in #82 

### Requirements
1. ALNAP create them
2. They are only viewable by logged in members (users)
3. You want to tag them for member(s) or ALNAP
4. They get displayed on the [user account page](https://invis.io/72BDLFJYG#/240257350_My_Account_V0-1) (if you are a member) 
---

### Done criteria
- [ ] Scope done
- [ ] Wireframe done?
- [ ] Update #154 with requirements
- [ ] Do we need a search page or other view for member updates other than that on the my account page?
---

**Comment by dave-manta** [comment]
@Maria-alnap just confirming the requirements for member updates which ALNAP adds to the site....

1. They are only viewable by logged in members (users)
2. You want to tag them for member(s)
3. They get displayed on the user account page (if you are a member) https://invis.io/72BDLFJYG#/240257350_My_Account_V0-1

[@angievanhegan @russ-manta - tagging you guys in]

**Comment by Maria-alnap** [comment]
@dave-manta @angievanhegan @russ-manta Those 3 points are exactly what we need from Member updates. 

Only thing to add is that we will also be using them to provide updates from the Secretariat (us) to the Membership so we need to be able to ID these accordingly (e.g. by tagging ourselves as well or have no tags for these).

**Comment by dave-manta** [comment]
@Maria-alnap Perfect!  @nadia847 all good?

**Comment by nadia847** [comment]
@dave-manta yes. Thanks, @Maria-alnap!

**Comment by angievanhegan** [comment]
@dave-manta Are you working on this issue (working your way through the done criteria?) If you are, I'll assign it to you and put it in the 'In Progress' column. Thanks

**Comment by dave-manta** [comment]
@angievanhegan no, not me. I was the only one around for Nadia to ask this morning ;-)

**Comment by russ-manta** [comment]
@dave-manta for member updates do we just need a view of them on the my account age with load more?  Is there no search or anything required anywhere?

**Comment by dave-manta** [comment]
@russ-manta that's right and I believe @ican-icant has confirmed this verbally with @nadia847.
