### ISSUE TITLE
(#209) Build and theme member updates views

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#154]
### Done criteria
- [x] ISSUE: Member update show the name of the organisation on card
- [x] See design, needs to list Organisation
- [x] Build views according to wireframes/design
- [x] Theme according to match design
- [x] Check if search or other view of member updates is required (it's not - according to @ican-icant )
---
### Designs
- [ ] https://projects.invisionapp.com/d/main#/console/10292473/240257350/preview

---
### ALNAP to check
- [x] Displays correct information on profile for each member update
- [ ] Member updates display matches design and can click through to individual member update

**Comment by russ-manta** [comment]
@nadia847 shouldn't the member update show the name of the organisation on the card? http://alnap-dev.mrmdev.co.uk/user  - not just 'Member'?

**Comment by nadia847** [comment]
@russ-manta yeah I had field_member instead of field_members in the template *facepalm*

I've now set it so that if you have the members field set it will show otherwise you'll see ALNAP/Contributor.

**Comment by angievanhegan** [comment]
@Maria-alnap Ready for you to review again.

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta this looks OK to me but couldn't find in the backend how to tag organisations in the update. We haven't received training on this bit yet, to be fair, @matty-manta, so apologies if it is obvious!

**Comment by matty-manta** [comment]
Hey @Maria-alnap If you take a look in the Details tab, you should be able to see a section called "Members" - I've highlighted the text here:

https://i.imgur.com/CUdQ2dV.png

Just type out the name of the organisation you wish to relate to this member update.

Hope that's all clear, just let me know otherwise :)

Thanks, 
Matty

**Comment by matty-manta** [comment]
Hey @Maria-alnap That's right - as we've done an import of the organisations into the CMS it associates the Update with the Organisation. And yes - you should have the option to associate an Organisation any time you add a new update. What happens going forward when someone registers a new Organisation is something we need a discussion amongst us at Manta Ray. Make sense for now?

**Comment by Maria-alnap** [comment]
@matty-manta thanks! All clear. I'll move this to done then :)

**Comment by matty-manta** [comment]
Thanks @Maria-alnap :)
