### ISSUE TITLE
(#202) Wireframe/scope blog author profile

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#156]
### Done criteria
- [x] Requirements approved by ALNAP, confirm fields & design
- [x] Confirm with client that author page will be user page
- [ ] Requirements all documented in issue #189

**Comment by angievanhegan** [comment]
@ican-icant If you have time to make a start on this it'd be great as build will be able to start on it. It's in the sprint this week. Thanks.

**Comment by ican-icant** [comment]
@angievanhegan This is done and in invision for review by @Maria-alnap https://projects.invisionapp.com/d/main#/console/10292473/239620640/preview

**Comment by Maria-alnap** [comment]
@ican-icant Thanks! Will this be connected to the account these people will have on the website or will it be something just for blog authors completely separate to their account? 

As we may have said before, we would prefer if it was something separate just for bloggers, as people have abused the fact that they have a profile on our website and say in their CV that they work for ALNAP, which is an utter lie!

Having this profile page also opens a can of worms as well: will this mean that authors in the HELP Library may also have a profile page? If so, I think we would have to park that here for now, as it has other implications.

**Comment by angievanhegan** [comment]
I'm putting this in blocked as I think this is something we need to resolve. I'll call in Russ and  Steve to discuss

**Comment by angievanhegan** [comment]
Angie to clarify the answer to Maria's questions

**Comment by angievanhegan** [comment]
Hi @Maria-alnap Russ has confirmed that the blog author page will be the person's user page. As per the design, it should show them as an employee of their organisation (which might make it a bit harder for them to say they work for ALNAP). Is that ok? 

Also, is there a link on the [resource page](https://invis.io/ANC0GIX8Q) to the author? It looks to me like there's only a link to the organisation page. Is that right? Thanks

**Comment by angievanhegan** [comment]
FROM SLACK

RUSS: we're in the process of setting up fields for people to enter their social information eg. twitter / linkedin etc.  This will display on blog author profiles ie https://projects.invisionapp.com/d/main#/console/10292473/240257402/preview   Do you have any preference for which fields we should add?  For now we're thinking of these 4: Linkedin , Facebook, Twitter, Researchgate but please let me know if you want a change to this.

TIM: The four you listed sound good to me, but Maria might have additional ones.  we'll go with those for now then but can change them around if need  be. 

----
@Maria-alnap Would you like to add anything? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan I think those would do

**Comment by angievanhegan** [comment]
Hi @Maria-alnap Russ has confirmed that the blog author page will be the person's user page. As per the design, it should show them as an employee of their organisation (which might make it a bit harder for them to say they work for ALNAP). Is that ok?

Also, is there a link on the resource page to the author? It looks to me like there's only a link to the organisation page. Is that right? Thanks

**Comment by Maria-alnap** [comment]
Hi Angie, yes that's right. Only a link to organisation in each resource, not to the author

**Comment by angievanhegan** [comment]
@russ-manta @dilwarhussain Maria confirmed that using the blog author page being the person's public user page is fine.
