### ISSUE TITLE
Wireframe user account page(s)

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#159]
- [ ] Create wireframe similar to current alnap account page for new site: http://www.alnap.org/account/

**Comment by russ-manta** [comment]
@ican-icant could you have a look at a wireframe for this please?

**Comment by ican-icant** [comment]
Does this really need a wireframe? I'd go with FMLM-style

**Comment by ican-icant** [comment]
![login-ALNAP.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593563879553c0002057e2c0/125516c66e82c728ace21e0d46e49b9d2a8cce88a3c79e73e611b2843b492d762a10e17132d0ba7bee112c575a5d1bad450e0c44fcfbda7df0e46f76d94e17ff933c0120996048e6edc00db513b922814e81bfb48a4ac1ea352ce48a8b5d73.jpg)

**Comment by russ-manta** [comment]
@ican-icant this is for the user account page once logged in which should show their photo, blogs if other people are looking at it, bookmarked resources etc. Have you looked at their current page when logged in? http://www.alnap.org/account/

**Comment by ican-icant** [comment]
A page was done a while ago,[https://projects.invisionapp.com/d/main#/console/10292473/238113517/preview] but this was to be discussed more widely as it was felt there might be a need for a home for members.

**Comment by ican-icant** [comment]
This wireframe probably needs to be revised in light of blog author page as it should be similar - does it need a design? @russ-manta

**Comment by cat-manta** [comment]
@Maria-alnap Have designed this page, link below:
https://invis.io/5TCA7FXBR#/240257350_My_Account_V0-1

**Comment by Maria-alnap** [comment]
Thanks @cat-manta ! I've added some comments :)

**Comment by angievanhegan** [comment]
@Maria-alnap Would it be ok to add your comments here please? Thank you.

**Comment by ican-icant** [comment]
@angievanhegan here's the list of items under the Account management titles:
> Personal 
>> Password / Email
>> Update my photo
> Professional
>> Bio
>> Job title
>> Organisation
> Preferences
>> Email subscriptions
>> Areas of interest
