### ISSUE TITLE
(#210) Build & theme PAST events view with search

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#163]
Same as main events search #75 but for past events only

### Done criteria)
- [x] Should search by:
  - [x] Text
  - [x] Type (Conference, Panel discussion, Lecture/ seminar, Workshop, Training course
  - [x] Other event (please specify), Online event (please specify)). ALNAP to be able to edit list. 
  - [x] Organisation (agency)
  - [x] Location
  - [x] Tags (the resource keywords)

- [x] Ability to promote ALNAP events above others

- [x] Sort by
  - [x] Date
  - [x] Title
  - [x] Popularity
  - [x] ALNAP events
  - [x] Contributor events

- [x] Add event / sign up/ upcoming events buttons

- [x] Theme filters
- [x] View toggle list/gallery
- [x] Theme date grouping
- [x] Load more
- [x] Match heights

**Note: No need to search by member/non member events.**

---
### Designs
- [Events wide](https://invis.io/VPC8MGQ6E)
- [Events wide search](https://invis.io/U6C8MHW2E)
---
### ALNAP to check
http://alnap-dev.mrmdev.co.uk/events/past-events
- [x] Page looks like the design on desktop
- [x] Page works on mobile
- [x] Filtering and search works

------

**Comment by Maria-alnap** [comment]
@nadia847 I've checked and the only one I haven't ticked is that last one as I tried to filter by location, for example, and that didn't work...

**Comment by russ-manta** [comment]
@cutlern can you take a look at this one in relation to Maria's last comment please?

**Comment by russ-manta** [comment]
@cutlern can you re-order the location to the end on past events please?

**Comment by Maria-alnap** [comment]
All good. I'll move to done
