### ISSUE TITLE
(#234) Build and theme user log in page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#166]
### Done criteria
- [x] Build login page according to sketch
- [x] Install login as email address module
- [x] Redirect to relevant page after login
- [x] Theme login page according to design
- [x] Link button in header to login page

---
### ALNAP to check
- [x] Test forgotten password process
- [x] Test log in process

**Comment by cat-manta** [comment]
@angievanhegan @russ-manta Can you have a look at the design please?
https://projects.invisionapp.com/d/main#/console/10292473/247392339/preview

**Comment by angievanhegan** [comment]
@ican-icant Is this ok for you? Thanks

**Comment by Maria-alnap** [comment]
@dave-manta  Not sure what I should be looking at here...

**Comment by Maria-alnap** [comment]
Gone through sign up process and updated wording where required. Will move to done
