### ISSUE TITLE
(#200) Homepage News/Resource/Blog view

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#169]
### Done criteria
- [x] Build
- [x] Theme
- [x] Mobile version
- [x] BLOCKER: Equal heights issue
- [x] Fix wider gap between latest resources and events 
- [x] ISSUE: make the transition when loading more items sexy
- [x] BLOCKER: Load more button
----
### Homepage designs:
- [Homepage wide](https://invis.io/NSCBN3KQ5)
- [Homepage wide nav](https://invis.io/6KCBN4KYE)
- [Mobile version](https://invis.io/9XCBN2XZ4)
- [Mobile nav](https://invis.io/5MCBMRUDQ)
---
### ALNAP to check
- [ ] Resource/blog/news section (mobile and desktop)
- [ ] Events section (mobile and desktop)
- [ ] more button for both sections (mobile and desktop)

**Comment by nadia847** [comment]
@russ-manta @ican-icant how do we want to allow them to choose which items go in here? Sticky? A Nodequeue?

**Comment by ican-icant** [comment]
@nadia847 Not sure if this is finished, but the MORE button doesn't work (you know this) but also we're not meant to display summary text on any card - just the title.

**Comment by ican-icant** [comment]
@nadia847 the gap between the bottom box in the hero and the strap line is bigger on the site than the design. It needs to be the same as the gap below the strap, which looks spot on

**Comment by angievanhegan** [comment]
@russ-manta Who can work on these if Arseni is off?

**Comment by russ-manta** [comment]
@pipemanta can you check the comment from Steve please 'the gap between the bottom box in the hero and the strap line is bigger on the site than the design. It needs to be the same as the gap below the strap, which looks spot on'

**Comment by nadia847** [comment]
@russ-manta @pipemanta I already fixed that as I got the feedback while I was still working on it

**Comment by nadia847** [comment]
@what's still outstanding is sorting out the match heights which isn't working properly

**Comment by angievanhegan** [comment]
@nadia847 Am I right to assign this one to you?

**Comment by nadia847** [comment]
@angievanhegan  well I hit a brick wall with it. Arseni was helping me but as he's off, not much more  I can do other than assigning it to Russ to look at in Seni's absence

**Comment by angievanhegan** [comment]
@ican-icant Can you just check this is ok for Maria to sign off? There's no mention on the card. Thanks

**Comment by ican-icant** [comment]
@meldera - please make the transition when loading more items sexy - it doesn't look good currently. Use some of that JS you love so much.

**Comment by angievanhegan** [comment]
@russ-manta I'm moving this back to the sprint backlog

**Comment by Maria-alnap** [comment]
@nadia847 not sure whether this is ready for me to check yet?
