### ISSUE TITLE
(#200) Homepage top band build and theme

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#170]
### Done criteria
- [x] Promoted items view
- [x] Help library search
- [x] Mobile version
- [x] Themed
- [x] When I click on the search bar on the H-library the search bar partially covers the GO button.
- [x] When the page resizes on mobile the padding at the bottom of the white cards disappears and the text sits on the bottom line of the box
- [x] search is broken
----
#### Homepage designs:
- [Homepage wide](https://invis.io/NSCBN3KQ5)
- [Homepage wide nav](https://invis.io/6KCBN4KYE)
- [Mobile version](https://invis.io/9XCBN2XZ4)
- [Mobile nav](https://invis.io/5MCBMRUDQ)
---
### ALNAP to check
[Home page](http://alnap-dev.mrmdev.co.uk/)
- [x] 3 promoted items (mobile and desktop)
- [x] Help library search (mobile and desktop)

**Comment by angievanhegan** [comment]
@russ-manta Who can work on these if Arseni is off?

**Comment by russ-manta** [comment]
@nadia847 is there anything left to do here or can I just move to review/done?

**Comment by nadia847** [comment]
@russ-manta I'm working on the matched heights now and then I'll chuck it into for review

**Comment by ican-icant** [comment]
@nadia847 A few issues:
> When I click on the search bar on the H-library the search bar partially covers the GO button.
> When the page resizes on mobile the padding at the bottom of the white cards disappears and the text sits on the bottom line of the box
> search is broken

**Comment by nadia847** [comment]
@ican-icant 

Go button addressed
Padding fixed
Search works and now shows the search query in the keyword field

**Comment by angievanhegan** [comment]
Ready for you to review @ican-icant

**Comment by angievanhegan** [comment]
@ican-icant Please can you check this? Just go through the Done criteria at the top and tick them off if they are done. THANK YOU!

**Comment by ican-icant** [comment]
@angievanhegan ticked all the done criteria

**Comment by angievanhegan** [comment]
@Maria-alnap Another one ready for you to check. Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan all of this looks and works OK!
