### ISSUE TITLE
(#201) Theme resources search/landing page (HELP page)

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#171]
### Dependencies
- [x] Build resources landing page #59
----
### Done criteria
- [x] BLOCKER: Filter JS problem (need to keep filter box open after search and prevent chosen styles being removed)
- [x] Page looks like design on wide screen
- [x] Page looks like design on mobile
- [x] Views and filters themed
- [x] Toggle to switch between list/card displays themed
- [x] Playable content (film/audio) should have a play icon over the image.
- [x] ISSUE - Advanced search filters are too wide on advanced search
- [x] ISSUE - Resource cards are also not centred on the iphone 6 screen.
- [x] ISSUE - Also just noticed the country filter box isn't quite the right shape - one of the end is square rather than curved.
- [x] ISSUE -  Advanced search filters not wide enough on narrow screen (see attached)
![Screen Shot 2017-08-21 at 13.18.34.png](https://images.zenhubusercontent.com/5970b09e61b4ca3b0a751dc3/20c6f343-de04-4828-95f5-1cab1b5a80c4)
---
### Designs
- <a href="https://invis.io/7GC3GQIWQ"> HELP page</a>
- <a href="https://invis.io/2CC3EN2NH"> HELP advanced search</a>
- <a href="https://invis.io/U7CBNIKA4"> HELP quick search mobile</a>
- <a href="https://invis.io/T7CBNJ7CQ">Help advanced search mobile</a>
---
### ALNAP to check
[Help library](http://alnap-dev.mrmdev.co.uk/help-library)
- [x] Page looks like design on wide screen
- [x] Page looks like design on mobile

**Comment by russ-manta** [comment]
@dilwarhussain @angievanhegan  I'm moving this to blocked as we're going to rebuild the search page based on conversations with Maria on Friday

**Comment by angievanhegan** [comment]
@dilwarhussain @russ-manta I moved this back into the sprint backlog as it's just about issue order rather than a problem that we need to focus on sorting to enable people to get on with work.

**Comment by russ-manta** [comment]
@cutlern the search page has been rebuilt by Arseni. You need to add some dummy content in for the portals section which should already then be styled and then it's the top part of the page ie filters etc that needs styling

**Comment by russ-manta** [comment]
@meldera need to keep filter box open after search and prevent chosen styles being removed

**Comment by angievanhegan** [comment]
@meldera Is this in the right column, or is it ready for @russ-manta  to review?

**Comment by angievanhegan** [comment]
@russ-manta Needs assigning

**Comment by russ-manta** [comment]
@cutlern   can you check that this looks ok on mobile, seems the card content may not be wide enough..

**Comment by cutlern** [comment]
@russ-manta mobile styling needs checking, cat's asked me to ask nadia's approval on the video icon colour but that part's done

**Comment by russ-manta** [comment]
@ican-icant can you take a look at this please

**Comment by ican-icant** [comment]
@russ-manta @cutlern Advanced search filters are too wide on advanced search - I have a screen shot for the person that needs to see it. Can't upload the pic here.

Resource cards are also not centred on the iphone 6 screen.

**Comment by russ-manta** [comment]
@dilwarhussain can you resolve these issues please?

**Comment by ican-icant** [comment]
@dilwarhussain also just noticed the country filter box isn't quite the right shape - one of the end is square rather than curved.

**Comment by Maria-alnap** [comment]
@nadia847 The link above http://alnap-dev.mrmdev.co.uk/help-library-new is broken. I assume I should be looking at the HELP page currently linked on the site?

**Comment by nadia847** [comment]
@Maria-alnap yup sorry. link updated

**Comment by nadia847** [comment]
@Maria-alnap this is more about looks than function at the moment. functionality is in a separate card.

**Comment by Maria-alnap** [comment]
Haha! No worries, I was a  bit confused (and tired). All OK with this. I'll move to done now :)
