### ISSUE TITLE
(#201) Theme resource node

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#172]
### Done criteria
- [x] Resource to match design
---
### Designs
- <a href="https://invis.io/ANC0GIX8Q">Resources wide</a>
- <a href="https://invis.io/ZTCBNO4N6">Resources mobile</a>
---
### ALNAP to check
[Resources example](http://alnap-dev.mrmdev.co.uk/test-innovation-resource)
- [x]  individual resource page matches design
- [x] correct information displayed on individual resource page

**Comment by angievanhegan** [comment]
@russ-manta Please can you add some 'ALNAP to check' criteria? Thanks

**Comment by angievanhegan** [comment]
@russ-manta Can this be assigned to @Maria-alnap  now to check?

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta I haven't ticked the first box as there is a line currently showing up under the date which is messing up the layout of the resource info box.

**Comment by angievanhegan** [comment]
@russ-manta Please can you have a look and reassign? thanks

**Comment by dilwarhussain** [comment]
@Maria-alnap I've fixed the issue with the line under the date if you could take a look please.

**Comment by Maria-alnap** [comment]
@dilwarhussain thanks! Just checked and it looks OK now :)
