### ISSUE TITLE
(#204) Standard page (About us)

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#173]
### Done criteria
- [x] Create About page using nuggets (see design)
- [x] Theme standard page and nuggets

---

### Design
[About page](https://invis.io/BFCAVB9ZD)

---
### ALNAP to check
[About page](http://alnap-dev.mrmdev.co.uk/about)
- [x] Lead image and text looks like design
- [x] Sub sections look like design
- [x] Can create new page with lead image and text, subsections

---

**Comment by angievanhegan** [comment]
@angievanhegan I've fixed the white background of the expanding content block, was there anything else for this card? :)

**Comment by angievanhegan** [comment]
@cutlern your comment was on the sprint goal issue (which is supposed to just be a parent issue) does your comment relate to this issue?

**Comment by cutlern** [comment]
@angievanhegan Ah yeah sorry that comment was for this issue (173), thought that was a card for working on the about page

**Comment by angievanhegan** [comment]
@cutlern There's nothing else I know about. This is probably a good example of where we might need to make sure there are more specific tick boxes in the requirements at the top.

**Comment by angievanhegan** [comment]
@russ-manta Please can you write some criteria for ALNAP to check. I had a go but mine are clearly rubbish. Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan not sure if the ones I'm ticking above are yours or @russ-manta criteria, haha. I have ticked the first 2, and will wait for confirmation to proceed with the rest!

**Comment by angievanhegan** [comment]
@Maria-alnap The first two should have been ticked already!  The final test (I've moved the last one to another task) is just to check that you can create a new page and add these things for yourself.

**Comment by Maria-alnap** [comment]
@angievanhegan Ah yes! Tim and I have a couple of creations already: http://alnap-dev.mrmdev.co.uk/marias-test

**Comment by angievanhegan** [comment]
@Maria-alnap YEAHHH!! It's making me grin!  :smile: I'll move this to done.
