### ISSUE TITLE
Font colon issue

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#182]
AT font-weight:500, colons look like a single dot, see http://alnap-dev.mrmdev.co.uk/miss-eleanor-cutler

**Comment by angievanhegan** [comment]
@nadia847 Please can you add an estimate to this one. Thanks

**Comment by angievanhegan** [comment]
@nadia847 hello. Can I mark this one as an extra, or do you think this font issue appears on the home/resources/about? Thanks

**Comment by meldera** [comment]
@nadia847 I've added some JS to wrap each colon into a <span class="colon"></span> so you could set it to 400

**Comment by angievanhegan** [comment]
@nadia847 I've put this into the 'done this sprint' column so we can still count the points and we can start to learn how many points we can do.
