### ISSUE TITLE
(#217) Add favicon

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#183]
### Done criteria
- [x] Alnap icon displays when viewing site on browser tabs
- [x] Icon displays for bookmarks on desktop
- [x] Icon displays when saving site on home screen on mobile
- [x]  BLOCKER - Apple home screen iOS icon not working
---
### Designs
- [ ] Files/PROJECTS/526 - ALNAP website and CRM/Design/Assets/favicons <link rel=“apple-touch-icon” sizes=“180x180" href=“/apple-touch-icon.png”>
<link rel=“icon” type=“image/png” sizes=“32x32" href=“/favicon-32x32.png”>
<link rel=“icon” type=“image/png” sizes=“16x16" href=“/favicon-16x16.png”>
<link rel=“manifest” href=“/manifest.json”>
<link rel=“mask-icon” href=“/safari-pinned-tab.svg” color=“#ff8838 ">
<meta name=“theme-color” content=“#ff8838 ">

---
### ALNAP to check
- [ ] Desktop
- [ ] Mobile
- [ ] ?

**Comment by angievanhegan** [comment]
@nadia847 Can I take this out of the sprint if it's blocked? There's still plenty of other stuff to do!

**Comment by nadia847** [comment]
@angievanhegan yeah sure fine :o)
