### ISSUE TITLE
(#202) Build + theme CTA for submitting a blog

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#188]
### Dependencies 
- [x] Blog landing page built  and themed #39
- [x] Design/wireframe blog CTA #205
---
### Done criteria 
- [x] 'Got an idea for a blog' button appears at the top of landing page (as per design)
- [x] Button is a mailto link to comms@alnap.org
- [x] Button text and email address editable by ALNAP
- [x] Buttons appearing in the right place (currently overlaying header) 
---
### Designs
- [Blog landing](https://invis.io/7CC18FLJ4)
---
### ALNAP to check
- [x] Button text correct
- [x] Mailto link works correctly
- [x] Text and email address can be changed
- [x] Buttons appear in the the position

**Comment by angievanhegan** [comment]
@ican-icant confirmed that there's no design needed just the 'got an idea for a blog' button at the top of the landing page. This will be a mailto link.

**Comment by angievanhegan** [comment]
@russ-manta Should ALNAP be able to edit the button text and the link? If so, can we add this to the done criteria?

@Maria-alnap Please can you give us the email address for this button? Thanks

**Comment by Maria-alnap** [comment]
hi @angievanhegan , the email address to be used is comms@alnap.org

**Comment by russ-manta** [comment]
@angievanhegan we have now edited it the button with the requirements but ALNAP can edit in the future if they need to

**Comment by angievanhegan** [comment]
@russ-manta Do you need to review this, or can it just go into the ALNAP review column with the criteria I made up for them? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan the buttons are showing up but the positioning is not right. They're showing up above the main menu?

**Comment by angievanhegan** [comment]
@matty-manta would you be able to show @Maria-alnap how to edit the button text and the mailto address?

@russ-manta This needs to be assigned to a dev to look at the button position issue (I've added a new checklist item in the done criteria). Thanks

**Comment by russ-manta** [comment]
@dilwarhussain can you look at this please?  The buttons appear above the nav when logged out: http://alnap-dev.mrmdev.co.uk/blogs but should be by the search as they appear when logged in

**Comment by matty-manta** [comment]
@russ-manta The buttons are also in the wrong position when logged in as web editor.

@Maria-alnap if you edit the blogs landing page, there's a nugget within the Additional content tab called "Links". Within there you'll be able to control the destination for the three buttons:

- Idea for a blog?
- Download out guidelines
- Sign up for updates

You may notice that these links have the "Button capsule" style applied to them in the dropdown that my cursor is hovering over here:

https://i.imgur.com/tdNnFpj.png

To change any of these links, you just need to pop your cursor within any of the links, and then click on the link icon in the WYSIWYG:

https://i.imgur.com/RjNn31r.png

When you click on that, you'll get the link window pop up as normal, when you can change email address, etc.

https://i.imgur.com/ArfklBc.png

Any trouble with that just let me know.

Matty

**Comment by dilwarhussain** [comment]
Fixed @russ-manta

**Comment by Maria-alnap** [comment]
@matty-manta just checked the button editing. All clear, thanks!

**Comment by matty-manta** [comment]
@Maria-alnap  Pleasure :)
