### ISSUE TITLE
(#202) Build and theme blog author profile

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#189]
### Dependencies
- [x] Scoping/wireframing #156
- [x] Linked to User config #40
---
### Done criteria
- [x] Social media: Linkedin , Facebook, Twitter, Researchgate
- [x] View of blog posts contributed by the author
- [x] add additional fields/views to profile
- [x] Theme profile page
- [x] Blog author profiles need hiding? See #156 Maria to confirm
---
### Designs
- [Blog landing](https://invis.io/7CC18FLJ4)
- [Blog](https://invis.io/NJC8OGC2B)
- [Blog author](https://invis.io/SBCGDY838)
---
### ALNAP to check
[Blog author page](http://alnap-dev.mrmdev.co.uk/users/angie-vanhegan)
- [x]  Check social icons are displaying and work
- [x] Check title, image,bio all work as expected
- [x] Check latest blogs view looks correct
- [x] Check page matches design

**Comment by russ-manta** [comment]
@dilwarhussain could you take another look at this? The social icons only seem to show on hover and the twitter link seems to have some html tags as part of the link

**Comment by angievanhegan** [comment]
@russ-manta ready for you to check

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta Just went ahead of myself and looked at this :S I won't tick anything until you tell me to do so BUT, I have a comment: Social media icon links would need to be set up as blank/opening in new window. Thanks!

**Comment by Maria-alnap** [comment]
This looks OK to me. Only have one questions, @russ-manta @angievanhegan : will we be able to customise which social media buttons show up? I'm sure there will be a quite a few people with none of them!

**Comment by russ-manta** [comment]
@Maria-alnap the buttons only show if you fill out the field with their social profile info so no info = no buttons show

**Comment by Maria-alnap** [comment]
@russ-manta That's what I thought! haha. Thanks!
