### ISSUE TITLE
(#240) Wireframe add a job page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#19]
### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@ican-icant Does this need a wireframe? Or can we move it to signed off on the page status board? and move this to done?

**Comment by dave-manta** [comment]
I don't think it needs a wireframe

**Comment by angievanhegan** [comment]
@ican-icant If you agree with Dave, can you move it over to done? Thanks

**Comment by angievanhegan** [comment]
This doesn't need looking at until it's in the sprint

**Comment by angievanhegan** [comment]
Dupe of #244
