### ISSUE TITLE
(#203) Theme individual topic page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#191]
### Dependencies
- [x] Topic page built #190
---
### Done criteria
- [x] Ability to re-order the Nuggets used for Jump topics
- [x] Jump topic nuggets have an optional image
- [x] Jump to menu will wrap onto another line
- [x] Twitter hashtag functionality like IDDG
- [x] Views more links to show 4 items and more to reveal another 4
- [x] White box text with +more button should align to the RHS of the image
 - [x] Sub topic description colour depending on palette selected 
- [x] Expandable boxes on mobile styling
- [x] featured boxes aren't displaying when logged in as editor (they do when you're logged in as admin)
---
### Designs
- [Landing page](https://invis.io/K5CGE4K9M)
- [Our topic](https://invis.io/WTCJKJ4PA) and [another topic](https://invis.io/42CJKJH5B) 
---
### ALNAP to check 
[Individual topic page](http://alnap-dev.mrmdev.co.uk/our-topics/evaluation)
- [x] Looks like the above designs
- [x] It's possible to create and edit a new topic page

**Comment by angievanhegan** [comment]
@cutlern Should this be 'in progress' if there's still a couple of done criteria to do? 
@nadia847 Are you still working on this too?

**Comment by nadia847** [comment]
@i was reviewing it, @cutlern was fixing it. It's now ready for Alnap review so I've moved it along.Reassigning to you and russ to figure out the Alnap done criteria.

**Comment by angievanhegan** [comment]
@Maria-alnap This is ready for you to sign off. Please @matty-manta here if there's anything you'd like more training/support with. 

If you find any issues, do you feel comfortable to add them as done criteria to the top of this issue?

**Comment by Maria-alnap** [comment]
hi @angievanhegan This looks OK but I haven't ticked last box as the "featured content" I added under "main content" is not showing up:

http://alnap-dev.mrmdev.co.uk/our-topics/test-topic

**Comment by angievanhegan** [comment]
@matty-manta Please can you have a quick look at this to see if Maria might have missed something? Thanks

**Comment by matty-manta** [comment]
@angievanhegan Maria hasn't missed anything - it's a permissions issue, featured boxes aren't displaying when logged in as editor. They are displaying when you're logged in as admin.

**Comment by angievanhegan** [comment]
@matty-manta Thank you for checking :+1: I'll add another done criteria. @russ-manta Can you reassign please? Thanks

**Comment by russ-manta** [comment]
@cutlern can you check this. As far as I can tell it's working ok when logged in as editor but can you verify please?

**Comment by cutlern** [comment]
It works for me when I log in as editor :)

**Comment by angievanhegan** [comment]
@Maria-alnap Do you mind taking another look please? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan this is now showing up, great! I'll move to done :)
