### ISSUE TITLE
(#203) Theme our topics landing page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#192]
### Dependencies
- [x] Our topics landing page built #105
---
### Done criteria
- [x] Theme research topic card content
---
### Issues
- [x] odd behaviour of expanding box - it flashes when closing and doesn't expand as I'd expect
- [x] Delete read time
---
### Designs
- [Landing page](https://invis.io/K5CGE4K9M)
- [Our topic](https://invis.io/WTCJKJ4PA) and [another topic](https://invis.io/42CJKJH5B) 
---
### ALNAP to check 
[Our topics landing page](http://alnap-dev.mrmdev.co.uk/our-topics)
- [x] Page matches design
- [x] Correct fields/content is displayed

**Comment by russ-manta** [comment]
@ican-icant can you review this one please? http://alnap-dev.mrmdev.co.uk/our-topics

**Comment by ican-icant** [comment]
@russ-manta review this page and added a few issues

**Comment by Maria-alnap** [comment]
This looks OK to me :)

**Comment by ican-icant** [comment]
@meldera can you work you magic on the opening / easing of the expandy box. It's not mission critical, but would be nice.

**Comment by angievanhegan** [comment]
@ican-icant just to keep things clear, I created a new issue for this tweak #223. This issue is DONE and won't be looked at! :o)
