### ISSUE TITLE
(#209) Build and theme news landing page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#193]
### Done criteria
- [x] BLOCKER: Sort issues with 'load more' pager
- [x] BLOCKER: keeping the search box open after searching [example](http://alnap-dev.mrmdev.co.uk/news)
- [x]  ISSUE: Filters auto submitting
- [x] Build search filters, Toggle, more page etc
- [x] Create Sign up for updates button
- [x] Theme page to match design
- [x] ISSUE - Filters are currently NOT auto-submitting (the text search at the top should NOT).
- [x] ISSUE - Please check space between news main title and content is right - it looks big
- [x] ISSUE - The right hand side of the filter boxes are square and the down arrows in blue cu=irlces don't sit nicely inside.

- [x] DISCUSSION: Do we need to display organisation on the cards?

---
### Designs
- [ ] https://projects.invisionapp.com/d/main#/console/10292473/232387377/preview
---
### ALNAP to check
[News landing page](http://alnap-dev.mrmdev.co.uk/news)
- [x] Page matches design
- [x] Functionality matches design &wireframes

**Comment by russ-manta** [comment]
@meldera could you take a look at the load more pager and keeping the search box open after searching for this one please? http://alnap-dev.mrmdev.co.uk/news

**Comment by angievanhegan** [comment]
@cutlern to add more details about the problem with the load more pager.

**Comment by angievanhegan** [comment]
@russ-manta It looks like this is ready for review.

**Comment by russ-manta** [comment]
@ican-icant could you review this one please?

**Comment by ican-icant** [comment]
@russ-manta  @nadia847 @angievanhegan Issues:
> filters are currently NOT auto-submitting (the text search at the top should NOT).
> Please check space between news main title and content is right - it looks big
> The right hand side of the filter boxes are square and the down arrows in blue cu=irlces don't sit nicely inside.
> load more still doesn't work right

**Comment by dilwarhussain** [comment]
@ican-icant All the issues stated above should be resolved now. The load more button is being looked at separately on issue #169 which will effect load more buttons sitewide.

**Comment by Maria-alnap** [comment]
@nadia847 is this ready for me to check?

**Comment by Maria-alnap** [comment]
@nadia847 This looks good. Only thing I think we should check is whether we had agreed to also spit the organisation in the card for these...

**Comment by nadia847** [comment]
@Maria-alnap they're not in the design, which has been signed off. Do you want us to add them in?

**Comment by Maria-alnap** [comment]
@nadia847 no, no need to. I got confused. The news don't need this so this is good to go. I'll move to done :)
