### ISSUE TITLE
(#202) Comments build (using DISQUS) and theme

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#194]
### Dependencies
- [x] Scoping/wireframing done #57 (decided to implement Disqus and SSO to see if it fits)
---
### Done criteria
- [x] Decide whether to use DISQUS (Maria agreed this in principle #57 u/n comms@alnap.org p/w qA1RtpYg07qV)
- [x] Enable DISQUS comments on blogs in the correct region
- [x] Single sign on for DISQUS
- [ ] Add some styling to comments
---
### ALNAP to check
[Blog page](http://alnap-dev.mrmdev.co.uk/blogs/humanitarian-financing-where%E2%80%99s-the-system-shift)
- [x] Styling looks ok
- [ ] Functionality works as expected
- [ ] Users can sign in to comment with:
   - [ ] their ALNAP website account
  - [ ] their DISQUS account
  - [ ] other accounts listed (Google, Facebook, Twitter)

**Comment by angievanhegan** [comment]
From RUSS: @Maria-alnap @ican-icant  Maria, thanks for the emails from DISQUS, it looks as if the single sign on feature requires pro membership level which costs $99 per month. Would you be happy to consider this or is this too expensive?

**Comment by Maria-alnap** [comment]
@russ-manta I'll ask our programme manager and should have an answer tomorrow

**Comment by Maria-alnap** [comment]
@russ-manta I checked but couldn't see whether we can pay yearly for Disqus instead of every month? Some apps work out to be cheaper if you pay upfront for the whole year... do you know?

**Comment by russ-manta** [comment]
@Maria-alnap @angievanhegan it's monthly only I think

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan great, thanks!

**Comment by angievanhegan** [comment]
@Maria-alnap would you like me to look into your tax question?

**Comment by Maria-alnap** [comment]
Hi @angievanhegan I know for Mailchimp already. Would be great if you could find out about Disqus. Thanks!

**Comment by angievanhegan** [comment]
@Maria-alnap I've sent them an email - although it looks to me like they're based in San Francisco...

**Comment by Maria-alnap** [comment]
@angievanhegan our programme manager told me they were based in Cali? I look forward to your info...

**Comment by angievanhegan** [comment]
@Maria-alnap I received this reply from Disqus. I hope it helps. 

Thanks for reaching out. To clarify, Disqus is not applying any tax to subscription fees. Invoice receipts are emailed to publishers providing invoice #s and other Disqus company information for those who wish to use them for tax purposes, but no taxes are applied to the subscriptions.

PS Sorry, I added this to the wrong issue. I'm sad they're not based in Cali  :o(

**Comment by russ-manta** [comment]
@Maria-alnap do you have any more news on the subscription for DISQUS?

**Comment by Maria-alnap** [comment]
@russ-manta this is now sorted, apologies, forgot to tell you. Please find login details below:
comms@alnap.org
qA1RtpYg07qV

**Comment by angievanhegan** [comment]
@russ-manta Who's working on this one? It's currently unassigned.

**Comment by russ-manta** [comment]
@dilwar for this you will need to setup SSO for DISQUS. The ALNAP DISQUS account details are further up in the thread. There are some instructions on the net about setting up in the DISQUS backend and with Drupal eg. https://help.disqus.com/customer/portal/articles/684744 & https://www.youtube.com/watch?v=SI5oAbzG1Mk  I think this video might be out of date though. If in doubt contact DISQUS support via Alnap's account.

**Comment by dilwarhussain** [comment]
@nadia847 http://alnap-dev.mrmdev.co.uk/blogs/blog-4

**Comment by nadia847** [comment]
@dilwarhussain looks a bit stuck on. can we do a teeny bit of theming here to make it visually integrated with the site?

**Comment by angievanhegan** [comment]
@Maria-alnap this is ready for review.

**Comment by Maria-alnap** [comment]
@nadia847 I'm not getting the notification email from Disqus so I cannot tick the other criteria yet. I'll keep you posted!

**Comment by nadia847** [comment]
@Maria-alnap OK just getting Dilwar to look into this.

**Comment by dilwarhussain** [comment]
@Maria-alnap What notification email is it that you are waiting for?

**Comment by Maria-alnap** [comment]
@dilwarhussain I was trying to test Disqus and I was prompted to sign up, which I found a bit odd because we had set this up for single login. Anyhow, I did sign up but never received a notification email to activate my disqus account. So that's as far as I got with testing it!

**Comment by dilwarhussain** [comment]
@Maria-alnap Single Sign-On means that you should be able to comment with your website account. 

If you're logged into the website with your account you will have the option to comment on the thread using that account. 

If you are not logged into the website you will get the option to log in using your website account to make comments. Or you can also log in with your Disqus account as well as facebook. twitter and google.

If you need any further help with this, please let me know.

**Comment by Maria-alnap** [comment]
@dilwarhussain I know how it works, I just wasn't logged in right when I tried last. Now I tried again and it works fine. Can you move this to done for me? The board isn't loading properly so I'm commenting straight on GitHub instead of Zenhub. Thanks!

**Comment by dilwarhussain** [comment]
That's great, I'll move to done. Thanks @Maria-alnap !
