### ISSUE TITLE
(#200) Card title formatting

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#195]
### Done criteria
- [x] being able to add bold/italics etc to node titles and have them work in teasers

There is no formatting on ALNAP although it seems to work fine on remora?

---
### ALNAP to check
- [x] Test adding bold/italics to page titles and check they appear in displays of those pages eg resources

**Comment by angievanhegan** [comment]
@russ-manta Is this for @meldera to review?

**Comment by russ-manta** [comment]
@meldera can you check this is working ok please?

**Comment by Maria-alnap** [comment]
@angievanhegan I'm not sure I can check this one yet, as I can only pull card of pages we've created via a box link and there's no formatting option for title of pages coming up (unless I missed it!)

**Comment by angievanhegan** [comment]
@matty-manta I think I should have come to the training! can you check this please? Thanks

**Comment by Maria-alnap** [comment]
@matty-manta @angievanhegan if you look at my test page you'll see that I could actually do this via a box link :)
http://alnap-dev.mrmdev.co.uk/marias-test

**Comment by angievanhegan** [comment]
@Maria-alnap I have no idea what a box link is!! :D
