### ISSUE TITLE
(#200) Responsive main menu

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#196]
### Done criteria
- [ ] Search (on desktop) the search should pop down on rollover so that it's consistent with the rest of the menu. On mobile it is a link to the search page
- [x] Desktop menu
- [x] Mobile menu
---
### ALNAP to check
- [x] Check search works as expected in the menu on both desktop and mobile

**Comment by angievanhegan** [comment]
@nadia847 Can you add an estimate to this one please? Thanks

**Comment by ican-icant** [comment]
@angievanhegan  -- no search in menu yet

**Comment by pipemanta** [comment]
@ican-icant the search is only on desktop, on mobile use a link to the search page

**Comment by angievanhegan** [comment]
@russ-manta Done criteria has been update with Steve's comments. Please can you assign to a dev when you're ready? Thanks

**Comment by russ-manta** [comment]
@ican-icant can you clarify please?  do we need search within the mobile menu or is the current link sufficient?

**Comment by angievanhegan** [comment]
@ican-icant Helloooooo! Please can you respond to this one so we can keep it moving? Thanks

**Comment by ican-icant** [comment]
@angievanhegan @russ-manta  I'm sorry but I can't sign this off because it's still broken. The search is only in the header / on the nav when you're signed in! When logged in the search sit above the menu.

**Comment by russ-manta** [comment]
@ican-icant @angievanhegan it's not in the review column.  It's in the spring backlog awaiting pipe. I'll assign to pipe to avoid confusion

**Comment by angievanhegan** [comment]
@ican-icant Please can you answer @russ-manta's question?  Do we need search within the mobile menu or is the current link sufficient?

**Comment by ican-icant** [comment]
@angievanhegan @pipemanta I think the search should pop down on rollover so that it's consistent with the rest of the menu.

**Comment by angievanhegan** [comment]
@russ-manta Please can you assign to someone? Thanks

**Comment by angievanhegan** [comment]
@Maria-alnap careful not to hit the close button, it moves it into the done column and I want to put them in the 'Done this sprint' column so I can count up all the points :smile:
