### ISSUE TITLE
Establish requirements for hosting at ALNAP

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#198]
ALNAP have confirmed that they will host the site with Manta Ray Media and would like to review this after the first 12 months.

**Comment by Maria-alnap** [comment]
@russ-manta I've heard back and can confirm that our current site is 43Gb in the current server.

**Comment by Maria-alnap** [comment]
@russ-manta I'll put you in touch via email with our Head of IT, Peter Gee, now :)

**Comment by angievanhegan** [comment]
@russ-manta Dave is going to provide comparative costs for internal vs external hosting.

**Comment by angievanhegan** [comment]
@dave-manta Did you provide the comparative costs for Maria on Friday? I couldn't tell from the minutes. Thanks

**Comment by dave-manta** [comment]
@Maria-alnap I'm not sure we needed this in the end as ALNAP can give us full access to the server. If that's the case, the cost are no different.

**Comment by Maria-alnap** [comment]
@dave-manta @angievanhegan great to hear that. It would be good to have clarity on a timeline for this (e.g. when you'll need to move stuff to the ODI server if we were to launch on 20 Sept as discussed in last catch up), so that I can chase the Head of IT at the ODI

**Comment by angievanhegan** [comment]
@dave-manta Please can you add an update here from the discussion with Maria on Friday? I wasn't quite clear what was agreed from Steve's notes. Thanks

**Comment by russ-manta** [comment]
@Maria-alnap I'm not sure what if anything was agreed last week but I think what would make sense is to copy the dev site over to your server on the week 4th-8th September to test the performance and make sure any dependencies (eg Apache SOLR etc) are installed during that week.  How does that sound?

**Comment by Maria-alnap** [comment]
@russ-manta @dave-manta @angievanhegan Apologies for the back and forth with this, but now ODI is suggesting it may make more sense for you to host as long as they can keep control of the domains. Is this something that would work for you?

**Comment by russ-manta** [comment]
@Maria-alnap @dave-manta @angievanhegan this is fine by us, did we give you a cost for hosting?

**Comment by Maria-alnap** [comment]
@russ-manta yes, @dave-manta did.  Tim, Alex and I think that going with you guys would be the more sensible option but I need to run this through finance before confirming 100% I'll do so on Monday :)

**Comment by angievanhegan** [comment]
Hi @Maria-alnap I'm assigning this to you as the action is with you to confirm. Thansk

**Comment by dave-manta** [comment]
@angievanhegan costs are in our original proposal.

**Comment by angievanhegan** [comment]
@dave-manta yes, Maria confirmed 3 days ago she has the costs. She's just checking with Finance that they'll approve it.

**Comment by Maria-alnap** [comment]
@dave-manta @angievanhegan @russ-manta just to confirm that we're OK to go with you for hosting the site on your server. We would like to revisit this in a years' time, if that's OK with you.

**Comment by angievanhegan** [comment]
@russ-manta Are there any next steps here, or do we wait until we're getting ready to go live?

**Comment by russ-manta** [comment]
@angievanhegan don't think so I think this can be moved to done
