### ISSUE TITLE
Wireframe for list view for jobs/resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#20]
linked to #59 and #60

**Comment by ican-icant** [comment]
@angievanhegan  Hoping a wireframe not needed as we have a design for resources on list view here https://projects.invisionapp.com/d/main#/console/10292473/236943102/preview and this could be the style for all list views. It was also verbally signed off by ALNAP

**Comment by angievanhegan** [comment]
@ican-icant  I've moved it over to signed off on the page status board and I'm moving this to done then.
