### ISSUE TITLE
Sprint goal: Homepage

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#200]
**Only tick when in the DONE column**
- [x] Homepage top band #170
- [ ] Homepage news/resources #169
- [ ] Twitter integration #126
---

### Done in sprint 5
- [x] Header #124
- [x] Footer #125
- [x] Responsive menu #196

-------
### Designs
- [Homepage wide](https://invis.io/NSCBN3KQ5)
- [Homepage wide nav](https://invis.io/6KCBN4KYE)
- [Mobile version](https://invis.io/9XCBN2XZ4)
- [Mobile nav](https://invis.io/5MCBMRUDQ)

**Comment by ican-icant** [comment]
@angievanhegan noticed a wider gap between latest resources and events
