### ISSUE TITLE
(#202) Design/wireframe blog CTA

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#205]
### Done criteria 
- [x] Design needed for the blog call to action
---
### Designs
- [Blog landing](https://invis.io/7CC18FLJ4)
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@russ-manta do we need something more than the 'got an idea for a blog?' button at the top of the landing page? I'd assumed that just opened an email. What do you think?

**Comment by russ-manta** [comment]
@angievanhegan maybe that is enough it's fairly low key but if that is all that was envisaged that's fine.  @ican-icant is the Idea for a blog link/button all we need for this Blog CTA?

**Comment by ican-icant** [comment]
yeah, that's all we need. Keeping top of the pages light @angievanhegan  @russ

**Comment by angievanhegan** [comment]
Design not needed - there's already a button. I'll update #188 with these details.
