### ISSUE TITLE
(#215) Footer newsletter sign up to connect to ALNAP newsletter

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#207]
### Dependencies
- [x] Login to ALNAP mailchimp account
OR
- [x] Mailchimp list embed Form code
- [ ] API key to connect drupal to ALNAP mailchimp account

### Done criteria
- [x] Embed ALNAP newsletter subscribe form in footer
- [x] Test subscriptions work ie email subscriptions via the form in the footer are added to mailchimp
---
### ALNAP to check
- [x] Embed ALNAP newsletter subscribe form in footer
- [x] Test subscriptions work ie email subscriptions via the form in the footer are added to mailchimp

**Comment by angievanhegan** [comment]
@Maria-alnap Are you happy to share your mailchimp account details with  us, it'd make this a lot quicker for us to do.

**Comment by Maria-alnap** [comment]
@angievanhegan Of course! Please find them below:
comms@alnap.org
PW: N7D3P8oFLL5?g

**Comment by Maria-alnap** [comment]
@russ-manta @nadia847 Would you please explain to me what I need to do/check here? I'm not sure. Thanks!

**Comment by nadia847** [comment]
@Maria-alnap use the sign up field in the footer to subscribe to your mailchimp list. If the email address ends up correctly subscribed: it works.

**Comment by Maria-alnap** [comment]
@nadia847 haha, sounded more complicated than it was. Apologies! All checked and working well 👍

**Comment by nadia847** [comment]
@Maria-alnap perfect! 👍
