### ISSUE TITLE
Review user profile views/permissions

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#219]
### Done criteria
- [x] Blog author page only shows rhs details if the user is logged in
- [x] Only show status, manage my account links & add jobs etc on own profile
- [x] Member updates and bookmarked resources only on own profile
- [x] Theme add to my list/remove from my list bookmarking button on resources eg. http://alnap-dev.mrmdev.co.uk/test-innovation-resource
- [x] ISSUE: Remove Member updates from Blog author profiles
---
### ALNAP to check
- [x] User's own profile matches design (alnap-dev.mrmdev.co.uk/user)
- [x] Able to bookmark resources and see them on user page
- [x] Can see member updates on your own profile page
- [ ] Correct information is displayed for blog author (http://alnap-dev.mrmdev.co.uk/users/mr-admin-admin)
- [x] ISSUE: Remove Member updates from Blog author profiles

**Comment by Maria-alnap** [comment]
@nadia847 Is this ready to check?

**Comment by nadia847** [comment]
@Maria-alnap I've edited the alnap criteria above and added links. hope that helps!

**Comment by Maria-alnap** [comment]
@nadia847 I've only ticked first one as I cannot see the button to add the resources to my account in any of the ones that are currently up. Also, the Member updates are currently showing on the blog author profile that you linked above.

**Comment by russ-manta** [comment]
@cutlern can you theme the bookmark resources button please?

**Comment by Maria-alnap** [comment]
With the could we swap the member update (maybe four on a row in a slider for more?) and the bookmarked resources around on the user page? They get a little lost all the way down at the bottom

**Comment by Maria-alnap** [comment]
@russ-manta 

also, in addition to the above comment, how might we edit/update the bio as displayed here? http://alnap-dev.mrmdev.co.uk/users/mr-admin-admin
