### ISSUE TITLE
Wireframe submit a resource page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#22]

**Comment by melkers** [comment]
Not sure this needs wireframing

**Comment by angievanhegan** [comment]
Do we just clarify the requirements when we're doing sprint planning?

**Comment by melkers** [comment]
@angievanhegan here's the page on their current site and I think we need something fairly similar which we can work out at sprint planning. http://www.alnap.org/account/submitresource.aspx

**Comment by dave-manta** [comment]
I'm closing this.
