### ISSUE TITLE
Body field isn’t appearing on resource; card content is in different place

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#227]
This came up at training. Let me know if it doesn't make any sense .

### ALNAP to check
[Link to what Maria needs to look at](https://)
- [ ] Agree description is a legacy field

**Comment by angievanhegan** [comment]
@dilwarhussain Should this be in the In progress column? Ta

**Comment by dilwarhussain** [comment]
@angievanhegan @Maria-alnap The resource node is now showing the body field. I cannot see where the 'description' field is being printed on the live site and looking through a few of the imported resources they all say 'Available on request' does this field still need to be used for anything?

I've also moved the 'card content' field to an easier to find place.

**Comment by angievanhegan** [comment]
@matty-manta Could you check this is what Maria wanted before we assign it to her for review please? Thanks very much.

**Comment by matty-manta** [comment]
@angievanhegan Yep - two issues we spotted in training was the lack of consistency for card content (which Dilwar has changed) and the fact that the body field wasn't appearing anywhere. I think the question that remains is whether the "description" field is a legacy field that's now redundant.

**Comment by angievanhegan** [comment]
@russ-manta one for you. Thanks

**Comment by russ-manta** [comment]
@Maria-alnap the description field is a legacy fiedl and all content from that field is now being imported into the new body field as you can see here: http://alnap-dev.mrmdev.co.uk/strategic-humanitarian-co-ordination-in-the-great-lakes-region-1996-1997

**Comment by angievanhegan** [comment]
@Maria-alnap This is ready for you to look at again. thanks

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta this looks good to me. I'll move it to done.
