### ISSUE TITLE
(#216) What is resource category on the individual resource?

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#228]
Question from training session: What is resource category on the individual resource? 

- Might be a duplicated field (from the import, which we then migrate from import field to a new one) - needs investigation

**Comment by meldera** [comment]
Term reference for http://alnap-dev.mrmdev.co.uk/admin/structure/taxonomy/resource_category vocabulary

**Comment by russ-manta** [comment]
@Maria-alnap this corresponds to the crisis category on your current site and will be removed once all resources have been imported and retagged

**Comment by Maria-alnap** [comment]
OK all good. WIll move to done
