### ISSUE TITLE
(#212) Build Portal pages

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#23]
### Done criteria
- [x] Setup domain access create 2 new domains eg. http://www.syrialearning.org/
- [x] Blogs, events, resources etc should use exisiting content types
- [x] Create new views if needed or add domain filter to views to display content on portals (added domain filter to existing views)
- [x] Create separate menus for each domain
- [x] New footer required
- [x] There are some resources which only appear in the portals and not the HELP library. See #95
- [x] New sitewide context for portals
- [x] Twitter nugget needs to work with portal specific twitter account. Just the one at the moment (Principled humanitarian action)
- [x] Create new template for menu
- [x] ISSUE: Opening resource does not change 'site'

---
### Designs
- <a href="https://invis.io/5SCAXSEBM"> Principled Humanitarian Action</a>
- <a href="https://invis.io/CQCCBR53T">  Urban</a>

---
### ALNAP to check
- [ ] ?
- [ ] ?
---

#### Notes

**Content on portals**
- Resources 
- Events 
- Twitter feed 
- Community of Practice

**Criteria for pulling resources to portals**
- Multiple queries combining tags/countries etc 
- Resources can also be cherry-picked by selecting the portal tag as these might not meet the original search criteria but can still be relevant, eg. Similar crisis but in different location 
 
If this is fiddly (the 'smart' updating query), we should consider running a query and bulk ticking the portal (which is likely to be an entity reference to a portal content type node) and then they can just manually add more going forward by just selecting the entity portal reference. No auto-adding in the future.

**Active vs archived portals **
Either have titles on the portals page splitting the two types, or a stamp on the Portal so show it's archived or a filter or tabs. 

-------
The urban portal has an "initiative" directory - outside of scope 
Could be replaced with a standard page.

12.5 days = £7000

**Comment by ican-icant** [comment]
Wireframe is done but chat is needed with Russ and Dave about what can be done to make the portals look different to the main site.

**Comment by dave-manta** [comment]
@ican-icant aren't we waiting for approval of our quote to determine how we proceed with portals?

**Comment by angievanhegan** [comment]
Yeah - good point. This is blocked until we've got answer from ALNAP

**Comment by ican-icant** [comment]
I've added a wireframe to invision for the new look portal and quote based on £7K, based on the requirements: 
1. Setup each sub-domain
2. Resource/events and other content are assigned to a sub-domain
3. New portal theme and then each portal can have some customisation of the theme.
4. Portal home page content type
5. New header inc. Nav.

 Can have a sub-domain or have its own domain.  One would redirect to the other, whichever way ALNAP preferred

**Comment by angievanhegan** [comment]
Maria confirmed that this can come into scope.

**Comment by Maria-alnap** [comment]
We've added comments on invision directly for the design of the portal page. I'm copying below as well:
We love the design for the portals! You definitely cracked it 
We do think that we need to add somewhere at the top that the portals are hosted by ALNAP. It doesn't need to be super prominent but the info needs to be there in some shape or form, even a sentence would suffice.
Would you play around with options for this? Thanks!

**Comment by ican-icant** [comment]
@Maria-alnap  do users need to log in to portals so that they can view member only resources or do you not add member only resources to portals?

**Comment by Maria-alnap** [comment]
@ican-icant We don't expect to have member only resources in the portals

**Comment by angievanhegan** [comment]
@ican-icant This is with you to make sure the portal design shows that they are hosted by ALNAP.

**Comment by angievanhegan** [comment]
@Maria-alnap Please can you confirm which portals have twitter accounts (and confirm which don't) and let us have the details? Thanks


- Urban Response Portal
- Syria Evaluation Portal... (
- Principled Humanitarian Action in Practice
- ECB Project
- Haiti Learning and Accountability Portal
- Tsunami Evaluation Coalition

**Comment by Maria-alnap** [comment]
@angievanhegan: the only one that may have one is the Principled Hum Action one (we're chasing them at the moment to ask). It may be that other of the new ones we build will do as well, so leaving space for twitter feeds on the template would be a smart idea

**Comment by angievanhegan** [comment]
@dilwarhussain FYI

**Comment by angievanhegan** [comment]
@dilwarhussain please can you update the done criteria with this? Thanks

**Comment by dilwarhussain** [comment]
Done @angievanhegan

**Comment by nadia847** [comment]
@dilwarhussain so i noticed that if a resource is in a portal and you click on it in the alnap help lib, you end up on the portal. Is that expected behaviour @dave-manta @ican-icant ?

**Comment by dave-manta** [comment]
@nadia847 @dilwarhussain I believe that it would make sense to stay within 
whichever site the resource is clicked in (if that makes sense).

**Comment by angievanhegan** [comment]
@nadia847 I added an issue and put this back into the sprint backlog.

**Comment by Maria-alnap** [comment]
@dave-manta @nadia847 It would be good to discuss this. Is there a way that we could signpost that the resource is in the HELP Library and in the portal? As we will be building hybrid portals in the future (hosting both resources that are within and outside the HELP Library), it would be good to show the user where the specific resource he's looking at lives. It's more of a political/positioning thing for ALNAP, but quite an important one!

**Comment by ican-icant** [comment]
@Maria-alnap I understand the political nature of thsis but just wondering how useful it is for the user or whether it will just confuse people. Def worth a discussion but would have to come later.

**Comment by angievanhegan** [comment]
@ican-icant Did we come up with a solution to this at the meeting? If we did, can you make a note of it here please and add any relevant done criteria? Thanks

**Comment by dilwarhussain** [comment]
@ican-icant Clicking on a resource that shows in another portal now stays in the site that you are viewing. For a resource to act like this, on save you need to keep the 'Source domain' as 'Use active domain' (This is default). You can also pick a domain if you would like it to go off to that particular domain.

**Comment by russ-manta** [comment]
@ican-icant is there anything left to check on this now? I think Dilwar fixed the issue with resources opening on the same site

**Comment by russ-manta** [comment]
@ican-icant are you able to take a look at this?

**Comment by ican-icant** [comment]
Done done @russ-manta

**Comment by angievanhegan** [comment]
@matty-manta Please can you show ALNAP how to edit these? thanks
