### ISSUE TITLE
(#208) Design, build and theme 'My account' button

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#231]
### Done criteria
- [x] When a user logs in, we need a 'My account' button to the left logout.  It needs to be more prominent from the logout

Check the new design here https://projects.invisionapp.com/d/main#/console/10292473/240257350/preview

And the button on the header after login http://alnap-dev.mrmdev.co.uk/

---

**Comment by dave-manta** [comment]
When a user logs in, we need a 'My account' button to the left logout.  It needs to be more prominent from the logout so you may need design input from Cat.

@angievanhegan tagging you on this one.

**Comment by cat-manta** [comment]
@dave-manta Have updated the design of 'My account', the log out box background is now #7596AE

**Comment by dave-manta** [comment]
over to @pipemanta ?

**Comment by dave-manta** [comment]
@angievanhegan is stuff to be assigned to me for review?

**Comment by angievanhegan** [comment]
@pipemanta Please can you add a link in the box at the top to where Dave can review this? Also, can you estimate it please? Thanks

@dave-manta The process we're working towards would be to put this in the sprint backlog so we can prioritise and estimate it (to help us learn how much we can do in a sprint), then make sure it has clear done criteria (so the dev knows exactly what to do and the reviewer knows exactly what to check). Then Russ will assign it to a member of the team.

**Comment by dave-manta** [comment]
@angievanhegan sounds good.

**Comment by angievanhegan** [comment]
@dave-manta Please can you write some ALNAP review criteria at the top of this issue so she knows exactly what to check, then assign it to Maria? If you don't think she needs to check this then please feel free to move it straight to 'Done this sprint'. Thanks

**Comment by dave-manta** [comment]
Moving to 'Done this sprint' @angievanhegan
