### ISSUE TITLE
(#212) Portal events landing page(s)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#235]
### Done criteria 
- [ ] Apply portal theme to portal events landing pages:
  - [x] [Urban humanitarian response](https://invis.io/92CRDWLXS)
  - [x] [Principled humanitarian action in practice](https://invis.io/8TCV59T9W)
  - [x] [Syria evaluation portal...  (CALL)](https://invis.io/U8CV5BXWF)
  - [x] [Emergency capacity building project](https://invis.io/CBCV5BFFE)
  - [ ] [Haiti Learning and Accountability Portal](https://invis.io/DCCV5AF4F)
  - [ ] [Tsunami Evaluation Coalition (TEC)](https://invis.io/VACV5B4HZ)

**Comment by russ-manta** [comment]
@pipemanta can you check with Dilwar if anything left here?
