### ISSUE TITLE
(#212) Confirm colors for all portals

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#237]
### Done criteria
Confirm colours for all of the portals:
- [x] Urban Response Portal
- [x] Syria Evaluation Portal... (CALL)
- [x] Principled Humanitarian Action in Practice
- [x] ECB Project
- [x] Haiti Learning and Accountability Portal
- [x] Tsunami Evaluation Coalition (TEC)

---
### Designs
- [Portal example - Principled...](https://invis.io/5SCAXSEBM)
- [Portal example - Urban](https://invis.io/CQCCBR53T)
- [Portal style guide](https://invis.io/92CRDWLXS)
---
### ALNAP to check
Happy with colours for: 
- [x] [Urban humanitarian response](https://invis.io/92CRDWLXS)
- [x] [Principled humanitarian action in practice](https://invis.io/8TCV59T9W)
- [x] [Syria evaluation portal...  (CALL)](https://invis.io/U8CV5BXWF)
- [x] [Emergency capacity building project](https://invis.io/CBCV5BFFE)
- [x] [Haiti Learning and Accountability Portal](https://invis.io/DCCV5AF4F)
- [x] [Tsunami Evaluation Coalition (TEC)](https://invis.io/VACV5B4HZ)

**Comment by angievanhegan** [comment]
Hello @cat-manta - please can I ask you to provide a colour for each of the portal sites? If you can tick the boxes a the top to confirm you've done each colour, then we can assign this issue to @Maria-alnap and move it over to the 'ALNAP to review' column for her to check (with a link to an invision slide showing the colours? 

Also, if you can drag this card into the 'In progress' column when you start work, that would be great. Thank you!

**Comment by cat-manta** [comment]
@angievanhegan Are these the colours already used on the current portals or am I coming up with totally new colours?

**Comment by angievanhegan** [comment]
@cat-manta good question! I think you're coming up with new ones. @Maria-alnap can you confirm please? I know we talked about picking a colour from their logo (if they have one). Thanks

**Comment by cat-manta** [comment]
@angievanhegan @Maria-alnap I have asked Steve about this and he said Maria has previously said to use the colours on the current portals, in which case you guys need to come up with colours for the [Haiti portal](http://www.alnap.org/current/Haitilearningportal) and [Tsunami coalition](http://www.alnap.org/tec) as they don't currently have any.

**Comment by cat-manta** [comment]
As far as I know, these are the portal colours so far:

- Urban humanitarian response: #862046
- Principled humanitarian action in practice: #FF7602
- Syria evaluation portal for Coordinated Accountability and Lessons Learning (CALL): #007A3D
- Emergency capacity building project: #932922

I have uploaded the [website colour palette](https://invis.io/72BDLFJYG#/245883604_Colour_Palette_V01) to invision.

**Comment by Maria-alnap** [comment]
@cat-manta @angievanhegan those colours are accurate, thanks! Of course, when having new portals we'll need to add new ones accordingly but we can cross that bridge when we get to it :)

**Comment by cat-manta** [comment]
@Maria-alnap are the Haiti and Tsunami portals not having their own websites?

**Comment by Maria-alnap** [comment]
@cat-manta @angievanhegan they are not active portals, and in practice, they're just pages with links, not like the newer portals that we've done, so the answer is that I'm not sure. I'll have an answer for you on Monday.

**Comment by cat-manta** [comment]
@Maria-alnap Great thanks Maria! If they have their own websites, I'd suggest 'Sea blue' as the highlight colours for both, or maybe 'Sea blue' and 'Medium vermilion' (have just updated the colour palette with this colour which is used as a hover colour on the main alnap site)

**Comment by Maria-alnap** [comment]
@cat-manta looks good! Please go ahead with that :)

**Comment by angievanhegan** [comment]
@cat-manta I think this is just with you to update the colour palette? Thank you :o)

**Comment by cat-manta** [comment]
@angievanhegan I have updated the palette!

@Maria-alnap I've also slightly changed the portal colours, although this is only on a styleguide that you probably haven't seen yet anyway. ([the portal styleguides are here](https://invis.io/72BDLFJYG#/245445460_Portal_-_Urban_Styleguide) if you want to have a look) Nadia noticed the month and the share boxes should be a different, neutral colour that doesn't look like a link so each portal now has a second darker version of their highlight colour.

This might also need to change on the main site, as the month boxes on [the events page](https://invis.io/72BDLFJYG#/232167017_Events_Wide) are orange which is the button colour, so what do you think about changing these boxes to the red hover (medium vermilion) or one of the more muted colours such as the grey-blue (weldon blue) from the logo?

**Comment by Maria-alnap** [comment]
@cat-manta @angievanhegan : going for the medium vermillion for the event date boxes sounds good. Not sure it would look as nice with the greys...

**Comment by cat-manta** [comment]
@Maria-alnap Great, I've updated the events designs to include medium vermilion.

Steve has just seen the suggested colours for the tsunami and haiti portals as he was away on Friday, and wasn't keen on using colours from the main ALNAP website, so we've come up with a couple other colours to replace them. I have updated the designs and colour palette with the new colours:
-[Tsunami portal](https://invis.io/72BDLFJYG#/246057229_Portal_-_Tsunami_Styleguide)
-[Haiti portal](https://invis.io/72BDLFJYG#/246057228_Portal_-_Haiti_Styleguide)

What do you think?

**Comment by Maria-alnap** [comment]
@cat-manta unfortunately going with those colours would be confusing as we use green for our evaluation stuff and similar shades of that blue for a couple of other workstreams. Can we revert to your previous suggestion? It may well be that we stick to greys for these. As I mentioned, these portals are not active at the moment so having them greyish/toned down would work. I'd prefer to keep these new ones for new portals that may come up...

**Comment by ican-icant** [comment]
@Maria-alnap @cat-manta that's OK - I haven't seen the greys but I think there are enough colours out there for us to find two new ones that aren't core ALNAP colours. I'm already concerned the orange portal is too similar to ALNAP (can this be changed?).

**Comment by Maria-alnap** [comment]
@cat-manta @ican-icant that's why I was thinking that going with greys for these 2 would be a good idea. They're more of a legacy thing and not active, tbh... Also not worth spending that much time on them

**Comment by cat-manta** [comment]
We could use Weldon blue (#7596AE) for the inactive portals if @ican-icant and @Maria-alnap are both okay with that?

**Comment by Maria-alnap** [comment]
@cat-manta @ican-icant I'm happy to go with that blue for inactive portals
