### ISSUE TITLE
(#212) Setup all portal pages and assign theme

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#238]
### Dependancy
- [x] Setup 'system for theming portals #132
- [x] Confirm colours for all portals

- --
### Done criteria - setup portals
- [x] Humanitarian Learning and Accountability Portal (HELP)
- [x] Urban Response Portal
- [x] Syria Evaluation Portal... (CALL)
- [x] Principled Humanitarian Action in Practice
- [x] ECB Project
- [ ] Haiti Learning and Accountability Portal
- [ ] Tsunami Evaluation Coalition (TEC)

---
### Done criteria - theme portals
- [x] Humanitarian Learning and Accountability Portal (HELP)
- [x] Urban Response Portal
- [x] Syria Evaluation Portal... (CALL)
- [x] Principled Humanitarian Action in Practice
- [x] ECB Project
- [ ] Haiti Learning and Accountability Portal
- [ ] Tsunami Evaluation Coalition (TEC)

---
### ALNAP to check
Does each portal look right
- [ ] [Humanitarian Learning and Accountability Portal (HELP)](https://)
- [ ] [Urban Response Portal](https://)
- [ ] [Syria Evaluation Portal... (CALL)](https://)
- [ ] [Principled Humanitarian Action in Practice](https://)
- [ ] [ECB Project](https://)
- [ ] [Haiti Learning and Accountability Portal](https://)
- [ ] [Tsunami Evaluation Coalition (TEC)](https://)

**Comment by angievanhegan** [comment]
@nadia847 Did you know about this issue, or has this already been done...?

**Comment by nadia847** [comment]
@angievanhegan well this is the rest of the portals which we shouldn't do until we have ironed out the first one.

**Comment by russ-manta** [comment]
@dilwarhussain @nadia847 can we stup the new portals now please?

**Comment by russ-manta** [comment]
@pipemanta this may all be done - can you check with @dilwarhussain

**Comment by Maria-alnap** [comment]
Update: have requested to @russ-manta to create the basic portals for the last two that we haven't set up (tec and haiti). They should be ready by the end of the week :)
