### ISSUE TITLE
(#234) Creating member organisations in Civi

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#245]
### Done criteria
- [x] Create the process for creating member organisations in Civi
- [x] Arseni to add rule to sync new organisations in Civi with the drupal organisation content type, Dave to then try importing organisations
- [x] Checkbox on organisation content type or similar to denote display this node on Drupal site - using unpublished to hide non members
- [ ] Ability to take new or collect recurring payments from member organisations?? is this required?
- [x] Check memberships within Civi apply to member organisations and their users

---
### Designs
- [ ] Maybe for payment pages
---
### ALNAP to check
- [x] Check all relevant member organisations added to CiviCRM and Drupal
- [x] Check that adding / editing an organisation in CiviCRM creates a new organisation in Drupal or changes it's name if modifying an existing member
- [x] Is there any method required to take payments for new member organisations via the website?

### More info ####
Currently agencies are being used on resources view to denote who a resource is assigned to.
This is going to be changed so that all agencies will use the organisation content type.
Organisations/agencies will be imported into Civi and a corresponding Drupal entity created using a rule.
This will remove the need to have a taxonomy for Agencies.

**Comment by russ-manta** [comment]
@meldera I've added a DONE task here for your rule which creates organisation nodes when an organisation is added to Civi

**Comment by Maria-alnap** [comment]
@nadia847 What is it that I have to check here? (Apologies, with Russ away I'm unsure!)

**Comment by dave-manta** [comment]
@Maria-alnap I believe this is all done, but let's discuss as part of our review of registration / login.

**Comment by Maria-alnap** [comment]
@dave-manta Don't think that we touched on this earlier?

**Comment by dave-manta** [comment]
@Maria-alnap nope we didn't in the end. Didn't want info overload?!  Whenever you want...

**Comment by dave-manta** [comment]
@Maria-alnap I believe all you need to do is add the organisaton in Civi, for brand new organisations that you want to add to your site.
