### ISSUE TITLE
Resource series display bug

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#249]
The card images are big and should be the same size as they appear on the home page

http://alnap-dev.mrmdev.co.uk/test-innovation-resource

@nelle Put 2 in a boxy row (row-max 2)

**Comment by meldera** [comment]
this has been set up this way intentionally. can be changed here:
http://alnap-dev.mrmdev.co.uk/admin/structure/block/manage/views/resource_node-block_1/configure
http://alnap-dev.mrmdev.co.uk/admin/structure/block/manage/views/resource_node-related/configure

**Comment by nadia847** [comment]
http://alnap-dev.mrmdev.co.uk/test-innovation-resource 

should look like https://projects.invisionapp.com/d/main#/console/10292473/236943102/preview
