### ISSUE TITLE
Wireframe member page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#25]

**Comment by ican-icant** [comment]
@angievanhegan - this already exists https://invis.io/4FC0LF7RE#/222960812_Member

**Comment by angievanhegan** [comment]
@ican-icant I'm assuming it'll be ok for the client to sign off on the wireframe? I've optimistically moved it to the review column.

**Comment by angievanhegan** [comment]
Signed off! 6 June
