### ISSUE TITLE
CiviCRM admin user role

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#251]
Separate Drupal user role for ALNAP to have access to Civi. In time, we could have different levels of permission within Civi, so I think it makes sense to start with a separate role now.

**Comment by angievanhegan** [comment]
@russ-manta When should we do this? 
@dave-manta Can you estimate the size of it please?

**Comment by dave-manta** [comment]
@angievanhegan Oops, all done!
