### ISSUE TITLE
(#137) Contact us page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#252]
### Done criteria
- [x] DISCUSSION - Add node details type box - How do we do this on a page node?
- [x] Add share icons to the page
- [x] Check iframe embeds for maps
- [x] Download PDF button styles
- [x] Apply details box styles and simplify HTML

### Wireframe
[Contact us](https://invis.io/3KCWGE8SR)

### ALNAP to check
http://alnap-dev.mrmdev.co.uk/about/contact-us
- [x] Share icons appear on the page
- [x] Can add/edit box on the right
- [x] Can embed maps
- [x] Can add a button linking to a pdf map

**Comment by nadia847** [comment]
@dave-manta @russ-manta this now looks like the design but as the text format has been changed for the white contact details nugget at the top, alnap won't be able to change content. was that agreed?

**Comment by dave-manta** [comment]
Had a look at the page, don't believe I can comment.

**Comment by russ-manta** [comment]
@Maria-alnap should there be a link to the contact us in the footer or somewhere else in addition to the menu under About?

**Comment by Maria-alnap** [comment]
@russ-manta would it be the title 'Contact' in the footer would be a link? Or would you put 'contact us' as a link under the email? I do think it would make sense to have the link to the contact us page on the footer. (Alex)

**Comment by Maria-alnap** [comment]
(it's Alex) Just ran through the new checks and these are still issues:

- In the sidebar, I can add and edit boxes, but it sometimes doesn't bold the text 
- I can add a new map content block, but the iframe doesn't embed the map on the page

**Comment by russ-manta** [comment]
@cutlern can you take a look at these 2 issues please?
@Maria-alnap (alex) will you ever need more than 1 map on this page?

**Comment by cutlern** [comment]
@Maria-alnap 

Hi Maria! I think the issue was with the address you pasted in the iframe URL, did you paste the web address or the share > embed map address? 

Also, sorry but I haven't been able to recreate your issue with the bold text, I've tested it by using the bold button and holding cmd + b and they both seem okay, what part of the text in the sidebar are you trying to bold?

**Comment by Maria-alnap** [comment]
@cutlern Thanks! All good now. Will move to done 👍
