### ISSUE TITLE
Sub topics - problems with nuggets?

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#253]
@russ @matty Just wondering whether there's still some work needed on the subtopics within topic pages? We are trying to set one up now and the sub topic nugget is working funny. The sub topic that we created is also popping up in other existing topic pages..

[example]
(http://alnap-dev.mrmdev.co.uk/our-topics/monitoring-of-humanitarian-action)

**Comment by russ-manta** [comment]
@Maria-alnap what other pages is the sub topic showing up on?

**Comment by Maria-alnap** [comment]
@russ-manta http://alnap-dev.mrmdev.co.uk/our-topics/evaluation#sub-589

**Comment by russ-manta** [comment]
@nadia847 can I assign this one to you in my absence please, feel free to reassign if you need.

**Comment by angievanhegan** [comment]
@nadia847 when you have an idea what's going on with this one, please can you add an estimate? Thanks

**Comment by nadia847** [comment]
@angievanhegan @russ-manta sure no problems. I'll take care of it and add an estimate soon as.

**Comment by nadia847** [comment]
@Maria-alnap this should now be fixed.

**Comment by Maria-alnap** [comment]
@nadia847 thanks! This is working OK now :)
