### ISSUE TITLE
(#137) Manual redirects setup

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#255]
### Done criteria
- [x] Ensure redirects have been enabled
- [x] Ensure editors have access to add redirects
----

### ALNAP review criteria
- [x] Ensure redirects can be created

**Comment by Maria-alnap** [comment]
@nadia847 @matty-manta I'd be happy to sign this off if you could explain to me how to do it? :)

**Comment by matty-manta** [comment]
@Maria-alnap fancy a skype chat? I'm matthew-manta

**Comment by Maria-alnap** [comment]
@matty-manta Happy to! Apologies if has taken so long to get back. I've had a mental week! I'm around in the afternoon. I'll add you to Skype now and take it from there. I'm alnap.secretariat

**Comment by angievanhegan** [comment]
@matty-manta Please can you contact Alex and Tim on Skype and arrange to show them how to do these? We need to get stuff signed off by Friday. Cheers.

**Comment by matty-manta** [comment]
@angievanhegan I've shown the guys how to do redirects - sorry this was left hanging. This is ready for sign off as far as I know.
