### ISSUE TITLE
Box links hover

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/alnap#256]
Jerky behaviour of box links on hover

**Comment by angievanhegan** [comment]
@matty-manta do you have a second to add a link with an example? Cheers :o)

**Comment by matty-manta** [comment]
Sorry @nadia847 

The box link at the bottom of this page:

http://alnap-dev.mrmdev.co.uk/marias-test

**Comment by matty-manta** [comment]
Hey @Maria-alnap 

So adding one box to a box links nugget, while having multiple items per row causes this jerky behaviour. If you check your test page again:

http://alnap-dev.mrmdev.co.uk/marias-test

Then you'll see I've added some more box links nuggets to show how they ought to be configured to ensure you don't get that jerky behaviour.

Hope that's all ok, of course any questions just let me know.

Matty

**Comment by Maria-alnap** [comment]
@matty-manta Thanks! That makes sense. We'll keep it in mind!
