### ISSUE TITLE
(#201) Modify resources importer - Monday 25th September

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#263]
### Dependencies
- [x] Dave to create spreadsheet linking all resources in export to the relevant node id for the new organistion node in Drupal

---
### Done criteria
- [x] Modify importer to add entity reference from Resource to the relevant organisation node
- [x] Test importer
- [x] Import all resources to test search/import

**Comment by russ-manta** [comment]
@dave-manta have you done this bit? 'Dave to create spreadsheet linking all resources in export to the relevant node id for the new organistion node in Drupal'

**Comment by dave-manta** [comment]
@russ-manta negative. Might need to discuss with you how this can be done.
