### ISSUE TITLE
Yoast SEO module for facebook posts

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#267]
We were wondering if you could enable YoastSEO on the website? The reason we'd like this is to be able to edit cards on Facebook posts.

(You may have seen that Facebook have stopped allowing users to edit the ‘card text’ when sharing a link in a post, to stop the spread of fake news. Unfortunately this means for some links - such as blogs - that the text that is previewed is the website footer text (even when you add a photo. Yoast would allow us to do this, hence the request!)

### Dependencies
- [ ] None

---
### Done criteria
- [x] Try using Mettags (opengraph) for this, discuss with Maria

---
### ALNAP to check
- [ ] Check ability to control cards for facebook posts via meta tags (@matty to explain)

**Comment by russ-manta** [comment]
@Maria-alnap I think Matty showed you how to use Metatags for this

**Comment by angievanhegan** [comment]
@Maria-alnap If @matty-manta has explained this to you, can it be signed off? Thanks

**Comment by Maria-alnap** [comment]
Yes, all good. I'll move to done.
