### ISSUE TITLE
Blog posts view - link person page to user account for blog author

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#269]
Currently there is no link between a person and their user account so blog posts are not shown on a person page.
Create a link from the person page eg. http://alnap-dev.mrmdev.co.uk/john-mitchell to that person's profile page and vice versa from the profile page to the person page

---
### Done criteria
- [ ] Create reference between person node and user account
- [ ] Display a user's blogs on their account page but a link from the person to account page and vice versa

---
### ALNAP to check
- [x] Can link person to their account page eg .http://alnap-dev.mrmdev.co.uk/about/meet-our-team/mr-admin-admin
- [x] View blogs button appears on link above directing to the profile page
- [x] View Staff profile link appears on account page eg. http://alnap-dev.mrmdev.co.uk/users/mr-admin-admin

**Comment by russ-manta** [comment]
@cutlern is this one now done?

**Comment by cutlern** [comment]
@russ-manta yes? I think i must have stuck it in the wrong column D:

**Comment by angievanhegan** [comment]
All the ALNAP criteria have been ticked so I'm moving this to done.
