### ISSUE TITLE
WYSIWYG text crop when pasting text into body

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#270]
First line of text is cut in half
### Done criteria
- [x] First line of text is not cut off in the WYSIWYG

---
### ALNAP to check
- [ ] First line of text is not cut off in the WYSIWYG

**Comment by russ-manta** [comment]
@matty can you verify this? 
![cropped text in text editor](https://user-images.githubusercontent.com/25846670/30431064-4a034ee6-9955-11e7-9394-81041dfbc70c.png)

**Comment by matty** [comment]
You tagged the wrong person? :)

**Comment by russ-manta** [comment]
@matty sorry about that! I left the rest of the username off :)

**Comment by russ-manta** [comment]
@matty-manta can you verify this is happening please?

**Comment by matty-manta** [comment]
@russ-manta yes - you move the scroll bar to the top of the field and the first line of text is hidden. @Maria-alnap you can still find it by placing your cursor in the WYSIWYG and pressing the up arrow until you get to the top of the text.

**Comment by Maria-alnap** [comment]
OK, all good. I'll move to done too 👍
