### ISSUE TITLE
Team nugget in sidebar not working as it should

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#271]
# ALNAP to review
http://alnap-dev.mrmdev.co.uk/events/annual-meetings/event-rss-test
- [x] Should display one team member at a time in slideshow

**Comment by russ-manta** [comment]
@Maria-alnap see http://alnap-dev.mrmdev.co.uk/events/annual-meetings/event-rss-test

**Comment by angievanhegan** [comment]
@Maria-alnap this is ready to review. Thanks

**Comment by Maria-alnap** [comment]
Great! I'll move to done
