### ISSUE TITLE
Browser QA issues

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#272]
Firefox

Homepage: 
- [x] Placeholder text on help library block getting cut off
- [x] Promo styling: Button is on two lines, text doesn’t always look right
- [x] Newsletter button in footer in out of line
- [x] Select language arrow in top menu style broken
- [x] Menu font is too bold
- [x] When you hover on help library the gap between the text and icon disappears

Event:
- [x] Spacing of RHS blocks related/recommended
- [x] Margins for multiple logos

Blogs search page:
- [x] Sort by filter styling broken
- [x] When I search in the keywords, the search button becomes temporarily see through?

Jobs 
- [x] Remove tags

About page:
- [x] Is doing that jumpy thing when you hover on box links (on what we do)

Person:
- [x] Title shows twice (remove from white bio section)

Logging in has made the social icons in the header look weird

—
Safari

Help library:
- [x] Submit a resource button is out of vertical align
- [x] Contributor filter needs styling
- [x] Date filter: calendar text is a bit big, month/year getting cut off
- [x] PORTALS WHERE THEY AT?
___

Explorer 11 (browser stack)

- [x] Remove auto on SVG
- [x] Select styles for IE
- [x] Help library menu (I had to use fix position, otherwise the IE hack breaks the menu)

Help library:
- [x] Filter arrows styling broken

Header:
- [x] Select styling broken

Blog landing page:
- [x] Idea for blog icon cutting into text

Search pages
- [x] Spacing below filters is very big

—

iPhone (SE) & Android (Axon)

Header
- [x] (Portrait) register/login buttons need spacing
- [x] On mobile and tablet the menu is preventing users from being able to click on the logo to go home
- [x] On mobile and tablet the menu and border bottom change the position when is expanded

Homepage
- [x] (Portrait) Strengthening humanitarian action text too close to right side of screen
- [x] Member tag not styled on news?
- [x] Promo text is all wonky (cause its in a wysiwyg?

Help library
- [x] List/block display is overlapping filter box
- [x] Advanced search options plus icon is oval instead of circle ???
- [x] filter text is cutting into drop down arrow
- [x] Expanded filter box is an overlapping mess, can’t see some of the filter options

Topics
- [x] (Portrait) not sure about jump links styling

Events:
- [x] Date is displaying twice on card

Jobs/events/resources:
- [x] (Portrait) Details too squished?

Contact us:
- [x] (Portrait) map getting cut off

—

iPhone (SE)

Contact us:
- [x] (Portrait) Wysiwyg details box not working well

Help library
- [x] (Portrait) on card the type tag is overlapping white box

—

Android (Axon):

Contact us:
- [x] A: wysiwyg out of line
—

iPad (someone double check these, my iPad might have been acting up!)

Homepage:
- [x] (L) Share icons in header are overlapping logo ( think because of the cart icon?)
- [x] Twitter arrow controls are out of line with dots
- [x] (L) footer is displaying single block above another, does it need to at this width?
- [x] (P) title of resource is touching edge of card/getting cut off, maybe font should be smaller?

Help library page 
- [x] Position of blocks is overlapping help library logo
- [x] Advanced search options block is a mess
- [ ] Resource cards should be 2 across at this width

Search pages
- [x] There’s a white bar above search options?
- [x] Filters don’t fit inside expanded search options white box (Double check on real device)

Events search page
- [x] (P) third wysiwyg button is out of line with the others

News/Jobs/members search page
- [x] Filters aren’t appearing

Share buttons
- [x] Appearing at the top and pushing the title/content down the page, shouldn’t it show at the bottom instead?? >>> (No flexbox on iPad...)

Tbh when iPad is landscape seems like the second sidebar could fit in on the right, but it shows underneath (like on mobile) and it leaves loads of empty space next to it

Sign up buttons need actual links

Read text field is inconsistent, sometimes at top of page sometimes at bottom

Edit forms: postscript - content curation grouping box shows even when there’s no nuggets for it

**Comment by russ-manta** [comment]
@pipemanta can you help @cutlern with these ones please?

**Comment by meldera** [comment]
About the "List/block display is overlapping filter box"... This trigger and functionality is not needed on mobile, is it?..

**Comment by cutlern** [comment]
@meldera well it only works when my phone is landscape, so i guess i'd agree?

**Comment by pipemanta** [comment]
It wasn't possible to fix the position of the Share buttons on iPad, there is not flexbox for iPad...

**Comment by russ-manta** [comment]
@pipemanta is there anything left here?
