### ISSUE TITLE
Topics page - more text to display alongside hero image

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#277]
### Related to
#191 

---
### Done criteria
- [x] The portion of text showing up next to the hero image needs to show at least 3 rows when it's collapsed [currently shows 1](http://alnap-dev.mrmdev.co.uk/our-topics/the-state-of-the-humanitarian-system)

---
### ALNAP to check
[currently shows 1](http://alnap-dev.mrmdev.co.uk/our-topics/the-state-of-the-humanitarian-system)
- [ ] 3 lines of text appear

**Comment by angievanhegan** [comment]
@Maria-alnap FYI
@russ-manta Is it ok to add this issue to this epic? Also, please can you estimate it? Thanks

**Comment by russ-manta** [comment]
@dilwarhussain can you take a look at this please?

**Comment by Maria-alnap** [comment]
@russ-manta this is looking better. May I ask what is the criteria for the number of rows showing up? Some look great and aligned to the photo, others still don't. Can we make it so that all text boxes next to photos in heroes in topic pages align to the photos?
