### ISSUE TITLE
Resource page - organisation data appearing below main box

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#278]
### Done criteria
- [x] Organisation data appearing on white box as per [design](https://invis.io/ANC0GIX8Q)

---
### ALNAP to check
- [ ] content appearing as per design

![screen shot 2017-10-02 at 10 05 19](https://user-images.githubusercontent.com/3796718/31084468-7b997c62-a762-11e7-9cd7-417f029f511b.png)

**Comment by angievanhegan** [comment]
@russ-manta I'm assuming this is ok to put in the pre-launch epic. Can you review and estimate please? Thanks

**Comment by russ-manta** [comment]
@Maria-alnap see here as an example: http://alnap-dev.mrmdev.co.uk/help-library/evaluation-of-the-peace-and-national-recovery-project-519-0394-el-salvador

**Comment by Maria-alnap** [comment]
@russ-manta, Looking good now, will move to done.
