### ISSUE TITLE
Resource page - more button needs two click to expand

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#279]
### Done criteria
- [x] Ensure 'More' button on resource page only needs one click to expand

---
### ALNAP to check
- [x] More button works as expected

**Comment by angievanhegan** [comment]
@russ-manta A new bug to size. I'm waiting on Tim to confirm the browser he's using. Thanks

**Comment by meldera** [comment]
Would be useful to know, as I was not able to reproduce this...

**Comment by russ-manta** [comment]
@arseni timharcourtpowell [< 1 minute ago] 
Just tried it again - the one on the homepage seems to work on first click, but the panels one is still two clicks on this page: http://alnap-dev.mrmdev.co.uk/events/annual-meetings/31st-annual-meeting-changing-humanitarian-action

**Comment by russ-manta** [comment]
@meldera just tested - still needs two clicks from me

**Comment by meldera** [comment]
Some JS changes were overwritten since yesterday. Now fixed again...

**Comment by Maria-alnap** [comment]
This is ok now. Will move to done.
