### ISSUE TITLE
Hashtag for event content types is not showing up

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#280]
Hashtag for event content types is not showing up despite us populating the field
### Done criteria
- [x] Hashtag for event content types shows up (http://alnap-dev.mrmdev.co.uk/events/annual-meetings/annual-meeting-test-2)
---
### ALNAP to check
- [ ] Works as expected

**Comment by angievanhegan** [comment]
@russ-manta New bug for you to estimate. 
@Maria-alnap Please can you add a little more detail in the description at the top? Thanks

**Comment by Maria-alnap** [comment]
@nadia847 @russ-manta I can confirm that despite removing the hashtag, the twitter feed is not showing up. We've used that hashtag last in July. Was the import of tweets done after that?

**Comment by nadia847** [comment]
@Maria-alnap the tweets were imported on the 17th of august (from what I can see here: http://alnap-dev.mrmdev.co.uk/admin/tweets). Those are the earliest ones we have.

**Comment by russ-manta** [comment]
@dilwarhussain can you take a look at this one please?

**Comment by Maria-alnap** [comment]
@nadia847 this makes sense, thanks for clarifying! Will move to done
