### ISSUE TITLE
Searches should be closed by default

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#281]
Request from Steve:
### Done criteria
- [x] [HELP library](http://alnap-dev.mrmdev.co.uk/help-library) closed by default
- [x] [Events](http://alnap-dev.mrmdev.co.uk/events) closed by default
- [x] [News](http://alnap-dev.mrmdev.co.uk/news)
- [x] [Blogs](http://alnap-dev.mrmdev.co.uk/blogs)
- [x] [Jobs](http://alnap-dev.mrmdev.co.uk/jobs)
- [x] All searches dropdowns retain the same open/closed position when navigating away/back from/to them
- [x] All search dropdowns work independently of each other
---
### ALNAP to check
- [x] [HELP library](http://alnap-dev.mrmdev.co.uk/help-library) closed by default
- [ ] [Events](http://alnap-dev.mrmdev.co.uk/events) closed by default
- [ ] [News](http://alnap-dev.mrmdev.co.uk/news) closed by default
- [ ] [Blogs](http://alnap-dev.mrmdev.co.uk/blogs) closed by default
- [ ] [Jobs](http://alnap-dev.mrmdev.co.uk/jobs) closed by default

**Comment by angievanhegan** [comment]
@ican-icant Should it only be closed by default the first time the users sees it, then it should stay in whatever state they set it to? Thanks

@Maria-alnap FYI

**Comment by ican-icant** [comment]
It remembers what you last did, ie. left it open / had it closed. That's fine, but it should not function this way across all the search boxes. So if you leave it open for news it should not open the search by default for events of the library. They should open / close independantly. Make sense @angievanhegan ?

**Comment by angievanhegan** [comment]
@ican-icant yeah - I've updated the done criteria. ta

**Comment by russ-manta** [comment]
@meldera can you take a look at this one please?

**Comment by Maria-alnap** [comment]
@russ-manta Apologies, what am I meant to be checking here? I tried with a search in events but when I go back it doesn't go to the search results...
