### ISSUE TITLE
Resource content type changes

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#282]
### Done criteria
- [x] Change display of resources that have video/media so videos display above white box
- [x] Display link field in white box with other fields
- [x] Check for missing resource file imports eg. http://www.alnap.org/admin/resource/edit.aspx?id=5239 & http://alnap-dev.mrmdev.co.uk/help-library/responding-to-earthquakes-learning-from-earthquake-relief-and-recovery-operations - it seems underscores and uppercase are converted to dashes and lowercase in the db. Will compare and then possibly rename all files.  Need to create a shell script that copies only files with uppercase to the same filename with lowecase.

---
### Designs
- [ ] Resources with video/media https://projects.invisionapp.com/d/main#/console/10292473/236978898/preview

---
### ALNAP to check
- [x] Videos display at the top of resources where present eg. http://alnap-dev.mrmdev.co.uk/help-library/setting-the-scene-simon-maxwell-introduces-state-of-humanitarian-system-report
- [x] If resource Link URL field is populated it displays within the white box on the page

**Comment by Maria-alnap** [comment]
All good with this. Will move to done :)
