### ISSUE TITLE
Make featured content autocomplete in subtopic paragraph wider

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#283]
### Done criteria
- [ ] Make featured content autocomplete in subtopic paragraph wider, see image below eg. http://alnap-dev.mrmdev.co.uk/node/32809/edit

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
<img width="840" alt="box not wide enough" src="https://user-images.githubusercontent.com/25846670/31184163-8f8ef886-a920-11e7-886d-7c304bb1a1e7.png">

**Comment by meldera** [comment]
This has been done already. Forgot to move it..

**Comment by Maria-alnap** [comment]
This is so helpful! Thanks. Will move to done :)
