### ISSUE TITLE
Menu items/Nav missing when viewing a news node

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#284]
### Done criteria
- [x] Menu items/Nav missing when viewing a news node: http://alnap-dev.mrmdev.co.uk/news/the-sohs-2018-survey-is-out

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [x] ?
- [x] ?

**Comment by meldera** [comment]
It is there. This is a styling issue.

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan checked and it's looking good now!
