### ISSUE TITLE
Ability to add timezone to events, needs new field

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#285]
### Done criteria
- [ ] Ability to add timezone to events, needs new field 'Format for timezone should be GMT, GMT+1, etc.'  Possibly use https://www.drupal.org/project/tzfield
- [ ] Should be visible within the white box on an event

---
### ALNAP to check
- [ ] Timezone is selectable using the GMT field on events
- [ ] Timezone is visible after the date/time when viewing an event

**Comment by meldera** [comment]
Already commented on this somewhere  -  date field setting provide this functionality.

**Comment by russ-manta** [comment]
@cutlern can you look at this one please?  ALNAP need to be able to show the timezone of an event on the content in the white box I think: http://alnap-dev.mrmdev.co.uk/events/3rd-asop-conference  we need a new field on Events that will show this, some kind of list they can choose from with eg GMT, GMT+1 etc
