### ISSUE TITLE
Resource series title

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#287]
### Done criteria
- [ ] Display title of resource series node in the view instead of just 'Resource series' eg. here: http://alnap-dev.mrmdev.co.uk/help-library/sohs-2015-launches-is-the-system-broken

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@meldera another one for you..

**Comment by meldera** [comment]
This needs to be a field view to show the series title, not a teaser view.
