### ISSUE TITLE
(#201) Modify resource content type

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#29]
Dependent on #4

### Done criteria
- [x] Add a custom card authors field which displays only if has content
- [x] If card authors field empty, display the regular authors truncated after a few characters.
- [x] NEW remove agencies taxonomy from content type once organisations are working correctly (depends #245)
- [x] Modify resource content type to user field_member organisation entity reference field.
- [x] Make certain resources for logged in members only (done using resource content type template)
- [x] Get organisation for user when submitting resource (civi contact from user id-> then related civi organisation - > Drupal organisation entity id using rule) and populate the Organisation entity ref field
- [x] Add Contributor field for Member/ALNAP resources
- [x] ISSUE: [Maria] cannot see the Bookmark resource button
---
### Designs
https://invis.io/ANC0GIX8Q

---

### ALNAP review criteria
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
We can't progress this until we've got a copy of the source data. @russ-manta sent a link to ALNAP. @melkers may have saved a copy of the network.

**Comment by melkers** [comment]
@russ-manta to review data source and advise Nelle of changes to content model.

**Comment by nadia847** [comment]
@dave-manta From onenote

_Taxonomies_
- Agency - is this a better name than "Members"?
- Topics
- Regions
- Type - in content model

They want to be able to filter by alnap/member

**Comment by nadia847** [comment]
All non-ALNAP resources need to display the organisation on the card and node 
 
For ALNAP resources, display the author(s) on cards. Either 1 x author et al or 2 x authors. Authors can be a text field

**Comment by russ-manta** [comment]
@Maria-alnap Maria, we've just been looking at related resources and we're wondering if you relate one resource to another does the relationship always  work both ways?
For example here: http://www.alnap.org/resource/6950 the resource 6947 (spillovers) is shown and id I then go here http://www.alnap.org/resource/6947 the corresponding resource 6950 (pathfinders) is shown.  Is it always like this or is it possible that sometime the relationship only works 1 way?

**Comment by Maria-alnap** [comment]
Hi @russ-manta ,

This is done manually so it's not always consistent.

We'd be happy to be flexible with this (either try a new workflow or continue doing it as we have so far).

Hope this helps!

**Comment by russ-manta** [comment]
Thanks @Maria-alnap . Also for the location on resources do you use region/continent at all or is Country only sufficient?

**Comment by Maria-alnap** [comment]
@russ-manta we need both, region and country. Thanks!

**Comment by russ-manta** [comment]
@Maria-alnap where is the region used/displayed on the site?

**Comment by russ-manta** [comment]
@Maria-alnap ah just seen, resources search

**Comment by russ-manta** [comment]
@Maria-alnap how do you envisage the resource search filter working for region. In the design/wireframes there is a dropdown for Location - would this just list regions with the same categories (eg Eastern Africa etc) as on your current site?

**Comment by Maria-alnap** [comment]
Hi @russ-manta , yes indeed. Use the same regions as in the website, please, but also include countries within them

**Comment by russ-manta** [comment]
@Maria-alnap thanks

**Comment by russ-manta** [comment]
@Maria-alnap what's the difference between Public tags and Internal tags on resources?  Are internal tags required for the new site?

**Comment by Maria-alnap** [comment]
@russ-manta internal tags are metadata. It would be good to discuss this further, as I'm unsure to what extend we'll need them in the same shape/form that they're now. Can we add this to our upcoming catch up with Angie?

**Comment by russ-manta** [comment]
@Maria-alnap sure let's discuss it then

**Comment by russ-manta** [comment]
@Maria-alnap for existing resources on your current site is there any way to tell who submitted the resource?

**Comment by Maria-alnap** [comment]
@russ-manta We can't do that from the backend but I think Phil can. Would you like me to ask him, copying you?

**Comment by russ-manta** [comment]
@Maria-alnap I can see the info in your database. The question is really if you need that info?  It's an extra step in the import.  For any new resources created we will automatically have the creator/owner info on the resource but do we need to import it for previous resources?

**Comment by Maria-alnap** [comment]
@russ-manta we don't really need to import that, don't worry

**Comment by angievanhegan** [comment]
@russ-manta I just came across this in the backlog, it looks relevant to our sprint goal. Are there any actions here? Thanks

**Comment by russ-manta** [comment]
@angievanhegan moving to review

**Comment by angievanhegan** [comment]
@russ-manta Is there anything for Maria to check here, or can it move to done this sprint? Ta

**Comment by nadia847** [comment]
@dave-manta @ican-icant atm, the authors field is a text field. And it looks like the show authors or author 1, author 2, et al (if more than two authors) still hasn't been built. The authors field is a text field which means this can't be automated.

Does this need to then be rebuilt?

**Comment by meldera** [comment]
https://mantaraymedia.slack.com/archives/C3FTH5AHW/p1497872512221167

**Comment by nadia847** [comment]
But should they be stored as varchar? @meldera. We still need to get Stave and ALNAP to sign of on this if it;s different from what is expected.



On 9 Aug 2017, at 09:32, meldera <notifications@github.com<mailto:notifications@github.com>> wrote:


https://mantaraymedia.slack.com/archives/C3FTH5AHW/p1497872512221167

**Comment by meldera** [comment]
that is the format of their imported data. nothing we can do about this, not even explode() as the strings are not consistent.

**Comment by angievanhegan** [comment]
@nadia847 to talk to @ican-icant  and @dave-manta about the request to see if that helps with a solution!

**Comment by nadia847** [comment]
@angievanhegan @meldera if their data does not support the 2 authors, et al then the following solution is proposed:

we have a custom card authors field which displays if has content

If empty, we display the regular authors truncated after a few characters. 

Sound good?

**Comment by angievanhegan** [comment]
@nadia847 Please can you add the blocker in the done criteria? Also, what's the next step for this one to unblock it? Thanks
