### ISSUE TITLE
Video not displayed on some resources

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#290]
### Done criteria
- [x] URL added to video field but video not shown: http://alnap-dev.mrmdev.co.uk/node/32827/edit , http://alnap-dev.mrmdev.co.uk/node/32826/edit

### ALNAP to check
- [ ] Video is visible on resources http://alnap-dev.mrmdev.co.uk/node/32827 , http://alnap-dev.mrmdev.co.uk/node/32826

**Comment by Maria-alnap** [comment]
All good with this now. Will move to done
