### ISSUE TITLE
Reduce spacing between nuggets within rendered content

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#291]
### Done criteria
- [ ] 'another thing we've seen is that the spacing between nuggets within content types in general is quite substantial (e.g. between videos and content blocks' http://alnap-dev.mrmdev.co.uk/events/webinar-flying-blind-gathering-and-using-quality-information-in-situations-of-constrained 'between content blocks themselves in blog posts' http://alnap-dev.mrmdev.co.uk/blogs/a-job-well-done-is-the-best-possible-humanitarian-motivation 'Any chance this could be reduced?'

---
### ALNAP to check
- [ ] Nugget spacing on viewed page is as expected

**Comment by Maria-alnap** [comment]
This looks great now, thanks! I'll move to done
