### ISSUE TITLE
Resource redirects

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#292]
We need to create redirects from all imported resources from their old url eg resource/id
http://www.alnap.org/resource/22855 to the new url in drupal
---
### Done criteria
- [x] Create process for creating redirects
- [x] Create redirects

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by meldera** [comment]
should be imported after resources
