### ISSUE TITLE
Build portals landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#296]
### Done criteria
- [x] Page built according to design
- [x] Page is dynamically populated (with the same content as appears on the HELP library landing page)
- [x] Page appears as a secondary nav item within HELP library
- [x] ALNAP are able to edit the top box
- [x] Add all the portal links for Urban, Syria, Principled and ECB and point to the live urls

---
### Designs
- [Portal landing page](https://drive.google.com/open?id=1GzcOWi3ifwLRPZ3ZuLVlCnC-mFakXxWLiA8ZlYSNwik)

---
### ALNAP to check
- [x] Design is correct
- [x] Content is correct
- [x] Top box can be edited
see: http://alnap-dev.mrmdev.co.uk/help-library/portals

**Comment by angievanhegan** [comment]
@Maria-alnap @russ-manta @ican-icant This is the issue for the new portal page. Please can you all check the done criteria are correct and I've not missed anything. Thanks

**Comment by russ-manta** [comment]
@cutlern can you add all the portal links for the live portal urls so they point to the old sites.
http://www.urban-response.org/
http://www.syrialearning.org/
http://www.principlesinpractice.info/
http://www.ecbproject.org/

**Comment by russ-manta** [comment]
@Maria-alnap logos and some text above need adding for the portals: http://alnap-dev.mrmdev.co.uk/help-library/portals

**Comment by Maria-alnap** [comment]
All good. Will add those later in the week.
