### ISSUE TITLE
Recommended resources order on mobile

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#297]
### Done criteria
- [x] ISSUE: Recommended resources should appear after Download resource (sidebar) on mobile

### ALNAP to check
- [ ] Recommended resources should appear after Download resource (sidebar) on mobile

**Comment by Maria-alnap** [comment]
@nadia847 the download button is not showing up on mobile, at least on this resource that I tried: http://alnap-dev.mrmdev.co.uk/help-library/responding-to-earthquakes-learning-from-earthquake-relief-and-recovery-operations

**Comment by nadia847** [comment]
@Maria-alnap http://alnap-dev.mrmdev.co.uk/node/27395/edit this one has a file uploaded on Files > Main report files

As does http://alnap-dev.mrmdev.co.uk/node/32571/edit

The one you sent does not. The download button and cover are automatically generated from the Main report file field.
