### ISSUE TITLE
Topics page responsiveness

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#298]
This page looks a bit odd in firefox 55.0.3
http://alnap-dev.mrmdev.co.uk/our-topics/coordination

---
### ALNAP to check
- [x] Tim to check - Responsiveness issue resolved

**Comment by russ-manta** [comment]
![1](https://user-images.githubusercontent.com/25846670/31548281-48384c18-b022-11e7-9706-633db2eec7f2.png)

**Comment by Maria-alnap** [comment]
All looking good!
