### ISSUE TITLE
(#210) Build & theme  event content type

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#30]
### Dependencies
- [x] BLOCKER: Twitter integration bug fix #126 

### Done criteria
- [x] Find out what ALNAP modifications are
- [x] Add hashtag field
- [x] Replicate tweets by hashtag view from Research topics
- [x] includes taxonomy (we need to clarify what's needed here)
- [x]  Share icons
- [x] Node details view
- [x] ISSUE: Node details view should say Organisation not Member
- [x] Need to modify the 'register' text on the button (consult with client) (it may be to more info or to a registration link)
- [x] Link field styling
- [x] Register link field styling
- [x] ISSUE: Register link Broken
- [x] Member orgs view
- [x] Contact info view
- [x] Split overview fields into Overview and Details tabs
- [x] Add note to location field to recommend format [city, country]
- [x] ISSUE: need Annual meeting taxonomy field: [Yes / No] so ALNAP can mark out as an ALNAP Annual meeting that will then go on the Annual meeting page
- [x] ISSUE: Need menu position rules for regular events [No] in the Annual meetings page and another for Annual meetings so they can go under the proper landing page.
- [x] ISSUE: Need to split locations fields into Card location (only displays on card) And full location; address view displays in RHS sidebar as in design.

- [x] ISSUE: iframes are way too big see http://alnap-dev.mrmdev.co.uk/upcoming-events/3rd-asop-conference - .fluid-width-video-wrapper should use pk and not & for the height value inserted in iframe nugget
- [x] ISSUE: need to modify the 'register' text on the button (consult with client) (it may be to more info or to a registration link)
- [x] ISSUE: Add checkbox to hide sidebar for event (for all events)
- [x] ISSUE: Add checkbox to hide event details white box (for all events)
- [x] ISSUE: Add subtopics nugget to event content type in the relevant region (style if needed), relabel nugget if needed on content type
- [x] ISSUE: Sub topic links only seem to appear in the hero

### Events coverage done criteria
The events page will also be used to show the content for past events. Content may include any of the following: 
- [x] audio of the panel discussions
- [x] YouTube playlist (opening panel, keynote speech, ted talk style presentations)
- [x] links to reports released or featured at the event
- [x] Storify (iFrame?]
- [x] BLOCKER: Twitter feed 

### Annual meeting content
- [ ] Add table in content block nugget to demo
- [x] New vocab called "annual meetings" (with two terms - "yes" and "no") to be used to place annual meetings with the correct crumb location and those that are not annual meetings to be placed within Events search

---
### Designs
- [Events node wide](https://invis.io/J4C0FZGGS)
- [Event coverage](https://invis.io/MTC3CTGWC)

### ALNAP to check
- [x] Events match design
- [x] Can add subtopics to annual events and header appears in correct place
- [x] Can add:
  - [x] New events
  - [x] audio of the panel discussions
  - [x] YouTube playlist (opening panel, keynote speech, ted talk style presentations)
  - [x] links to reports released or featured at the event
  - [x] Storify (iFrame?]
  - [x] Twitter feed (using hashtag field)
  - [x] Timetables / event schedules

**Comment by dave-manta** [comment]
@dilwarhussain are you working on this?

**Comment by angievanhegan** [comment]
@dilwarhussain I think we could come back to this when we theme it and ask Maria to review it. I'll make sure there's an issue for theming this content type and add a note there. I'll remove it from the requirements here. Thanks.

**Comment by nadia847** [comment]
@Maria-alnap On the events content type you have a basic text field for event location which ideally should have no more than City, Country in it as it displays on event cards. This seems to be inline with how events are handled on your current site.

In the events node design (https://invis.io/J4C0FZGGS) you have a box on the right which looks like it has a bit more detail. 

Does this need to look as it is in the design or should the short location go into node details view?

You would be able to use a custom content block to add to the right if you have more detailed information on location if you wanted buy then you would have Location details on the page twice...

**Comment by Maria-alnap** [comment]
@nadia847 The location detail is actually quite important because it's very likely the name of the venue and the address. That needs to go on the event page. For the corresponding cards, it would be OK to just show city and country. Hope this makes sense?

**Comment by nadia847** [comment]
@Maria-alnap yes it's ready for you to look at :o). Reassigning it back to you.

**Comment by Maria-alnap** [comment]
@nadia847 Happy to check this but I'm not sure what I should be signing off, as I cannot find anything from the boxes at the top in this page (which is what I'm assuming this issue is about):
http://alnap-dev.mrmdev.co.uk/upcoming-events/annual-meeting-of-the-german-society-of-tropical-medicine

**Comment by nadia847** [comment]
@Maria-alnap sorry this one isn't quite ready for you yet but will be once we reinstate twitter.

What needs to be signed off here is that you have everything you need from your events content type and that it looks how it should

**Comment by Maria-alnap** [comment]
@nadia847 this looks good and works. It's just us who will need to crack how we manage all the info that needs to go into these pages. 
May be a good exercise for an upcoming training session, @matty-manta ?

**Comment by angievanhegan** [comment]
@russ-manta I'm working on the assumption that we're making this content type work for AGMs too. Is this ready for ALNAP review? The done criteria under the 'Annual meeting content' heading of 'Add table in content block nugget to demo' is not marked as done. 

Also, are you happy we've got all the requirements for the AGM pages?

**Comment by russ-manta** [comment]
@angievanhegan the other card #144 had some new issues from ALNAP which I've moved over here and am checking off now

**Comment by angievanhegan** [comment]
@russ-manta from Tim (in Slack)

I'm having a couple of issues with the new functionality on the annual meeting pages - (see here: http://alnap-dev.mrmdev.co.uk/node/19980/revisions/19981/view): the sub topic links only seem to appear in the hero, which is placed above the main title of the page. Am I doing something wrong?

**Comment by russ-manta** [comment]
@Maria-alnap I've asked the following question to tim in slack about this but here is that message:

just been looking at this. For the content above what would you prefer:
1) Keep the hero as is but make the heading slightly larger and remove the duplicate heading/image/share icons beneath
2) move the hero and links beneath the existing event header/image/share icons (and remove the hero header)  
3) something else

**Comment by Maria-alnap** [comment]
@russ-manta we would like to go with option 1, please. Thanks!

**Comment by russ-manta** [comment]
@Maria-alnap no problem
@cutlern can you add a checkbox to hide the title/image/share and then change the view so that the hero title is an H1 and has the same treatment as other event titles

**Comment by russ-manta** [comment]
@cutlern is this one now ready for review?

**Comment by cutlern** [comment]
@russ-manta Don't think so, i only assigned it to you so that it wouldn't get lost while i was on holiday

**Comment by russ-manta** [comment]
@dilwarhussain for the event content type can you add a checkbox to hide the title/image/share and then change the view so that the hero title is an H1 and has the same treatment as other event titles - Nelle knows about this so please ask her/me if not clear. This is an example page where this needs to work: http://alnap-dev.mrmdev.co.uk/events/annual-meetings/28th-annual-meeting-evidence-and-knowledge-in-humanitarian-action-0

**Comment by dilwarhussain** [comment]
@russ-manta Can you test this for me please. There needs to be something in the hero for the title to sit above it. Thanks.

**Comment by Maria-alnap** [comment]
All working well on these pages now. I'll move to done

**Comment by dilwarhussain** [comment]
Hi @Maria-alnap 
To get this working with the sub-topics, you need to check all three of the checkboxes in the sub-topics tab, 'Hide title' 'Hide RHS' and 'Hide details' and if you're happy with the changes you need to publish that node using the 'Revision' tab.

Here's a link to the same annual event on the dev site with the checkboxes checked for you to have a look.

**Comment by Maria-alnap** [comment]
@dilwarhussain thanks! All clear now 👍
