### ISSUE TITLE
Shopping cart icon and placement

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#304]
Shopping cart icon needs checking and putting in the best location on the site.
### Done criteria
- [x] Design created
- [x] Theming to match design
- [ ] Move to live

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@cat-manta can you take a look at the ALNAP site with Steve and work out the best positioning for the shopping cart?  Thanks http://alnap-dev.mrmdev.co.uk/

**Comment by cat-manta** [comment]
@russ-manta Here's where the new icon is:
Files/PROJECTS/ALNAP website and CRM - 526/Design/Assets/basket.svg

It's fine where it is, it just needs to be centred like the social media icons.

**Comment by russ-manta** [comment]
@cat-manta Thanks 
@cutlern can you style the shopping cart icon accordingly please?

**Comment by russ-manta** [comment]
@pipemanta can you check what needs doing here with nelle?
