### ISSUE TITLE
Build (modify) News content type

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#31]
Design https://invis.io/K3C0H5DZF

Content type additional fields: 
- [ ] NOT REQUIRED Contributor taxonomy  values are ALNAP, Member
- [ ] NOT REQUIRED Member(s) entity reference

linked to #34 and #32

**Comment by melkers** [comment]
Awaiting on answers to linked card

**Comment by angievanhegan** [comment]
@melkers Sorry, you'll need to clarify the client question for me on this one too. I suspect they're obvious :o(

**Comment by melkers** [comment]
Questions for ALNAP:

News items are tagged as either ALNAP or Member. For those that are tagged as Member:
1. Should they be linked to one or more specific members? And if so

a) Should those members be displayed on the node (page) and if so (b) Should there logos be used
c) Should the names of the member(s) be displayed on the cards in the news list view?
d) Should we add a search field on the news search page for users to see a drop down of the names of all Members that have a news. Clicking one would filter results for just that Member's news.  Another way to achieve this is to just use the text search which would also pick up the member's news, but of course would find other news that they may be mentioned in which they are not necessarily the 'source' of.

**Comment by dave-manta** [comment]
Answer is to get rid of of ALNAP / Member tag so all the questions above are not relevant.

**Comment by angievanhegan** [comment]
ALNAP said they don't actually need a search. Unless we think they should have one for consistency,  it can go.

**Comment by dave-manta** [comment]
@angievanhegan I believe they wanted a text search - see #32

**Comment by dilwarhussain** [comment]
@dave-manta With the removal of the member/ALNAP tag, the 'News article' content type doesn't need to be modified anymore, is that correct?

**Comment by dave-manta** [comment]
@dilwarhussain I believe so.

**Comment by angievanhegan** [comment]
@russ-manta I think this is with you for review/sign off

**Comment by dilwarhussain** [comment]
@dave-manta @russ-manta I had to add the 'Member' entity reference back so we can show all referenced news on the Member node.

**Comment by dave-manta** [comment]
@dilwarhussain please check this with @russ-manta
