### ISSUE TITLE
Blog node blog author image

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/alnap#310]
On the blog node, the design for the blog author on the RHS has a smaller landscape image with curved bottom right corner.

http://alnap-dev.mrmdev.co.uk/blogs/a-thought-for-world-humanitarian-day

### Done criteria
- [ ] Add new image field for profile image
- [ ] Add cropper to user image field
- [ ] Change image style for view on blog node and also on user profile page
- [ ] Copy existing user pictures for blog authors to the new field
- [ ] Hide the user picture field from users when logged in so they can't upload/edit

---
### Designs
- [ ] https://projects.invisionapp.com/d/main#/console/10292473/232387428/preview

**Comment by russ-manta** [comment]
@dilwarhussain done criteria updated

**Comment by ican-icant** [comment]
Blog authors look good on sidebar - thanks @dilwarhussain
