### ISSUE TITLE
Events blank box in RHS when contact details empty

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#313]
### Done criteria
- [ ] No blank box on RHS if content empty on Events, see screenshot below

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] No blank box on RHS if content empty on Events, see screenshot below

<img width="476" alt="events contact" src="https://user-images.githubusercontent.com/25846670/31734866-f5235d32-b437-11e7-9bc2-67bd17d22242.PNG">

**Comment by meldera** [comment]
Looks like this is fixed already: http://alnap-dev.mrmdev.co.uk/events/humanitarian-evidence-programme-whats-the-state-of-the-evidence

**Comment by Maria-alnap** [comment]
All working well here as well. I'll move to done :)
