### ISSUE TITLE
Submit resource, event etc buttons for live

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#315]
### Done criteria
- [x] Create a page called 'coming soon' or similar
- [x] Unpublish existing pages for Add a resource etc eg. http://alnap-dev.mrmdev.co.uk/help-library/add-a-resource 
- [x] Repoint all buttons/links for adding events/resource/jobs to this coming soon page eg. the buttons found here: http://alnap-ecb.mrmdev.co.uk/ , http://alnap-dev.mrmdev.co.uk/events , http://alnap-dev.mrmdev.co.uk/help-library, http://alnap-dev.mrmdev.co.uk/user etc - Portal page links are less important at this stage

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@ican-icant @dave-manta rather than removing these buttons should we just redirect them to some kind of holding page for now saying this functionality is coming soon?
eg the buttons found here: http://alnap-ecb.mrmdev.co.uk/ , http://alnap-dev.mrmdev.co.uk/events , http://alnap-dev.mrmdev.co.uk/help-library, http://alnap-dev.mrmdev.co.uk/user etc

**Comment by russ-manta** [comment]
@cutlern are these all done now?

**Comment by Maria-alnap** [comment]
@russ-manta there's no criteria to check here - how should I proceed?
