### ISSUE TITLE
Resource download button missing

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#317]
### Done criteria
- [x] Reinstate button eg here: http://alnap-dev.mrmdev.co.uk/help-library/responding-to-earthquakes-learning-from-earthquake-relief-and-recovery-operations or upload missing file

---
### Designs
- [ ]  https://projects.invisionapp.com/d/main#/console/10292473/236943102/preview
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by meldera** [comment]
Is there a file that can be downloaded?

**Comment by russ-manta** [comment]
@meldera can you reassign to me instead of closing please?  In this case it looks like this is one of the files that was in all caps before. Can you check to see if there is a similar file naem to the PDF cover and uplado the file to this resource please? http://alnap-dev.mrmdev.co.uk/node/48004/edit
