### ISSUE TITLE
Homepage large promo resource card missing fields

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#318]
### Done criteria
- [x] Can we add in author and org like other resource cards and as shown in the design
- [ ] ?

---
### Designs
- [ ] https://projects.invisionapp.com/d/main#/console/10292473/235626263/preview
- [ ] ?

---
### ALNAP to check
- [x] Can we add in author and org like other resource cards and as shown in the design

**Comment by Maria-alnap** [comment]
This is working now. Will move to done
