### ISSUE TITLE
Build News landing page (search)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#32]
Search options:
- [x] text search

Sorting options:
- [x] most recent 
- [x] A - Z 
- [x] Most popular - client hasn't asked for this, but if it's easy to do, no harm

Linked to #31 and #34

**Comment by melkers** [comment]
Blocked until the above questions are answered

**Comment by nadia847** [comment]
@dave-manta this looks OK to me except it's a custom view and not a type of nugget feed view.

That's probably fine as this is not a Remora site but just wanted to confirm that this is what you expected.

**Comment by nadia847** [comment]
the current build approach means you can't add nuggets to the news landing page (e.g. an advert, or an intro at the top etc etc) @dave-manta 

Instead I suggest we just add the filters to he existing remora all-news view?

**Comment by dave-manta** [comment]
@nadia847 I think this should be discussed with the wider dev team and Steve should be assigned to check this page, rather than me?

**Comment by dilwarhussain** [comment]
http://alnap-dev.mrmdev.co.uk/styling-checklist/news-events/news 
@nadia847 Can you wanna review this please.
