### ISSUE TITLE
Padding missing in Annual meeting event pages

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#322]
### Done criteria
- [x] Fix LH padding eg http://alnap-dev.mrmdev.co.uk/events/annual-meetings/31st-annual-meeting-changing-humanitarian-action
- [x] The jump to buttons are not showing

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [x] Fix LH padding eg http://alnap-dev.mrmdev.co.uk/events/annual-meetings/31st-annual-meeting-changing-humanitarian-action
- [x] The jump to buttons are now showing

**Comment by Maria-alnap** [comment]
All looking good here! Will move to done
