### ISSUE TITLE
Double click needed on more button

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#324]
### Done criteria
- [x] This page - http://www.alnap.org/our-topics/coordination remove requirement for double click

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [x] This page - http://www.alnap.org/our-topics/coordination remove requirement for double click
- [ ] ?

**Comment by Maria-alnap** [comment]
All looking good. Will move to done
