### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#325]
### Dependencies
- [x] Events/Past events year in red box gets smaller after you load more Fix styling issue
- [x] Members toggle view toggles both (maybe hide second toggle)
- [x] Hide internal fields in ALNAP themes for Resource, jobs and events content type
- [x] No download file on resources for multiple files, eg. http://alnap-dev.mrmdev.co.uk/node/46930/edit need to list all files
- [x] Resource update, run again tonight
- [x] Some links overflowing eg. https://www.alnap.org/membership/members/tufts-university
- [x] Check editor permissions - should not create/delete organisations (administering content allowed?)

---
### Done criteria
- [ ] ?
- [ ] ?

---
### Designs
- [ ] ?
- [ ] ?

---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by meldera** [comment]
Removed editor permission to "administer content"
