### ISSUE TITLE
Author page needs fixing - styling gone wrong

### ISSUE THREAD

**Issue by ican-icant** [MantaRayMedia/alnap#326]
http://alnap-dev.mrmdev.co.uk/users/john-mitchell

**Comment by dilwarhussain** [comment]
@ican-icant Fixed on dev: http://alnap-dev.mrmdev.co.uk/users/john-mitchell
Will also be fixed on live when we roll out our styling changes to live later today.

**Comment by russ-manta** [comment]
@ican-icant can you review and then assign to pipe/arseni to put live
