### ISSUE TITLE
Steve's bugs and issues

### ISSUE THREAD

**Issue by ican-icant** [MantaRayMedia/alnap#327]
- [x] Site speed: Seems a little slow - ARSENI
- [x] Creating an account: Image upload is on password page which is silly - let's move to details page plus the crop feature is confusing,. It does not explicitly say you need to edit your image, which is should.  - DAVE
- [x]  It may be a content issue; but when I click the register button there is no info on what I'm registering for... [http://alnap-dev.mrmdev.co.uk/user/register] - ALNAP to provide content.

- [x]  Search button in odd place - search panel / content type filter and button should be in a better alignment [http://alnap-dev.mrmdev.co.uk/search?keywords=albania]
- [x]  Members: Reduce gap between search members and Full members
![image.png](https://images.zenhubusercontent.com/598c61aff8b79f8376e2a502/addcdde7-f2b4-4f38-a715-77088cb4c995)
- [x]  When loading more events [http://alnap-dev.mrmdev.co.uk/upcoming-events] an additional November panel appears!
- [x] Event text search isn't working - maybe need to run cron to index recent events (i searched on redr that do lots of events and got zilch)
- [x] Lots of dummy content in past events http://alnap-dev.mrmdev.co.uk/events/past-events
- [x] Actually think text search isn't working on all content types - News, Blogs, Events etc.
- [x] Videos [https://www.alnap.org/help-library/animation-how-can-we-change-humanitarian-action] have not used the design / there has been no discussion why this has not been used https://projects.invisionapp.com/d/main#/console/10292473/236978898/preview
- [x] HELP LIBRARY icon disappears on hover (only when user on the help library landing page)
- [x] On home; BLOG authors has no separating ',' See in hero Why should I care about eval...
- [x] There are very few member only resources - but this one I found is NOT displaying the member only tag on the card [http://bit.ly/2yW0Sjh]. It displays it on the node only.

**Comment by russ-manta** [comment]
@meldera can you look at these with @pipemanta if needed please?
