### ISSUE TITLE
Dummy text on card hover

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#333]
See "why ALNAP?" card here: https://www.alnap.org/about under "who we are"

**Comment by matty-manta** [comment]
Cards are displaying summaries from other languages when you remove the english summary text.

Eg:

https://i.imgur.com/V9Xq4Gt.png

displays on box link on this page:

http://alnap-dev.mrmdev.co.uk/about

From this node:

http://alnap-dev.mrmdev.co.uk/why-alnap
