### ISSUE TITLE
Retain search results when returning to search after viewing a resource

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#336]
#Maria believes that the journey people will take is to go to search, enter search criteria, select one resource from the results, review it, then go back to the search - where they'd like to see the previous search results. 

---
### Done criteria
- [x] Add pagination to search results and remove 'load more' button
- [x] Ensure search still works ok
- [x] User can select an item from the search results then use the 'back' button and see the same search results again
- [x] Same behaviour on events
- [x] Same behaviour on news
- [x] Same behaviour on blogs
- [x] Same behaviour on jobs

### ALNAP done criteria
- [x] Add pagination to search results and remove 'load more' button
- [x] Ensure search still works ok
- [x] User can select an item from the search results then use the 'back' button and see the same search results again
- [x] Same behaviour on events
- [x] Same behaviour on news
- [x] Same behaviour on blogs
- [x] Same behaviour on jobs

**Comment by angievanhegan** [comment]
@Maria-alnap Please can you confirm I've captured this correctly before I ask Arseni to estimate it? Also, can you confirm which searches it should relate to? Thanks very much

**Comment by Maria-alnap** [comment]
@angievanhegan This is what we need, thanks!

**Comment by angievanhegan** [comment]
Hi @meldera - please could you estimate how long this might take. It's important for @Maria-alnap  and we might need to prioritise it over other issues. Thank you.

**Comment by angievanhegan** [comment]
From Arseni: this is a relatively quick one, but would require ditching "load more" button in favour of a regular pager

**Comment by angievanhegan** [comment]
@meldera so all the results relevant to the search request would load, which might slow down the delivery of the search results? How many points would it be to do it if:

1. we lose the 'load more' button
2. we don't lose the 'load more' button

Thanks

**Comment by meldera** [comment]
I'd estimate a couple to a few hours. #2 is not an option.

**Comment by angievanhegan** [comment]
@meldera so if Maria really doesn't want to lose the 'load more' button, are there any alternatives?
 Such as having a list of pages of search results?

**Comment by meldera** [comment]
this can be tested on alnap-dev.mrmdev2.co.uk (same login details as live site)

**Comment by Maria-alnap** [comment]
@nadia847 @russ-manta this looks like it has been sorted?

**Comment by russ-manta** [comment]
@Maria-alnap yes this is now fixed on live
