### ISSUE TITLE
Resource node edit issues

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#338]
Issues for Russ
- [x] Check why cover images are not being generated for resources by sanguinettichloe_568 - might be related to  issue 335

Issues for Arseni
- [ ] Problem when IDP/refugees tag has been chosen as the first tag – you then can’t add any other tags

**Comment by cutlern** [comment]
@nadia847 okay with the subtitle size here? http://alnap-dev.mrmdev.co.uk/help-library/how-governments-learn

**Comment by meldera** [comment]
Problem with / in tags is drupal core issue. Shall I try a patch? Or perhaps just rename the term?..

**Comment by meldera** [comment]
Covers not being generated is a server issue...

**Comment by meldera** [comment]
https://www.drupal.org/project/autocomplete_post
https://www.drupal.org/project/autocomplete_hack
