### ISSUE TITLE
(#209) Build and theme News node

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#34]
Link #30 #32 #31

### Done criteria
- [x] Check all required fields are present, add if needed
- [x] Theme to match wireframe/design
- [x] Member organisation (related) shown on RHS
---
### Designs
- [News node](https://invis.io/U4CKSQQ2W)

---
### ALNAP to check
[Example news page](http://alnap-dev.mrmdev.co.uk/news/english-accumsan-amet-cogo-fere-qui)
- [x] Page functionality matches the scope
- [x] Page matches design

**Comment by dave-manta** [comment]
@pipemanta @angievanhegan what am I supposed to do with this assingment?

**Comment by angievanhegan** [comment]
@russ-manta Can this one be assigned to @dave-manta to check? 

@pipemanta I think that @russ-manta should allocate stuff to Dave to check rather than us. Russ, let us know if you disagree. Thanks

**Comment by russ-manta** [comment]
@pipemanta @ican-icant should the member organisation be displayed on the RHS like in the wireframe(https://projects.invisionapp.com/d/#/console/10292473/235809784/preview)?  it's not on this page: http://alnap-dev.mrmdev.co.uk/news/english-accumsan-amet-cogo-fere-qui @pipemanta can you check with Steve please?

**Comment by pipemanta** [comment]
@russ-manta I have confirmed with Steve to display the organisations on the RHS

**Comment by angievanhegan** [comment]
@Maria-alnap this is ready for you to review now. Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan Thanks! I haven't ticked the second one as at the moment there's an isolated image popping up on the right side of the screen and I'm not sure what's its purpose...

**Comment by angievanhegan** [comment]
quick question for you @nadia847 - can you explain the [flower image on the  RHS](http://alnap-dev.mrmdev.co.uk/news/english-accumsan-amet-cogo-fere-qui)?  Thanks

**Comment by nadia847** [comment]
@angievanhegan it's the "logo" for "Test organisation/member"

**Comment by angievanhegan** [comment]
@Maria-alnap it's the logo! Are you happy to sign this off now? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan This is OK, but I'm a bit confused tbh, as on the website we will have News and Member updates. Will the content type for news be the same than member updates? The access in these is different and it may make sense to differentiate somehow? 

- News are about ALNAP and open access, any user coming to the site will see them. 
(These would have an ALNAP logo to the right as per this design, I assume?)

- Member updates about Members  or ourselves but only available to the Membership (hence only showing up for Members when logged in)

(We discussed this with @ican-icant and @dave-manta but I'd like to know the details on how this will be implemented)

**Comment by nadia847** [comment]
@Maria-alnap we have a separate content type (Member updates) which should be used for... updating members. news is public. Member updates private. You should already be able to see these on your account page (click on My account in the header).

Member updates are in the current sprint and in the Manta review column so we should have those available for you to test soon.

@angievanhegan

**Comment by Maria-alnap** [comment]
@nadia847 Oh apologies! And thanks for the explanation! It all makes sense now :)

I'm not sure that we'll need logos in all news items then. I assume that we'll have the option of not adding any as well?

**Comment by nadia847** [comment]
@Maria-alnap If you add a member in the Members field, the logos will appear on the right of the node.

**Comment by angievanhegan** [comment]
@MantaRayMedia/alnap Are you happy to sign this one off now? Thanks

**Comment by Maria-alnap** [comment]
@nadia847 @ican-icant I'm happy with this and will move to done
