### ISSUE TITLE
Resource node display issues

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#340]
- [x] Display subtitle above details box
- [x] Display subtitle on resource card

## ALNAP criteria
- [ ] Display subtitle above details box
- [ ] Display subtitle on resource card

**Comment by nadia847** [comment]
okay with the subtitle size here? http://alnap-dev.mrmdev.co.uk/help-library/how-governments-learn

**Comment by Maria-alnap** [comment]
Size looks okay! Looks a little odd not being as indented as the title text, perhaps. Could we shift it in a bit, or perhaps include it (as a smaller size) within the blue and orange bracket things? Also, will this display in cards, or just on the page? (Tim)

**Comment by russ-manta** [comment]
@nadia847 can you take a look at this please?

**Comment by nadia847** [comment]
@Maria-alnap 
![screen shot 2017-11-06 at 12 25 18](https://user-images.githubusercontent.com/29143619/32441057-b367bb94-c2ed-11e7-9c56-b4e2b34e3429.png)

Cat and I are both certain that the indented title looks weird and that it;s better when it's aligned with the white box below.

It should definitely not go in the brackets with the main page title especially because this title is likely to be so much longer than the page title.

The subtitle is not currently set to display in cards; did you want it to?

**Comment by Maria-alnap** [comment]
Hey @nadia847 - yeah, agreed that it looks weird! Let's go back to the white box align. And could you should us what it would look like if the subtitle did display in the cards? Additionally, would there be the option to turn it on/off for particular cards? (I guess by not adding any subtitle? Sorry - thinking out loud here!)

**Comment by nadia847** [comment]
@Maria-alnap lucky I didn't change it then :o)

This is what the strap line could look like:

![screen shot 2017-11-09 at 11 35 13](https://user-images.githubusercontent.com/29143619/32603579-249a7878-c542-11e7-82d7-216a510e7276.png)

If you wanted to turn it on/off for particular cards, you could either maybe use the card summary field for subtitles you want on cards or we could have a checkbox while allows you to toggle it.

**Comment by nadia847** [comment]
@Maria-alnap have you decided based on the screenshot above whether you want subtitles on resource cards?

**Comment by Maria-alnap** [comment]
@nadia847 please go ahead and include them. Also, it would be great if we could have an answer to the date display issue. Thanks!

**Comment by nadia847** [comment]
@Maria-alnap I'm sorry I assumed the display date issue was fixed. we're looking into this now and will get back to you!

**Comment by russ-manta** [comment]
@Maria-alnap I'm picking this up. With the date display how do you want it to work differently to the moment. At the moment it's just using the published date field and the other date fields 'Date display mode' and 'Diplay date override' are not used - do these need to work - is that the issue?

**Comment by Maria-alnap** [comment]
@russ-manta when selecting to just show month and year, for example, that is not working...
