### ISSUE TITLE
Build blog CT

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#36]
- [x] add all the fields in the content model
- [x] Blog authors field see outcome of #45
- [x] Related/taxonomy (#15)

Wireframe #56 and #39

**Comment by dilwarhussain** [comment]
http://alnap-dev.mrmdev.co.uk/admin/structure/types/manage/blog/fields

**Comment by angievanhegan** [comment]
@dilwarhussain Did you need to know the search criteria for this? They're now confirmed on #56 if you do. Otherwise, do you want to allocate it to Russ for sign off? Ta
