### ISSUE TITLE
(#202) Theme blog node

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#37]
### Dependencies
- [x] Build completed first #164 
---
### Done criteria
- [x] Theme views on RHS
- [x] Theme comment button
- [x] Theme main body content as per design
---
### Designs
- [Blog landing](https://invis.io/7CC18FLJ4)
- [Blog](https://invis.io/NJC8OGC2B)
- [Blog author](https://invis.io/SBCGDY838)
---
### ALNAP to check
[Sample blog](http://alnap-dev.mrmdev.co.uk/blogs/humanitarian-financing-where%E2%80%99s-the-system-shift)
- [x] Share icons on left look & work correctly
- [x] Main blog content looks and works correctly
- [x] Right hand side content (author and comment button) looks and works as expected

**Comment by russ-manta** [comment]
@nadia847 is the related view on the RHS themed as it should be?

**Comment by russ-manta** [comment]
see http://alnap-dev.mrmdev.co.uk/blogs/new-year-new-you-what-the-whs-can-learn-from-failed-new-years-resolutions for an example blog

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan I haven't ticked last one because I cannot see any related content at the moment. It may be that you didn't add it to this particular blog, but it would be good to see that tested :)

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta Whilst playing with uploading some blog posts, we have found a glitch with colons in headings (which is something we use quite a lot)! It seems that with some h tags these don't come up (h4,5 and 6 in the link below + screenshots attached)

http://alnap-dev.mrmdev.co.uk/blogs/humanitarian-financing-where%E2%80%99s-the-system-shift-2
![glitch02colon.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593fc96377a396001a3a210d/125516c66e82c728ace21e0d46ef989337818bf9ddeab04fab53b2d86b56357c2301a03f32dfa17de6112a5258594bae14595b12aff98929f5e06a22d95a58ffcd7f1d2598694ef1e1c84afd13b03289498fb7b98a4dc5e83420e48e87463f0c48.PNG)
![glitch01colon.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593fc96377a396001a3a210d/125516c66e82c728ace21e0d46ef989337818bf9deeab04fab53b2d86b56357c2301a03f32dfa17de6112a5258594bae14595b12aff98929f5e06a22d95a58ffcd7f1d2598694ef1e1c84afd13b032884e8fb7b98a4dc5e83420e3888e46370c48.PNG)

**Comment by nadia847** [comment]
should now be fixed @Maria-alnap

**Comment by Maria-alnap** [comment]
@nadia847 great!

**Comment by angievanhegan** [comment]
@Maria-alnap the related content feature hasn't been built yet. That's be built in a later sprint - I should have specified this just meant the author and the add comment button on the right hand side. Are you ok to sign this off now?

**Comment by Maria-alnap** [comment]
@angievanhegan ok, I understand. Yes! Consider the blog post page signed off (and I look forward to seeing the related content bit when it's ready!)

**Comment by Maria-alnap** [comment]
(Apologies @angievanhegan for not assigning these properly but I'm just dealing with them from GitHub on my phone as I won't have access to a laptop till the afternoon today!)
