### ISSUE TITLE
(#202) Build blog landing page + search

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#38]
### Done criteria

- [x] Search with filters for: Text search, Author, Organisation, Topic (Keywords), Order by date
- [x] Create link/buttons for: Idea for blog, download guidelines, Signup for updates
- [x] Switch for grid/list
- [x] Card content for blog post
- [x] combine filters for sort/order by
- [x] grid view icon highlight

- [x] ISSUES: The cards that appear after clicking on the more arrow sometimes show up cropped
- [x] ISSUES: The filters are not really working yet; Tagsthat have been added not appearing in filter (e.g. System-wide performance, which is a tag for the "one humanity, many visions" blog post)

---

### Designs
[Blog landing page](https://invis.io/7CC18FLJ4)

---

### ALNAP review criteria
- [x] Correct filters are available and work
- [x] The page looks like the design
- [x] Switch for grid/list works correctly
- [x] Cards contain the correct information
- [x] Sort works and has the required options

**Comment by nadia847** [comment]
@angievanhegan deadline? :oP was this for jobs at one point?

**Comment by angievanhegan** [comment]
@nadia847 brain fart. I have no idea why that's there. It's not anymore!

**Comment by russ-manta** [comment]
Should the card in the view be a link? , this can probably be done as part of the theming

**Comment by angievanhegan** [comment]
@russ-manta I just found this on the backlog. Is is just a dupe?

**Comment by ican-icant** [comment]
@russ-manta very minor, but the grid view icon isn't highlighted / active, which it should be.

**Comment by angievanhegan** [comment]
@russ-manta One for you to assign.

**Comment by Maria-alnap** [comment]
@nadia847 Should I be checking anything here? Again, a bit unsure...

**Comment by nadia847** [comment]
@Maria-alnap I've added review criteria for you

**Comment by Maria-alnap** [comment]
@nadia847 Thanks! Unfortunately there's still a few issues with this page showing up on my end:

- The cards that appear after clicking on the more arrow sometimes show up cropped
- The filters are not really working yet. I have added tags in a few blogs already but when I type one of these tags, they don't come up (e.g. System-wide performance, which is a tag for the "one humanity, many visions" blog post)

**Comment by nadia847** [comment]
@Maria-alnap right ok, back into the backlog this goes :o(

**Comment by russ-manta** [comment]
@meldera can you take a look at this one please?

**Comment by russ-manta** [comment]
@Maria-alnap can you check the last two items you commented on are now fixed as required?

**Comment by Maria-alnap** [comment]
Hi @russ-manta - the filters are working, but I've noticed that on the main page the blogs aren't coming up in the right order. Sort by: latest is active, but they're showing the oldest first - it started doing this after I did one search, and then wouldn't reset, even after I pressed 'reset'.

Also did we choose 'title' as a sort criteria? Does this mean alphabetical order, because I'm not sure if that's useful...

**Comment by russ-manta** [comment]
@meldera could you look at these issues.
1. Remove title from sort criteria
2. Fix the issue that after searching so the view shows latest first

**Comment by russ-manta** [comment]
@Maria-alnap this is now fixed

**Comment by Maria-alnap** [comment]
Great! All good now. Will move to done 👍
