### ISSUE TITLE
(#202) User account config

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#40]
### Done criteria
creating, editing, permissions etc
- [x] add custom fields
- [x]  Add any civi fields, employer may need to be a civi field
- [x] Configure role syncing with drupal/civi
---
### ALNAP to check
- [ ] ?

**Comment by melkers** [comment]
Blocked until #42 is resolved

**Comment by angievanhegan** [comment]
@melkers I don't think it's blocked, it just needs to be done in sequence. The backlog should be a prioritised/ordered list so as long as this sits under 42 we should be good. Basically, this is not an issue that we need to urgently sort to allow us to keep working. Does that  sound ok?

**Comment by melkers** [comment]
@angievanhegan perfect
