### ISSUE TITLE
(#208) Migrate users (trial)

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#41]
Probably for Russ, Arseni and Dave

- [x] Create importer for importing data into civi
- [ ] Test importing data into civi from current database
- [x] Test creating drupal accounts synced with civi accounts (see https://wiki.civicrm.org/confluence/display/CRMDOC/Creating+a+Drupal+user+for+every+CiviCRM+contact) OR (https://civicrm.org/blog/petednz/creating-drupal-users-made-easy-for-single-or-multiple-contacts-via-civi-imports-and)
- [ ] Assign roles to imported accounts automatically

**Comment by angievanhegan** [comment]
@russ-manta Dave mentioned you'd asked him to look at this. Are you being one step ahead of the game and planning for the next sprint? Or can he leave it until it comes into the sprint? Thanks

**Comment by dave-manta** [comment]
Changes made to Civi for import (in case of roll back):
1. Updated suffixes

**Comment by dave-manta** [comment]
We @russ-manta need to check we have all the user data.
Also, let ALNAP know about any data that has issues, can't import and what we are importing.

**Comment by angievanhegan** [comment]
@dave-manta Are you done with this task? Should we put it in the review column for @russ-manta?

**Comment by dave-manta** [comment]
Not yet @angievanhegan, a wee bit more to do tonight and tomorrow with Russ, then I need to confirm a few things with ALNAP.

**Comment by russ-manta** [comment]
@dave-manta @meldera while I'm away it may be worth you trying to get Arseni to have a go at automatically creating user accounts in Drupal and/or organisations with the use of a Civi tag as mentioned in the link I posted: https://civicrm.org/blog/petednz/creating-drupal-users-made-easy-for-single-or-multiple-contacts-via-civi-imports-and

**Comment by dave-manta** [comment]
Sure thing @russ-manta

**Comment by angievanhegan** [comment]
@dave-manta you've moved this into the backglog (and out of the sprint backlog) - is it no longer part of this sprint? And/or no longer in progress?

**Comment by dave-manta** [comment]
@angievanhegan - Update: We're 80% complete on all the items in this task.  I need input from ALNAP - waiting to hear back from Maria (over Slack) as to when we can catch up - to finish off the data import trial and I need to spend a bit of time checking that the other items are complete.  So, almost there, but not quite.
