### ISSUE TITLE
(#208) Review user migration

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#42]
#### Requirements
- [x] Gain access to user table
- [x] Assess migration and which fields we'll need for user accounts
- [x] Don't forget to consider Civi  in migration

Viewing current sign-up will shed some light. We also have accounts for Steve and Dave which we can edit to see the fields. http://www.alnap.org/account/create.aspx

**Comment by melkers** [comment]
Don't forget to consider Civi  in migration

**Comment by russ-manta** [comment]
This is the plan:
1. Import all information into Civi for all users. 
2. Create corresponding user accounts in Drupal using the following: 
https://wiki.civicrm.org/confluence/display/CRMDOC/Creating+a+Drupal+user+for+every+CiviCRM+contact
3. Drupal will be used to store usernames/email, passwords, photos and probably a bio field
4. Having created the usernames in Drupal we may need to sync the users with the entity reference field for imported resources etc so they have the correct owner.
