### ISSUE TITLE
Build job content type

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#43]
Design https://invis.io/F3C0I5GAX

link to #46

**Comment by dilwarhussain** [comment]
Location now needs to be a taxonomy at country level

**Comment by dilwarhussain** [comment]
http://alnap-dev.mrmdev.co.uk/admin/structure/types/manage/job/fields

**Comment by nadia847** [comment]
@ican-icant Do we also need the following fields (from OneNote)?

- Topic 
- Role
 - Types of opportunities (taxonomy)
-- Jobs (permanent) 
-- Consultancy 
-- Call for experts 
-- Advisory committee call 
-- Emergency deployment opportunity
