### ISSUE TITLE
User account vs person content type face off

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#45]
#### Requirements
-----
- [x] decide if we'll build everything using person content for all people or user accounts

- [x] Blog authors will have user accounts with the profiles viewable. These need to be designed (#156)
- [x] Secretariat etc will use the Person and team content types 
----

If we went with user accounts, would need to rebuild aspects of Remora that use the person content type, eg, teams, feeds and related.

On the current site, as we sometimes do, there are separate profiles for the team and blog authors.

**Comment by angievanhegan** [comment]
@dave-manta What's blocking you from doing this?

**Comment by dave-manta** [comment]
@angievanhegan Nadia marked it as blocked. I don't think it should be and me & Russ can work it out.

**Comment by russ-manta** [comment]
plan is to use person for team members ie secretariat and users for members of organisations that sign up and can submit resources etc

**Comment by nadia847** [comment]
What about blog authors? are these definitely users? @russ-manta @dave-manta

**Comment by dave-manta** [comment]
@nadia847 if they need to be, I don't see why they couldn't be.

**Comment by nadia847** [comment]
@russ-manta I've updated the description; we happy with this now? Can I chuck it into "done"?
