### ISSUE TITLE
(#211) Build & theme jobs node

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#46]
### Dependencies
- [x] Job node built

### Done criteria
 - [x] Create job Type (Taxonomy: Consultancy, ToR, Job etc)
- [x]  Share icons
- [X] Build node view with job details (deadline, posted, org, contact etc)
- [x] ISSUE: Sidebar alignment
- [x] Add member view
- [x] ISSUE: Text white in node details box and also not floating properly
---
### Designs
- [Job page](https://invis.io/UZCLJXSAF)
---
### ALNAP to check
- [x] Looks like design (http://alnap-dev.mrmdev.co.uk/job-example)
- [x] Can add a new job node via CMS menu

**Comment by nadia847** [comment]
@Maria-alnap Added links & review criteria

**Comment by Maria-alnap** [comment]
@nadia847 Just tested it and it looks good! http://alnap-dev.mrmdev.co.uk/jobs/alnap-is-looking-for-a-research-assistant

I'll move to done
