### ISSUE TITLE
(#240) Build jobs submission (DUPE?)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#47]
Dependent on outcome of #76 

------

From OneNote
- No limit to number of jobs a member can submit. 
- Non-members have to submit and pay for a each job, one at a time for £45 each. Same for events. 
 - WorldPay for transaction. 
- All require approval by ALNAP before going live and usually same day. 
- Need workflow from Maria.

Workflow:
1. Submit 
2. Approval by ALNAP 
3. ALNAP clicks a button to send payment request 
4. Jobs automatically published when payment is received

### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@dave-manta Action from client  meeting on 6/6 - you need to talk to Phil at ALNAP to understand more how this is working. Do you want to leave it to the sprint when we work on it,  or do it now in case it's a fiend?

**Comment by dave-manta** [comment]
@angievanhegan have assigned this to Russ on #76

**Comment by angievanhegan** [comment]
@russ-manta Is this a dupe of 244?
