### ISSUE TITLE
DUPE? Build functionality for HELP advanced search

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#54]
Requirements here in wireframe: https://invis.io/2CC3EN2NH

**Comment by melkers** [comment]
I've renamed the title of this card from wireframe.  @nadia847 I think you should discuss this one with some other devs including @meldera and decide the best way to present and then we'll just have to tell ALNAP that's the way it is.  UX is the most important thing here.

**Comment by angievanhegan** [comment]
@ican-icant Can I move it to signed off on the page status board? They're going to see it again later, when it's built.

**Comment by angievanhegan** [comment]
Following client meeting on 6/6. They currently like the tab, but they're expecting to see something different when it's built!

**Comment by angievanhegan** [comment]
This task was just to confirm the functionality. It's been agreed with the client on 6/6 to I'm moving to done.

**Comment by dave-manta** [comment]
@angievanhegan I still think Nadia and Arseni et al need to discuss the implementation of this before it is implemented.  Not sure if that means this should be re-opened?

**Comment by nadia847** [comment]
@dave-manta @angievanhegan @ican-icant 

Russ, Arseni and myself agree that we want to have regular (quick) search always present with the ability to expand advanced filters, otherwise you force users to have to search twice.

**Comment by dave-manta** [comment]
@nadia847 agreed. Decision made. And please edit first note to reflect requirements and feedback to @angievanhegan if any wireframing or design work is  needed here.

**Comment by angievanhegan** [comment]
@russ-manta Is this a duplicate of #159? If it is it should just be moved over to done. Thanks

**Comment by russ-manta** [comment]
@angievanhegan this has all been agreed and implemented already
