### ISSUE TITLE
Wireframe blog landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#56]
Design here: https://invis.io/7CC18FLJ4

Search fields: 
- Author
- Text
- Organisation 
- Tag (using resources tag)

Linked to #36 and #39

**Comment by angievanhegan** [comment]
@ican-icant There's a note on the page status board that says this needs some search criteria. What work actually needs doing here before we can say this is complete and ready for build to start on it?

**Comment by ican-icant** [comment]
Signed off by client in meeting 6/6/17
