### ISSUE TITLE
(#202) Wireframe/scope for comments on blog post

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#57]
### Done criteria
- [x] Moderation required?
- [x] ALANP happy to use DISQUS if MRM recommend it
- [x] Requirements captured in #194

**Comment by angievanhegan** [comment]
@ican-icant On the page status board it says that this still needs comments adding. Do they need a wireframe or a design? Thanks

**Comment by ican-icant** [comment]
@angievanhegan No wireframes or design for this. Think discussion needs to be had whether we use Drupal comments or DISQUS. What do we think? @russ-manta @dave-manta

**Comment by dave-manta** [comment]
@ican-icant this perhaps needs to be discussed in a meeting as part of a sprint, rather than here.

**Comment by russ-manta** [comment]
@Maria-alnap we're currently scoping the commenting for the website. Would you be willing to consider using Disqus for comments?  This is something that ODI use and it comes with some nice features such as comment moderation, notifications. There is a small monthly fee of $10 per month: https://disqus.com/pricing/  The only issue might be with you adding in your comments for the previous site - do you need to keep these?

**Comment by Maria-alnap** [comment]
@russ-manta Happy to go with Disqus. Any idea how much it would be if we pay upfront for a whole year? I have just created an account for us to find out, but it seems things need to be set up first. Pls find login details below:
comms@alnap.org
PW: qA1RtpYg07qV

We would like to move comments for past blogs, as there's been some quite interesting discussions there and it shows that the blog generated some food for thought. Also we have high traffic for older blogs too, which shows those conversations are still relevant.

How would it operate in practice from a user's perspective?

**Comment by angievanhegan** [comment]
@Maria-alnap migrating comments from past blogs is currently out of scope (see the Realtime Board and our meeting on Friday 30 June when we talked about migration scope). Do you want us to cost this? Please can you @ me in your reply and assign the issue to me so I know to pick this up. Thanks.

**Comment by angievanhegan** [comment]
@russ-manta If we're going ahead with Disqus, does that mean that people using the site will need two logins? A Drupal one to login as an ALNAP member, then a second one for Disqus? 

Also, I'm assuming that Disqus will handle all the moderations so it's entirely within Maria's control?

Thanks

**Comment by angievanhegan** [comment]
@Maria-alnap a programatic migration of  comments from past blogs is currently out of scope. From your comment above, I can't tell if you're saying you're going to move them manually, or if you'd like us to do it. Let me know if it's the latter and we can organise a quote. Thanks.

**Comment by Maria-alnap** [comment]
Hi @angievanhegan we're aware of that, which is why I've repeatedly asked how we'd be able to do this from our end. Will we have to log in as each particular person via disqus and add the comment?

Looking forward to your suggestions on workflow for this :)

**Comment by angievanhegan** [comment]
@russ-manta A couple of questions in here for you. Thanks

**Comment by angievanhegan** [comment]
@Maria-alnap Russ thinks that you'd have to copy the comments across manually, then assign them to the relevant user. I'm going to set-up a quick Skype call for you and Russ to discuss the following:

1) Whether to use Drupal or Disqus
2) Options for migrating comments

**Comment by angievanhegan** [comment]
@russ-manta I am moving  this issue to done if the plan is to go ahead and build disqus with single sign on. We can work from issue #194

**Comment by Maria-alnap** [comment]
Thanks @angievanhegan . Happy to speak to @russ-manta next week

**Comment by angievanhegan** [comment]
@Maria-alnap Great. We've set it up in Disqus ready to show you but we'll go over the pros and cons of using Disqus and Drupal for this in the meeting on Monday so that you can make a final decision.

**Comment by Maria-alnap** [comment]
@angievanhegan Great! Looking forward to our call later :)
