### ISSUE TITLE
(#210) Build and theme annual meetings landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#6]
### Dependencies
- [ ] Link to #35

### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by nadia847** [comment]
Dupe

**Comment by angievanhegan** [comment]
This can all be done in a normal event page. Therefore this is a DUPE of #30
