### ISSUE TITLE
(#216) Member only resources

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#64]
Requirement: Some resources need to be restricted to logged in members

### Done criteria
- [x] The display of members only resources needs fixing when logged out, and in see: http://alnap-dev.mrmdev.co.uk/help-library/evaluation-en-temps-r%C3%A9el-%C3%A0-mi-parcours-de-la-r%C3%A9ponse-doxfam-international-%C3%A0-la-crise
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by melkers** [comment]
I (Dave) think these should be show in list view for anonymous users and receive a member only stamp, then the node would require login and be restricted.  Even if they are hidden from anonymous users, I believe there should be a visual way to pull these out in the list view and perhaps they should also be a  filter on the search.  This needs discussing with ALNAP.

**Comment by dave-manta** [comment]
Awaiting client response on slack channel

**Comment by dave-manta** [comment]
Client wants to indicate member only resources, both on the list view and on a node (for logged in members). For those not logged in, the node needs to prompt them to login.

**Comment by ican-icant** [comment]
This needs some discussion before design can commence @dave-manta as there is already a MEMBER tag sitting on the cards and adding another will be confusing  to say the least. I suggest dropping the MEMBER tag for a MEBER ONLY tag. Your thoughts?

**Comment by dave-manta** [comment]
Confirming that I have discussed this with Steve, and we're going to try dropping the MEMBER and ALNAP stamps and replace with a member only stamp.

**Comment by ican-icant** [comment]
@angievanhegan  this needs sign off from client. https://invis.io/32BYCG1CW#/235626263_Homepage_Wide
We also need to sort this for the node too.  Cat needs to do this

**Comment by russ-manta** [comment]
@ican-icant any news on this?  Can we have a design for member only node - what someone sees when they are not logged in?

**Comment by russ-manta** [comment]
@Maria-alnap can you explain the difference between Subscriber and Full member please?  Is a subscriber someone that has an account but belongs to an Organisation without a paid membership?

**Comment by Maria-alnap** [comment]
Hi @russ-manta yes, that's indeed the case. Subscribers are users that have an account but are not full ALNAP Members

**Comment by russ-manta** [comment]
@Maria-alnap thanks. So it looks like there are only 2 resources that are subscriber only. Do you need any resources to be subscriber only or is it just either Member only or anyone can access?

**Comment by Maria-alnap** [comment]
Hi @russ-manta that must've been a mistake, as we're only meant to have Member only or open access resources. I can confirm we will only have these 2 categories on the new site.

**Comment by dave-manta** [comment]
@dilwarhussain need a different notification for when someone is logged in with a non-member account, along the lines of...

This resource is for members only.  You are currently logged in as a non-member.  If you believe you should be a member of ALNAP, please contact us.

Link through to the contact us page.

**Comment by dilwarhussain** [comment]
@dave-manta Test this out on dev for me please.

**Comment by dave-manta** [comment]
@dilwarhussain yep, put this live!
