### ISSUE TITLE
Organisation CT vs Civi data

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#66]
#### Requirements
-----

- [x]  decide how much of this data goes into CiVi
- [x] Add any civi fields required

----

There are members and non members - together they're all called agencies when it comes to resources, however we should call them Organisation and if ALNAP want to label them as agency on Resources, that's fine.
Civi records if they're a member or not
There are full and associate members

**Comment by dave-manta** [comment]
Had a chat with Russ. He's going to explore creating entity in Drupal from Civi orgs.

**Comment by russ-manta** [comment]
Currently we have an organisation content type which is a hybrid of the Remora organisation content type but with the addtional fields required by ALNAP. I think we will most use the organisation content type with a link to the Org in civi but I'm currently experimenting with the Civicrm Entity module which will determine how much crossover there is.

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this task when you have a second?  thanks

**Comment by russ-manta** [comment]
@angievanhegan done

**Comment by russ-manta** [comment]
No civi fields for now - will be added into Drupal manually
