### ISSUE TITLE
(#234) Build and theme user registration

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#67]
### Workflow for user registration:
1.  All users use the same form
2.  On the form the user will select their organisation, be that a member org or not and be able to add a new organisation if needed.
3.  This will create an 'inactive' employee relationship in CiviCRM and notify ALNAP of the new registration.
4.  The user will receive an email to confirm their new Drupal user account and after clicking a link to confirm will have access to login to the website.
5.  ALNAP will need to mark each and every new employer relationship as active. At that point, the user will be able to see their employer information on their account page and anyone that was made an active employer of a membership organisation will be automatically have a membership in CiviCRM and granted access to the members only content on the website based on that membership.

---

## Done criteria (TBC)
- [ ] All new registrations to be approved by ALNAP [output of slack discussion pasted below] see http://www.alnap.org/account/create.aspx
- [ ] Create registration form(s) (including civi webforms), ability to assoicatewith/add organisation
- [ ] Create workflow/rules for ALNAP to approve registrations
- [ ] New members to be given role based on organisation membership
- [ ] Theme forms according to any designs
- [ ] Add organisation reference to a user once they have been approved by ALNAP
---
## Designs
- [ ] Registration page(s) / forms
---
## ALNAP to check
- [ ] Register as new user to check end to end process

**Comment by dave-manta** [comment]
Question for ALNAP.  A new user that selects a member organisation as their employer, by default will automatically gain access to the members area of the website.  If you need control, then are you happy to approve each new user registration?  I think we've discussed this, however I can't fine my notes on the outcome!

**Comment by dave-manta** [comment]
Awaiting client response in the slack channel

**Comment by angievanhegan** [comment]
@Maria-alnap Are you able to answer this one for us?

**Comment by dave-manta** [comment]
https://mantaraymedia.slack.com/archives/C5Q7FV3K9/p1496823229458274

**Comment by angievanhegan** [comment]
Copied from Slack

DAVE: A new user that selects a member organisation as their employer, by default will automatically gain access to the members area of the website. If you need control, then are you happy to approve each new user registration? I think we've discussed this, however I can't fine my notes on the outcome!

MARIA:  I don't think we would need control over this if we enable the functionality of users updating their profile after submission? (which is what we'll also need for jobs and events, all out of scope and yet to be costed as well)

DAVE: OK, so I'm clear.  You are happy for newly registered users who select a member org and users who perhaps change their employer to a member org to gain instant access to the members area without approval?

MARIA: That's a point, actually. People may fiddle with listing themselves as a Member org when they're not. Let's go with approving them then, we don't have much of an option

DAVE: This is fairly easy to do for new registrations, but I think it might be tricky for us to approve an existing user who logs in and updates their employer from a non-member to a member.  I think what we agreed before was that you guys would keep an eye - we can send you notifications - on new user registrations and anyone that changes their employer and deal with any issues you spot.  After all, is the members only area so sort after that people would want to 'cheat' to gain access?

MARIA: We think we should go with approving them and as a way of checking they're legit, we'll encourage people to use their work email for their account. that way we can confirm that they belong to the organisation they're saying they work for

DAVE:  so, could you confirm what you are looking approve, new registrations and changes to an employer?

MARIA: We would like to go with your suggestion of approving new registrations and keep an eye for changes in organisation but not approve those

DAVE:  OK.  How would you feel about preventing people changing their organisation and asking them to contact you to do so?

MARIA:  that sounds good

**Comment by angievanhegan** [comment]
@russ-manta Do you need more client input on this? Also, would it be possible to make the task title a bit more specific, and to estimate it please? Thank you.

**Comment by russ-manta** [comment]
@angievanhegan I think I have enough info from Dave now.

**Comment by dave-manta** [comment]
@angievanhegan @russ-manta I see this has been closed, but do we not need a task to build user registration now?

**Comment by dave-manta** [comment]
Initial form is here: http://alnap-dev.mrmdev.co.uk/user-registration

**Comment by dave-manta** [comment]
@Maria-alnap for new organisations that are registered on your website (from an employee registering), do you set the organisations constituency type or do they chose what they believe their type to be?

**Comment by nadia847** [comment]
@dave-manta I really need you to sort out user edit forms so that the profiles can be signed off.

**Comment by dave-manta** [comment]
@nadia847 I'm afraid I need @russ-manta to confirm the plans. It's out of my hands.

**Comment by dave-manta** [comment]
@Maria-alnap I need you to confirm the workflow for user account registration at the top of this thread. Any questions do let us know.

Dave

**Comment by Maria-alnap** [comment]
@dave-manta just to confirm. Does the workflow outlined above means that we'll need to approve EVERY new organisation added?

**Comment by dave-manta** [comment]
@Maria-alnap you do not need to approve as such as the organisation will get automatically added to Civi, however you'll need to approve the employees relationship to their employer and at that point you can check and amend the employer info should you wish.  Note that as soon as someone adds a new organisation it will then be available for others that register.

**Comment by dave-manta** [comment]
@Maria-alnap just checking into to see if my response above is OK?

**Comment by Maria-alnap** [comment]
OK, all clear (may need you to explain it again when we use it as I'm in full population mode at the moment!)

**Comment by dave-manta** [comment]
@Maria-alnap OK, so we're going to build it that way! It will be fine.
