### ISSUE TITLE
(#214) Build and theme related content view

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#70]
depends on #15 - Setup the taxonomy for tagging resources / events / news

### Done criteria
- [x] Confirm scope (is remora functionality enough?)
- [x] Confirm which content types are included within the view and where this view is displayed (Blogs, jobs, news, events, resources?)

Related by Entity Ref
- [x] Rename Related entity ref field to Recommended (throughout site)
- [x] Change related entity ref view heading to Recommended
- [x] Automatic add related item to the Related ref (two way entity relationship)
- R&D: Can you remove relationship from one node without affected the other? - Nope.

Related by Tags
- [x] Related box: None / Display All related / Default: Display same content type
- [x] Displays after Recommended, titled Related

- [x] Build views of related content
- [x] Theme views of related content

---
### Designs
[See Blog page](https://invis.io/NJC8OGC2B)

---
### ALNAP to check
- [x] Related content using tags appears on RHS
- [x] Recommended resources appear at the bottom of the page, see: http://alnap-dev.mrmdev.co.uk/help-library/responding-to-earthquakes-learning-from-earthquake-relief-and-recovery-operations

**Comment by angievanhegan** [comment]
@meldera Please can you estimate this task? Thanks

**Comment by Maria-alnap** [comment]
@nadia847 what am I meant to look at here?

**Comment by nadia847** [comment]
@Maria-alnap nothing to look at. you were in discussions with dave bit it;s been scoped and has been assigned to arseni for build.

**Comment by russ-manta** [comment]
comment for me..
Recommended resources should show at the bottom of the page (this uses the recommended field)- remove the image as pdf cover is too big 
Related resources are using tags and should show on the right (the current related resources on the right is wrong it's using entity ref but should be using tags)
see http://alnap-dev.mrmdev.co.uk/help-library/responding-to-earthquakes-learning-from-earthquake-relief-and-recovery-operations

Probably need to remove context for the related on the right being shown at the moment and replace with the blocks generated by this view: http://alnap-dev.mrmdev.co.uk/admin/structure/views/view/tagged_sidebar/edit

**Comment by russ-manta** [comment]
@cutlern can you take another look at this one - see my comment above - it looks like we have two views currently showing the same thing - call me if unclear

**Comment by cutlern** [comment]
@russ-manta should images be removed from the sidebar related content view too?

**Comment by russ-manta** [comment]
@cutlern yes please remove images and can we show perhaps 5 items max on RHS?

**Comment by russ-manta** [comment]
@cutlern can we have a bigger font for the 'Related content' title above the related items on the RHS?

**Comment by Maria-alnap** [comment]
All good. Will move to done
