### ISSUE TITLE
Build alternative translations entity reference field to other versions of a resource

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#73]
- titles and body/description only
- A resource may be available in 3 or 4 languages 
- On current site, each translation is a separate node 

google translation vs drupal?

- [x] Need to work out how we deal with translated version of a resource, particularly with regards to migration
- [x] Need to think about language expansion - currently out of scope but later this may include Arabic.

**Comment by angievanhegan** [comment]
Angie to check with Steve if there's more to do than just enable them to add them.

**Comment by russ-manta** [comment]
This is just done by creating an identical page but choosing a different language in the language field and uploading different text/pdf as required. Resources in the different languages are then just related using the Related field
