### ISSUE TITLE
(#210)  Build & theme events search

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#75]
### Done criteria
- [x] Add field for Event type Other (dependent on Type) This field will show when 'other' option is selected from event type list.
- [x] Add filter to filter ALNAP/Member/Other events
- [x] Display ALNAP or Member on events cards and if a member display org. And if contributer field is empty, still show the organisation.
- [x] Show all events in results inc. those tagged for annual meetings
- [x] Add event / sign up/ past events buttons
- [x] ISSUE: Grid/list toggle works on desktop, but not mobile (on mobile, it says '0 items' in each of the event search boxes)

**Should be able to search by:**
  - [x] Text
  - [x] Type (Conference, Panel discussion, Lecture/ seminar, Workshop, Training course
  - [x] Other event (please specify), Online event (please specify)). ALNAP to be able to edit list. 
  - [x] Organisation (agency)
  - [x] Location
  - [x] Tags (the resource keywords)

**Additional page elements:**
- [x] Theme filters
- [x] View toggle list/gallery
- [x] Theme date grouping
- [x] Load more
- [x] Match heights

**Note: No need to search by member/non member events.**

---
### Designs
- [Events wide](https://invis.io/VPC8MGQ6E)
- [Events wide search](https://invis.io/U6C8MHW2E)
---
### ALNAP to check
http://alnap-dev.mrmdev.co.uk/events
- [x] Page looks like the design on desktop
- [ ] Page works on mobile
- [x] Filtering and search works

**Comment by dave-manta** [comment]
1. Text
2. Type (conference, launch, lecture, meeting, seminar, workshop, training course, webinar, other)
3. Tags (the resource keywords)
4. Organisation (agency)
5. Member vs non-meb

**Comment by angievanhegan** [comment]
I thought they said they don't want to search on member. I'll check with them.

**Comment by dave-manta** [comment]
@angievanhegan - searching on member -I think that was for jobs, but you might be right with Events as well.

**Comment by nadia847** [comment]
@dave-manta there is mention of Sponsored events in OneNote. What do we do about that?

**Comment by dave-manta** [comment]
@nadia847 good question!  Erm... I don't know :(  Ask @ican-icant ?!  We may have to ask ALNAP, I suggest you or Steve does that on the Slack channel using my numbering system... ya?

**Comment by angievanhegan** [comment]
@dave-manta Can I suggest we leave it in here with the 'Needs ALNAP input' tag and ask them when we meet them? We're going to go through all these questions with them. I don't think we need an answer soon do we? Thanks

**Comment by dave-manta** [comment]
@angievanhegan sure, good with me.

**Comment by ican-icant** [comment]
@dave-manta  @angievanhegan From memory, sponsored events are paid for by non-members, but let's ask them later

**Comment by angievanhegan** [comment]
Hi @Maria-alnap Three questions for you:

1. Do you want the events search to search on member? 
2. Have you decided yet how people will search by sector? Can this just use the resource tags?
3. Can you clarify what sponsored events are please? 

Thank you very much.

**Comment by angievanhegan** [comment]
@nadia847 Do you have enough information to be able to estimate this one please? Thanks

**Comment by Maria-alnap** [comment]
HI @angievanhegan !

Please find our answers below:
1) No, no search by member needed
2) We would like people to be able to search by top level resource tags.
3) On the type of event, we want to refine the existing list. Please use the options below instead:
Conference
Panel discussion
Lecture/ seminar
Workshop
Training course
Other event (please specify)
Online event (please specify)

Thanks!

**Comment by angievanhegan** [comment]
@Maria-alnap Thanks for this. I've updated the requirements at the top of this issue and I'll put the list of event types on the taxonomy issue. @nadia847 Does this go back to you now?

**Comment by nadia847** [comment]
@russ-manta how are we capturing whether this is an alnap or not event? so that ALNAP events can be promoted above others?

**Comment by dave-manta** [comment]
@Maria-alnap when you see a list of events: http://alnap-dev.mrmdev.co.uk/upcoming-events, do you want to show to user which events are from a member organisation and which are not?  In both cases I'm assuming we want to display the organisation name.

**Comment by dave-manta** [comment]
@Maria-alnap also, if you are someone wants to add an online event, we have noted to have another field titled 'please specify'.  What is this for?

**Comment by Maria-alnap** [comment]
@dave-manta yes to Q1 on Members, we need to ID somehow the ones which are from Members. Not sure how this was scoped in the design...

on Q2, online events can be webinars or other things like live Q&As, etc... Hope this makes things clearer

**Comment by dave-manta** [comment]
@Maria-alnap thanks, I believe that is what we need.

**Comment by Maria-alnap** [comment]
@angievanhegan I'm naming you on this, as I'm not sure who to tag! 

1. Grid/list toggle works on desktop, but not mobile
2. When on mobile, it says '0 items' in each of the event search boxes

**Comment by angievanhegan** [comment]
@russ-manta I've added the issue to the done criteria. It just needs assigning.

**Comment by russ-manta** [comment]
@cutlern can you look at this one please?

**Comment by russ-manta** [comment]
@cutlern do you know if this one was done? does it just need moving to review?

**Comment by cutlern** [comment]
@russ Dilwar is working on the issue for this card about mobile

**Comment by dilwarhussain** [comment]
@russ-manta I've removed the grid/list button on mobile as at that width there is no difference in how the items are shown, they are always stacked one on top another. Also the chosen module does not work on mobile so the filters revert to a simple multi-select list when on mobile.

**Comment by russ-manta** [comment]
@dilwarhussain thanks

**Comment by Maria-alnap** [comment]
This looks good. I'll move to done
