### ISSUE TITLE
(#240) Scoping Payments for events & jobs

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#76]
### Requirements

Find out specific details how how this is built so that we can work around it and reuse as much of the current systems as possible. 

Currently, ALNAP (via the website) can generate a payment request to WorldPay and once paid the items is automatically published.

From OneNote:
- Members post for free and non-members pay per post. 
- Can we take payment pending approval?  
- Currently, automated email upon being approved with payment request.

Needs to use WorldPay
May have a manual process (Maria has confirmed that that would be ok)

Linked to #47 (Build jobs submission)

Current thinking is that this might be about 5 days of work ie 5 x £560 but need to check a few more things to confirm

Russ confirmed that the simple workaround is a similar amount of work as the automated solution. ALNAP would prefer the automated solution. 

----

### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

-----

**Comment by angievanhegan** [comment]
@dave-manta Can we be more specific on what this task is? Is it to scope or to build? Thanks

**Comment by dave-manta** [comment]
Here's Maria's comment from #97

"Of course, @dave-manta. Have you reached out to him on this? Would you like me to chase him?

We'd be happy to change the workflow for the approval/payment of these to make it happen. I spoke to our ops team earlier and they confirmed the world pay set up is just a link. The complicated bit would be automatising the publication of the job/event once payment has come through, but we'd be happy to change the process to make it work."

**Comment by dave-manta** [comment]
@Maria-alnap Russ is going to contact Phil and then we can discuss requirements/options with you and cost the work.

**Comment by russ-manta** [comment]
I have contacted Phil, awaiting a response

**Comment by angievanhegan** [comment]
Hi @Maria-alnap - @russ-manta sent an email to Phil about this yesterday. Can you see if he can reply? We'd like to see if we can get this quote to you ASAP so that you can decide on everything on Friday. Thanks

**Comment by Maria-alnap** [comment]
I've chased him now. We'll see!

**Comment by russ-manta** [comment]
@Maria-alnap with the current setup do you review the content of posted jobs/events before sending a payment link or is the whole process automated?

**Comment by Maria-alnap** [comment]
@russ-manta We do review the content, as the job/event needs to be relevant to the ALNAP Membership...

**Comment by angievanhegan** [comment]
@russ-manta Is there anything I can do to help get this quote done for Maria? Thanks

**Comment by russ-manta** [comment]
@Maria-alnap I've just submitted a job and an event logged in as Steve/Dave. Is the next step normally for you to send me a payment link or am I missing something? If so could you send me the link so I can take a look?

**Comment by Maria-alnap** [comment]
@russ-manta , I've just seen your submission as pending in the backend and have now ticked it as approved. That should've triggered the payment email. Pls keep me posted!

**Comment by russ-manta** [comment]
@angievanhegan I'm still going through the testing of current functionality.  Current thinking is that this might be about 5 days of work ie 5 x £560 but need to check a few more things to confirm

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan Just to reiterate that we're willing to go one step down with this and action ourselves the publication of events and jobs that have been paid for, in case this makes the task any easier...

**Comment by angievanhegan** [comment]
@russ-manta How are you getting on with this? Do you think you'll be able to have a final quote by Friday? Maria is keen to know all her costs as soon as possible. Thanks

**Comment by angievanhegan** [comment]
@russ-manta Have you had a moment to finalise this quote? It'd be great to give it to Maria today at the meeting at 2. You can just at it at the top of this issue. Thanks very much

**Comment by angievanhegan** [comment]
@Maria-alnap I have a note to say you were going to approve a job for Russ (on his account) so that he can see the process in order to finish this quote. Is that right? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan I've just logged in as @russ-manta  and submitted a job on his behalf. Because I used his subscriber account, he should've received the payment email and he'll now be aware of the workflow for that.

**Comment by angievanhegan** [comment]
@russ-manta You should be getting the payment email shortly.

**Comment by Maria-alnap** [comment]
@russ-manta I have just sent you a payment request and above you can see screenshots from the backend. I hope this helps with you figuring out the workflow for this in more detail

**Comment by russ-manta** [comment]
@angievanhegan @Maria-alnap thanks I've now seen this.  The workflow would be slightly different in our implementation whereby the person would make the payment upfront and then once payment had been submitted they would have the ability to create their job/event. Once they had created their content it would remain unpublished until you had a chance to review it and then either publish it or contact the submitter if any content changes were required.
I stand by by 5 days @ £560 = £2800 +VAT . This includes setting up the payment workflow for all types, testing end to end payments. Styling and making the whole process user friendly.

**Comment by angievanhegan** [comment]
We're going to discuss this at the meeting with Maria on Monday 17 July to confirm if Maria wants it to come into scope.
