### ISSUE TITLE
(#208) Build and theme member organisation search (listing page)

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/alnap#79]
### Done criteria
- [x] ISSUE: Remove sort by title (see comments below)
- [x] ISSUE: Change search blogs to Search Members
- [x] ISSUE: List view toggle looks a bit weird when there is a member with an image
- [x] BLOCKER: Keep the search box open on submit (see #193)
- [x] Sort by A - Z (only)
- [x] Search criteria: text search, constituency
- [x] Theme search page

---
### Designs
- [Members page - listing](https://invis.io/P6CLJY7XB)
---
### ALNAP to check
[Members page](http://alnap-dev.mrmdev.co.uk/membership/members)
- [x] Page looks like design
- [x] Filter works ok
- [x] Page view works ok (Grid/list)
- [x] Search works as expected

**Comment by russ-manta** [comment]
@cutlern this is related to the organisation view page you are already building and you may have it covered already but these are some extra criteria

**Comment by cutlern** [comment]
@russ-manta view Haven't checked the third box because the view is using fields instead of teaser display because of the selective filter

**Comment by russ-manta** [comment]
@cutlern could you look at the following issues:
1. Change search blogs to Search Memebers
2. The list view toggle looks a bit weird when there is a member with an image - can you check with @ican-icant to see how this should be displayed
3. We need to keep the search box open on submit can you check this with Arseni or move to blocked on this issue

**Comment by cutlern** [comment]
@russ-manta 

1. Done!
2. Steve says to leave it as is
3. Sorry, my bad :D

**Comment by angievanhegan** [comment]
@cutlern I made boxes at the top for you to tick! Then you can move it into 'Manta Ray review'. Ta

**Comment by russ-manta** [comment]
![members_search.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317a67d22f160aef8442eb/125516c66e82c728ace21e0d46e59197218791bab0faba42b65ef8d665043761260ea62864c7b96aea1b28505c5848a9430d5e40aaaa892ba4e56a26d80f0dbec3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1ed3d2ce08c8f4d3d161755.jpg)
@cutlern is this correct for how the list view should be if an image is present?

**Comment by cutlern** [comment]
@russ-manta yeah, its the same layout that news/blogs/resources have too

**Comment by russ-manta** [comment]
@meldera could you look at the keeping the search box open fix which I think you are looking at for other pages? http://alnap-dev.mrmdev.co.uk/membership/members

**Comment by angievanhegan** [comment]
@russ-manta Ready for you to check.

**Comment by russ-manta** [comment]
@meldera could you take a look at this?  I'm not sure we need the sort by Title if there's only one option and also when choosing to filter by constituency the selected option looks a bit odd (see attached image)
![alnap_filter_select.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59317a67d22f160aef8442eb/125516c66e82c728ace21e0d46e998942292bcaf86e5ab46b662e391254324676b48e13b628ae92dbc56395b4d5a47af405b5842f9fbdc2aa2e06f708a5e58bb873f0c72952f0dbefad341eb5ee779c11ac7a4b6984fc1e23c20e78a874b381a001d8cf65927ed.jpg)

**Comment by Maria-alnap** [comment]
@nadia847 Is this ready for me to look at? I'm unsure...

**Comment by Maria-alnap** [comment]
All good here. I'll move to done!
