### ISSUE TITLE
Wireframe portal landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#80]

**Comment by ican-icant** [comment]
There are two versions of this page. One as separate site and one as internal to the main ALNAP site. Both are in invision @angievanhegan

**Comment by ican-icant** [comment]
Awaiting feedback from @Maria-alnap on designs.

**Comment by Maria-alnap** [comment]
I put my comments on #23 as instructed by @angievanhegan

**Comment by angievanhegan** [comment]
This is a dupe of #23. Archiving.
