### ISSUE TITLE
(#213) Build and theme submit a resource page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#81]
This is a dupe of #243 - moving to archive

### Done criteria
- [ ] for members and non-members - Non members will still need to login to submit.
- [ ] With basic workflow to send notifications on submission
- [ ] We need to clarify how the PDF cover is automatically used as the image for the page. 
- [ ] ?

See notes on wireframe #22

---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by dilwarhussain** [comment]
Need to remember to change link on 'Submit a resource' button on HELP library page to this page once completed. http://alnap-dev.mrmdev.co.uk/help-library
