### ISSUE TITLE
Scope member updates

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#82]
New content type. Same as news but only visible to members on log in.

**Comment by nadia847** [comment]
@dave-manta @ican-icant what are the requirements for members update? does it need any special fields? that news doesn’t? otherwise we can handle it same as members only resources with a tick box on the content type  this wills till allow us to put them on different pages

dave's gut feels it is a separate content type which is probably 1 day of work more than just adding a tick box?

**Comment by dave-manta** [comment]
@nadia847 Make it a tick box if you can control access and set the URL (and exclude from the main news feed).

**Comment by nadia847** [comment]
@dave-manta er that's def a new content type

**Comment by nadia847** [comment]
@cutlern could you add Member update to the content model, please?

**Comment by dave-manta** [comment]
This is becoming my most frustrated ALNAP discussion, so let me confirm requirements and then the dev team can decide the implementation.

1. These are updates from ALNAP to members.
2. They will not be displayed in the main news feed and instead I reckon they will be on some kind of members home page [@angie this needs adding as a work package. I believe that it won't have much on it besides the feed and perhaps a list of member only resources].
3. The URL should probably reflect its location. eg. member-home/updates/update-x
4. It should only be viewable by logged in members, which I think would be the same for the members home page and content within, eg. member only resources.

Ps. @nadia847 not sure why that makes it a new content type? Is that cos of the URL as we have used context to govern URLs based on tick box before... anyway over to you dev people now.

**Comment by dave-manta** [comment]
@nadia847 in addition if Nelle does need to add it to the content model, I think that should be a separate task. I'm going to rename this one to scope.

**Comment by nadia847** [comment]
@dave-manta @ican-icant does it got nuggets?

**Comment by dave-manta** [comment]
@nadia847 if it's easier without nuggets, let's go without.
