### ISSUE TITLE
Card titles

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#84]
From onenote: All content types that are displayed in feeds need 'card' titles

**Comment by nadia847** [comment]
@dave-manta @ican-icant does this mean we need a separate card title so they can have shorter titles from the node title? Because this will need to be added to the content model

**Comment by dave-manta** [comment]
@nadia847 I thought we already hard separate titles for cards, but perhaps I'm not remembering Remora right.  I would go with what we have in Remora cos it's going to be a bit of work to implement an additional field and put that on cards isn't it?

**Comment by nadia847** [comment]
@dave-manta yeah it'll be much more work than leaving it as is in any case :oD

**Comment by nadia847** [comment]
@dave-manta so do we block this?

**Comment by dave-manta** [comment]
@nadia847 perhaps check with Angie about what do with this in waffle, but agreed not do it.

**Comment by nadia847** [comment]
@dave-manta is this future or closed?

**Comment by dave-manta** [comment]
@nadia847 closed.
