### ISSUE TITLE
Languages / Translation

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#87]
### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by nadia847** [comment]
The whole site will need Google translation like on the current site, right? Looks like that can support Arabic fine or is it just resources that need translation? We have a separate card for resource node translation (#73) @dave-manta @ican-icant @russ-manta

**Comment by dave-manta** [comment]
Yes, whole site need Google Translate although Arseni has said several times it won't work.  Resource title and description translation is a separate issue and we have said we're not supporting Arabic.

**Comment by angievanhegan** [comment]
Maria and I agreed to close this.
