### ISSUE TITLE
Resource card content

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#88]
Dependant on #29

Card fields to include (as in design): 
- [x] Image [front cover] 
- [x] Published date  
- [x] Title
- [x] Authors
- [x] Organisation
- [x] Members only tag
- [x] Content Type
------

We also need to discuss how we deal with images. Currently when a resource is added, the front cover of the PDF is used as the image for the resource. (see card #96)

**Comment by ican-icant** [comment]
Where does this field list come from @nadia847 ?

Resource cards should have:
> RESOURCE tag [when in a view mixed with other content types]
> Publish date
> Image [front cover taken from the front cover of the PDF ]
> Title
> Author [Author et al if more than two or both authors' names or just the one]
> Organisation 
> MEMBERS ONLY tag (if just for members)

**Comment by nadia847** [comment]
@ican-icant from OneNote.

**Comment by dilwarhussain** [comment]
@ican-icant Are all the fields in the design accurate. There's a discrepancy between design and One note notes.

**Comment by dilwarhussain** [comment]
@ican-icant @russ-manta Need to work out how the 'Members only' resources are going to work before I can add it to the card content.

Also the authors field is just a varchar text field atm so there will be no option to "et al" if > 2. Can maybe trim the length of the field on the card.

**Comment by angievanhegan** [comment]
@dilwarhussain @russ-manta From the comments it looks like this is blocked. Russ, can you help? Thanks

**Comment by russ-manta** [comment]
@angievanhegan it's not blocked any more. We had a chat about this after @dilwarhussain 's comments. He has started making the changes but didn't finish them before we went away. He'll finish when he's back

**Comment by dilwarhussain** [comment]
Example page using teaser template cards here:
http://alnap-dev.mrmdev.co.uk/resources-test-page
