### ISSUE TITLE
(#240) Editing of submitted jobs, resources, events (after submission)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#89]
Dupe of #242 moved to archive
Current scope:
- All newly submitted resources, jobs and events to require ALNAP approval.
-  Ideally some basic email sent to ALNAP to notify them of new submissions and perhaps the user confirming submissions

To quote for
-  Submitter (author) can edit their content at any time and their edits require approval by ALNAP, along with necessary workflow (version control etc) and notifications.

3 days at £560 = £1,680

### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@dave-manta Do you mind putting the requirements notes in here please? Just so we have a record and they're not just in your big head? Ta

**Comment by dave-manta** [comment]
Sure @angievanhegan 

1. All newly submitted resources, jobs and events to require ALNAP approval.
2. Ideally some basic email sent to ALNAP to notify them of new submissions and perhaps the user confirming submissions
1 & 2 part of current scope
3. Submitter (author) can edit their content at any time and their edits require approval by ALNAP, along with necessary workflow (version control etc) and notifications.  

3 is the bit we need to quote.

**Comment by russ-manta** [comment]
@dave-manta @angievanhegan do i put my quote on this card?

**Comment by dave-manta** [comment]
@russ-manta let's discuss the price on our slack channel and then we can post here as a record, ok?

**Comment by angievanhegan** [comment]
@russ-manta Can you @ me when you add the quote and I can make sure it's stored on the RT board with the others.

**Comment by angievanhegan** [comment]
From onenote: What if one person submits a job. Can someone else in that org edit it? Might need organic groups

**Comment by angievanhegan** [comment]
@dave-manta @russ-manta This costing is going to need doing for tomorrow (Tuesday 13 June) as Dave and Steve are having a meeting with the client at 2 to discuss what's going to be added into scope. Thanks

**Comment by dave-manta** [comment]
Over to @russ-manta to cost I believe.

**Comment by russ-manta** [comment]
@angievanhegan @dave-manta Costing now done

**Comment by angievanhegan** [comment]
Maria confirmed that this can come into scope.

**Comment by angievanhegan** [comment]
Maria confirmed that this can come into scope.

**Comment by dave-manta** [comment]
@angievanhegan so this needs re-tagging and move to backlog?
