### ISSUE TITLE
Work out url structures for content types

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#9]
- [ ] decide if we're going to keep the url structure for resources
- [ ] redirects for blogs?
- [ ] redirects for resources?

**Comment by angievanhegan** [comment]
I'll ask the client if they need to keep the urls for these things

**Comment by dave-manta** [comment]
@angievanhegan I think this is all been decided.

1. Resources - will have new URLs, but need to do redirects
2. Blogs - Ditto
3. News - ditto
4. etc etc.

**Comment by angievanhegan** [comment]
FYI @dilwarhussain @meldera @nadia847 @pipemanta @cutlern @ican-icant. I'll confirm with the client that this is what we're doing.

**Comment by nadia847** [comment]
FROM ONENOTE: For the portals, can we keep the URLs (and not redirect) and/or how would sub-domains work?

@dave-manta @angievanhegan how does this fit in?

**Comment by dave-manta** [comment]
@nadia847 there have been discussions about Portal URLs with Russ and it's all good.  Waiting for ALNAP to accept our quote.  Not relevant for URL redirects.

**Comment by angievanhegan** [comment]
@dave-manta So this can go back to the review column? I was only going to confirm with ALNAP what the plan was.

**Comment by dave-manta** [comment]
@angievanhegan no harm in confirming redirects with the client.

**Comment by angievanhegan** [comment]
Maria is happy to have the redirects and to lose the old uls (she didn't like them anyway)
