### ISSUE TITLE
(#216) Book marking resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#91]
Estimated at 2 days (£1,120)

### Done criteria
- [ ] ?
- [ ] ?
---
### Designs
- [ ] ?
- [ ] ?
---
### ALNAP to check
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
Maria confirmed that this can come into scope.

**Comment by russ-manta** [comment]
@meldera to look at options for implementing this

**Comment by angievanhegan** [comment]
@russ-manta Are you bringing this into the sprint? If so, can you label it as an 'extra'. Thanks

**Comment by angievanhegan** [comment]
@russ-manta Please can you add more detail to the issue name? Was this task just to look at options, rather than to build it? thanks

**Comment by angievanhegan** [comment]
Moving this from ALNAP review to Backlog as it's not within the current sprint goals.

**Comment by Maria-alnap** [comment]
@angievanhegan @russ-manta just to say that this was in scope, has been developed and it is working so I'll move it to done
