### ISSUE TITLE
(#213) Bulk editing of tags

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#94]
2 days = £1120

Bulk editing of tags #94 - Russ asked how ALNAP would like to choose which pages they would like to change the tags for. Maria gave two scenarios:
Simple: It might be that a new ‘sub category’ tag needs to be created. They’d need to search on the parent category then go through them manually one by one and select manually which ones need the new sub category tag. This is probably the most frequent requirement. 
Hard: UN has taxonomies. ALNAP are talking to them about creating a taxonomy for humanitarian themes. They might need to update the title of the tag
Russ proposed a search using the HELP page filters. Then the site editor would go through each resource individually and check a box to say this resource would have the tag changed. 
### Dependencies
- [x] #71
### Done criteria
- [x] Addition to #71 allowing bulk adding/editing of tags to a selection of resources at the same time
- [x] Probably use VBO but taxonomy multi editor or similar may be useful
- [x] ISSUE: When on the first page, you can pick a criteria at the top, you can't unselect it
- [x] ISSUE: Where can ALNAP check they've been added?
---
### Designs
- [x] N/a
---
### ALNAP to check
- [x] Can edit tags for resources as required - see notes below for process

### How to edit tags ###
Goto: http://alnap-dev.mrmdev.co.uk/admin/content/resources
1. Select resources you want to edit using search/filtering as required and then check boxes of relevant resources
2. From the operations dropdown choose 'Modify entity values' and click execute
3. Check the tags box and click on related
4. Add new tags separated by commas.
5. IMPORTANT - Check the box 'Add new value(s) to Tags, instead of overwriting the existing values.' if you don't want to remove any previous tags.
6. Click Next & Confirm

**Comment by angievanhegan** [comment]
This can probably only be bought into scope if it's a relatively easy job.

**Comment by angievanhegan** [comment]
@Maria-alnap This has now been costed. It will just take two days, which is £1120.

**Comment by Maria-alnap** [comment]
Great @angievanhegan ! Please do bring it into scope. We really need this :)

**Comment by angievanhegan** [comment]
@russ-manta @ican-icant @dave-manta FYI - this is now in scope. I am updating the in-out scope doc you produced on 14 June. 

@russ-manta I've added a work package for this to the unsorted pile.

**Comment by Maria-alnap** [comment]
@angievanhegan 

This works fine, but I've got a couple of notes:
1. When on the first page, I can pick a criteria at the top, you can't unselect it
2. I managed to carry out the process, but I can't see where I can check they've been added

(Alex)

**Comment by angievanhegan** [comment]
@russ-manta some new issues added from ALNAP. Up to you to decide if they're both in scope. Thanks

**Comment by russ-manta** [comment]
@Maria-alnap you can only check if tagsd have been added by looking at one of the resources you just tagged or re-run a search for that new tag and checking for the resource

**Comment by angievanhegan** [comment]
@Maria-alnap If you're happy with Russ's answer (above) please can you move this to done? Thanks

**Comment by Maria-alnap** [comment]
Happy. I'll move it
