### ISSUE TITLE
(#201) Migrate/Bulk upload of resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#95]
### Done criteria
- [x] Import existing resources and populate title field
 - [x] Consider how to import Crisis Category (used on portals)
 - [x] Consider content which should only be available within portals and not main resource search
- [x] Need to import Internal tags for each resource mapped to the same term in our taxonomy

__Internal tags to migrate__
- [x] ALNAP Steering Committee
- [x] ECB (This is a portal, so I'm not sure we'll need to be internal tags any longer)
- [x] Events and its subtags
- [x] Publications and its subtags
---
### ALNAP to check
- [ ] Confirm resources that have been imported have all relevant info compared to the current live site
- [x] Ability to filter on HELP library by type etc is all doable with the data that has been imported

**Comment by russ-manta** [comment]
@Maria-alnap could you provide any examples of resources which appear only within portals and not within the main HELP search?

**Comment by Maria-alnap** [comment]
@russ-manta, unfortunately we don't have any of those at the moment as we haven't had the need until now. That functionality is not enabled on the current site.

**Comment by russ-manta** [comment]
@Maria-alnap ok that's fine. We'll be adding this functionality but don't need to worry about it for the import.

**Comment by angievanhegan** [comment]
@meldera I added to the top box notes of the internal tags that Maria wants migrating. Does this create more work for you? Do we need to move it back to the 'in progress' column? Thanks

**Comment by angievanhegan** [comment]
@russ-manta What is the next step for this?

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan I'm only ticking the 2nd one here as the first one is not very clear to me. The few test resources added that I checked don't look like they have all the populated fields that a real resource would have.

**Comment by angievanhegan** [comment]
@Maria-alnap  We've actually created a new 'go live' tasks to migrate all the resources, so that's a better time to check they're all there! I'll move this to done. Thanks
