### ISSUE TITLE
(#201) Automatic capture of PDF front cover for resource

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#96]
### Done criteria
- [x] Add to resource view and node displays
- [x] When a resource is added, the front cover of the PDF is used as the image for the resource.
- [x] Image crop working as Steve wants it to work!
----
### Designs
- <a href="https://invis.io/ANC0GIX8Q">Resources wide</a>
- <a href="https://invis.io/ZTCBNO4N6">Resources mobile</a>
----
### ALNAP to check
[PDF front cover - example](http://alnap-dev.mrmdev.co.uk/test-innovation-resource)
- [x] Test uploading pdf and that the front page appears on the resource page and also in other displays that include that resource
----
### Notes

Estimated at £560

**Comment by angievanhegan** [comment]
Maria confirmed that this can come into scope.

**Comment by nadia847** [comment]
@russ-manta seeing an error although the actual generation seems to be working: 

-----
User error: ImageMagick error 1: convert.im6: unable to open image `convert': No such file or directory @ error/blob.c/OpenBlob/2641. convert.im6: no decode delegate for this image format `convert' @ error/constitute.c/ReadImage/544. in _imagemagick_convert_exec() (line 519 of imagemagick/imagemagick.module

-----
This might help:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=18287

**Comment by russ-manta** [comment]
can't find a fix for the error message but seems to be working ok so will leave as won't fix for now.

**Comment by angievanhegan** [comment]
@russ-manta Please can you add some 'ALNAP to check' criteria? Thanks

**Comment by angievanhegan** [comment]
@russ-manta Can this be assigned to @Maria-alnap  now to check?

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan This is working OK. See my test below for evidence :)

http://alnap-dev.mrmdev.co.uk/test-to-check-cover-capture

**Comment by ican-icant** [comment]
@nadia847 - there needs to be an automatic / default crop for the card as the image is a set size (and is landscape, not portrait). On the node the full image (not-cropped) can be displayed.

**Comment by nadia847** [comment]
@ican-icant They can crop it both landscape and portrait. Only landscape will show in the cards. I can make the crop required but thought it best it isn’t required until after all resource nodes have been imported in case the required crop breaks the importer. After that they will have to be manually cropped.

In terms of cropping, we have two options:

1. We can either set a fixed crop the always takes middle middle and they won’t be able to change where the image is cropped unless they crop it outside of drupal and re-upload it

or

2. they have a free crop available but it only applies a crop after they manually crop each image after import.

@pipemanta am I missing anything?

**Comment by angievanhegan** [comment]
@russ-manta should we make this part of the resources (extras) sprint goal (as per Nadia's suggestion of waiting until all the resource nodes have been imported)? Thanks

**Comment by russ-manta** [comment]
@angievanhegan no I don't think so this is pretty discrete as a piece of work.  @ican-icant did you have an issue with the size of the pdf image on the node? If so can you explain here?

**Comment by nadia847** [comment]
@russ-manta:  @ican-icant had a problem with the size of the image in the Resources views not the node - because the test one maria added was not cropped (though it is now). Even if we force having a crop because the image is taken from the PDF and isn't generated until after you save the page, not sure the requiredness will make much of a difference.

**Comment by angievanhegan** [comment]
@russ-manta What's the next step for this one?

**Comment by ican-icant** [comment]
@nadia847 not sure I understand what you mean?

**Comment by ican-icant** [comment]
@russ-manta  Each resource card (in a view) has a set image size, which means when the image is captured from the pdf it needs to be cropped to fit the set size. On the node the full capture of the pdf can be displayed, it's just the card the crop is needed.

Does this make sense? This was always the requirement.

Steve

**Comment by russ-manta** [comment]
@nadia847 can you resolve this one with Steve I'm not sure I know enough about this to help

**Comment by nadia847** [comment]
@russ-manta I've explained the sitch to steve and he's deferring to alnap for final decision.

**Comment by ican-icant** [comment]
No, there isn't really a decision @angievanhegan - there's only one way this works properly and we need to explain it to ALNAP.

**Comment by angievanhegan** [comment]
@matty-manta Can you help @Maria-alnap with this please? Thanks

**Comment by Maria-alnap** [comment]
Just thought I'd upload this for you to see, as the capture looks odd (the bg of that page is white, not black)

![glitch04cardimage.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593fc96377a396001a3a210d/125516c66e82c728ace21e0d46ef989337818bf9dbeabe51a054fd952e43653f6b14b1247a80e03cfd183954565c4faf465e5a46a9f88d7df5b63c72d90a5dbf826b0c66da2f53fde6d640e258f075c95d8fa4be8c46c1ed3d24ef8e8c483e16031d8ded10.PNG)

**Comment by nadia847** [comment]
Hi @Maria-alnap

Just made a tweak to the settings so that any transparency on pdf covers is removed (and made white). I re-uploaded the PDF and it now appears to be working.

Over to you... :o)

**Comment by Maria-alnap** [comment]
@nadia847 thanks!
@russ-manta There's one more thing in resources which is not showing up. We have tested adding a different image for the card of the above resource but it continues to load the cover. Can you check this? it may be that we want to use this quite often, as having boring report covers in the cards may look a bit dull

**Comment by angievanhegan** [comment]
@russ-manta Should this definitely be in done? From Maria's comment it sounds like there's more to do?

**Comment by nadia847** [comment]
@Maria-alnap that's because we were prioritising the cover. We've now switched it around so any card images will override the generated cover

**Comment by Maria-alnap** [comment]
@nadia847 aaah! That makes sense. Thanks for tweaking it :)
