### ISSUE TITLE
Payment system for jobs/events

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#97]
From OneNote:
- Members post for free and non-members pay per post. 
- Can we take payment pending approval?  
- Currently, automated email upon being approved with payment request.

Needs to use WorldPay
May have a manual process

**Comment by Maria-alnap** [comment]
We need clarity on the costing of this for the meeting at 2 today as well. This is a key functionality on our current site which needs to be enabled in new one from the moment we launch it.

**Comment by Maria-alnap** [comment]
(or at least a ball park figure)

**Comment by dave-manta** [comment]
@Maria-alnap I'm not sure we can give you a costing for this until we have clarification from Phil on how this works / what coding he has done for the integration?

**Comment by Maria-alnap** [comment]
Of course, @dave-manta. Have you reached out to him on this? Would you like me to chase him? 

We'd be happy to change the workflow for the approval/payment of these to make it happen. I spoke to our ops team earlier and they confirmed the world pay set up is just a link. The complicated bit would be automatising the publication of the job/event once payment has come through, but we'd be happy to change the process to make it work.

**Comment by dave-manta** [comment]
@Maria-alnap I'm going to move this discussion over to #76 as this is where we are scoping the requirements and will cost the implementation of this.  I will post your messages and respond on that thread.

**Comment by angievanhegan** [comment]
Hi @Maria-alnap - @russ-manta sent an email to Phil about this yesterday. Can you see if he can reply? We'd like to see if we can get this quote to you ASAP so that you can decide on everything on Friday. Thanks

**Comment by angievanhegan** [comment]
This is a duplicate. I'm archiving it.
